openshift/cluster-ingress-operator

- images/cluster-ingress-operator/Dockerfile
/cc @openshift/sig-network-edge 
1. Product builds require the Dockerfile in this location
2. Turns out the product builds don't yet support multistage all the way up and down the stack yet; once they do we can replace this Dockerfile with the multistage contents
3. After this merges, we can go ahead and switch CI to point to this file
> Add Dockerfile for product builds

- HACKING.md
- deploy/cluster-ingress-operator.yaml
This manifest is needed in order to run the
Cluster Ingress Operator as a container inside
OpenShift.
Also added running information to the documentation.
> Add operator manifest

- HACKING.md
- Makefile
- test/integration/integration_test.go
- CRD is created as part of the test
- WATCH_NAMESPACE env is now optional
Command to run integration tests:
```
KUBECONFIG=<admin.kubeconfig> CLUSTER_NAME=<gcp-cluster-name> make test-integration
```
> Simplify running integration tests

- deploy/namespace.yaml
The Cluster Ingress Operator Service Account needs a namespace
for isolating permissions.
> Add Namespace for Cluster Ingress Operator

- deploy/01_namespace.yaml
- deploy/02_crd.yaml
- deploy/03_rbac.yaml
- deploy/04_cluster-ingress-operator.yaml
- deploy/05_cr.yaml
In order to deploy a cluster ingress operator some
resource have to be deployed in a specific order.
The point of this patch is to allow user to issue a
oc create -f deploy/.
> Set deployment order

- examples/cr.yaml
Some manifests are needed to manage an test the Cluster Ingress Operator, this patch adds the
custom resource creation example.
> Add examples directory

- cmd/cluster-ingress-operator/main.go
- pkg/stub/handler.go
- pkg/util/slice/slice.go
Refactor the handler to be level driven.
/cc @openshift/sig-network-edge
> Refactor to level driven design

- hack/release-local.sh
Fix the `cp` command in `release-local.sh` to copy the manifest files directly into the temporary directory rather than copying the `manifests/` directory as a subdirectory of the temporary directory.  This change causes the subsequent `sed` command to overwrite the `02-deployment.yaml` file.
Before this commit, the `cp` command in `release-local.sh` was copying the `manifests/` directory under the temporary directory, and the subsequent `sed` command was creating a second `02-deployment.yaml` file in the temporary directory, as shown below:
/tmp/tmp.8gU85s0EC2
├── 02-deployment.yaml
└── manifests
├── 00-cluster-role.yaml
├── 00-custom-resource-definition.yaml
├── 00-namespace.yaml
├── 01-cluster-role-binding.yaml
├── 01-role-binding.yaml
├── 01-role.yaml
├── 01-service-account.yaml
├── …
> release-local.sh: Fix cp command for manifests

- hack/release-local.sh
Check in `release-local.sh` whether Buildah is available, and use it if it is.  Setting the `DOCKER` environment variable forces the use of Docker.
> release-local.sh: Use Buildah if available.

- Makefile
- manifests/00-cluster-role.yaml
- test/e2e/operator_test.go
Add baseline end-to-end tests for cluster-ingress-operator.
This commit is related to NE-96.
https://jira.coreos.com/browse/NE-96
* `Makefile` (`test-e2e`): Add target.
* `test/e2e/operator_test.go`: Add tests.
Give the operator permission to update the clusteroperator's `status` subresource.
* `manifests/00-cluster-role.yaml`: Allow the operator to update the clusteroperator's `status` subresource.
This change is a followup https://github.com/openshift/cluster-ingress-operator/pull/65.
> Add baseline end-to-end tests

- pkg/dns/aws/dns.go
The tectonicClusterID tag is being replaced with openshiftClusterID in the installer. This change will use the new tag name.
Hold on openshift/installer#817.
/hold
> replace tectonicClusterID tag with openshiftClusterID

- pkg/apis/ingress/v1alpha1/clusteringress_types.go
- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
Add a high-availability strategy that exposes ports 80 and 443 as endpoints on the host network and leaves implementation of high-availability up to the user.
* `pkg/apis/ingress/v1alpha1/clusteringress_types.go`: Define `UserDefinedClusterIngressHA`.
* `pkg/manifests/manifests.go` (`RouterDeployment`): If HA type is `UserDefinedClusterIngressHA`, use host network, and configure probes to use localhost (defaulting to the node IP address could cause problems if it is not routable or is blocked by a firewall).
* `pkg/manifests/manifests_test.go`: Test with `nil`, `CloudClusterIngressHA`, and `UserDefinedClusterIngressHA`.
This PR resolves [NE-116](https://jira.coreos.com/browse/NE-116).
---
@ironcladlou
Should I add handling of updates, so the operator deletes any service LB if one exists …
> Add UserDefinedClusterIngressHA

- cmd/cluster-ingress-operator/main.go
- manifests/00-cluster-role.yaml
- pkg/util/config.go
Consume cluster ID from its stable location in config.openshift.io. The previous
field on the install configmap is deprecated.
Blocks https://github.com/openshift/installer/pull/783.
> Consume cluster ID from config.openshift.io

- pkg/manifests/manifests.go
- test/e2e/operator_test.go
Noticed this while fixing up the router tests in origin - the service selector for the internal service adds an extra selector which causes issues. PTAL Thx
/cc @openshift/sig-network-edge
> Fix selector for internal router service, so that it is correctly populated

- pkg/dns/aws/dns.go
https://github.com/openshift/cluster-ingress-operator/pull/93 changed the DNS private zone discovery to use the `GetResources` AWS API call.  However, even though we use filters, the resources are still paginated as though no filter were applied.  If the desired resource is not on the first page, then `GetResources` will not return it.  We need to use `GetResourcesPages`, and we may need to look through one or more empty pages of resources till we find the desired resource.
* `pkg/dns/aws/dns.go`: Use `GetResourcesPages` to get the private zone.
---
@ironcladlou @wking
> Cope with pagination in private zone discovery

- pkg/dns/aws/dns.go
Follow-up to #99.
* `pkg/dns/aws/dns.go` (`discoverZones`): Use `kerrors.NewAggregate` to combine error values from GetResourcesPages and its callback.
> Improve error handling in private zone discovery

- manifests/00-cluster-role.yaml
- pkg/operator/controller/controller.go
- pkg/operator/controller/status.go
- pkg/operator/controller/status_test.go
- test/e2e/operator_test.go
Break out #89  to just handle updates to a subset of the generated assets. The PR only handles updating the router namespace and deployment assets.
> [NE-72] Handle updates to ClusterIngress and update a subset of the generated ingress assets

- manifests/02-deployment.yaml
An operator deployed by the CVO should run on the master.
> Restrict operator to masters

- README.md
Bugs are tracked in Bugzilla. GitHub issues are disabled for the repository, so make a note in the README to redirect users to Bugzilla.
> docs/readme: Add Bugzilla issue reporting link

- Gopkg.lock
- manifests/00-cluster-role.yaml
- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
- pkg/operator/controller/controller.go
- test/e2e/operator_test.go
- vendor/github.com/openshift/library-go/LICENSE
- vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
- vendor/github.com/openshift/library-go/pkg/crypto/rotation.go
- vendor/k8s.io/apiserver/LICENSE
- vendor/k8s.io/apiserver/pkg/authentication/user/doc.go
- vendor/k8s.io/apiserver/pkg/authentication/user/user.go
Generate a CA certificate and use it to generate default certificates for routers.  Publish the CA certificate in a configmap, which can be incorporated into CA bundles in order to trust the default certificates.
This PR resolves [NE-139](https://jira.coreos.com/browse/NE-139).
* `manifests/00-cluster-role.yaml`: Grant the operator create, get, list, watch, and delete access to configmaps.
* `pkg/manifests/manifests.go` (`RouterServiceInternal`): Change serving-cert secret name so as not to conflict with the secret that the operator creates.
* `pkg/manifests/manifests_test.go` (`TestManifests`): Adjust for the change to `RouterServiceInternal`.
* `pkg/operator/controller/controller.go` (`caCertSecretName`):
(`caCertConfigMapName`): New constants for the name of the secret and configmap …
> Use self-signed default router certificate

- manifests/00-cluster-role.yaml
- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_test.go
- test/e2e/operator_test.go
* `manifests/00-cluster-role.yaml`: Grant the operator create, get, list, watch, and delete access to configmaps.
* `pkg/operator/controller/controller.go` (`globalMachineSpecifiedConfigNamespace`): New constant for the `openshift-config-managed` namespace.
(`ensureRouterCACertificate`): Create the `router-ca` configmap in `openshift-config-managed`.
* `test/e2e/operator_test.go` (`TestRouterCACertificate`): Get the `router-ca` configmap from the `openshift-config-managed` namespace.
* `pkg/operator/controller/controller.go` (`reconcile`): Rename `errors` variable to `errs` to avoid shadowing the `errors` package.
* `pkg/operator/controller/controller.go` (`CACert`): Delete.
(`Config`): Delete CACert.
(`ensureRouterCACertificate`): Delete caching.
If there exists no clusteringress that …
> Put router-ca configmap in openshift-config-managed iff needed

- manifests/00-ingress-credentials-request.yaml
Relocated from cloud-credentials-operator repo per recent discussions.
Ingress team will have control over your own creds going forward.
> Add credentials request for AWS.

- pkg/manifests/manifests.go
- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_lb.go
- pkg/operator/operator.go
Before this change, the ingress controller was receiving edge triggered events
for related resources, requiring us to look up the entire ingress list on every
event because we had no association from the related resources to the ingress.
With this change, related resources which should trigger a clusteringress
reconcile are labelled to refer to their owning clusteringress. This allows the
use of the controller-runtime `Mapper` interface to translate events for related
resources into clusteringress events. Now the ingresss controller can reconcile
a single clusteringress, which is:
1. Easier to understand and refactor, fitting with the way a controller should
be structured
2. Less susceptible to hot loop bugs, as related resource events can now be
coalesced and rate limited at the scope of …
> controller: refactor event triggering

- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_ca_configmap.go
- pkg/operator/controller/controller_ca_secret.go
- pkg/operator/controller/controller_default_certificate.go
* `pkg/operator/controller/controller.go` (`caCertConfigMapName`, `GlobalMachineSpecifiedConfigNamespace`, `shouldPublishRouterCA`, `ensureRouterCAIsPublished`, `ensureRouterCAIsUnpublished`): Move from here...
* `pkg/operator/controller/controller_ca_configmap.go`: ...to this new file.
* `pkg/operator/controller/controller.go` (`caCertSecretName`, `ensureRouterCACertificateSecret`, `getRouterCA`): Move from here...
* `pkg/operator/controller/controller_ca_secret.go`: ...to this new file.
* `pkg/operator/controller/controller.go` (`ensureDefaultCertificateForIngress`, `ensureDefaultCertificateDeleted`): Move from here...
* `pkg/operator/controller/controller_default_certificate.go`: ...to this new file.
* `pkg/operator/controller/controller.go`: Refactor configmap publishing...
* …
> Set pathlen constraint on router-ca

- hack/uninstall.sh
- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_dns.go
- pkg/operator/controller/controller_lb.go
When reconciling a clusteringress, establish the invariant that DNS and
Infrastructure cluster config must exist; this makes it easier to deal with
error handling and there's little we can do without cluster config anyway. Make
it possible to do some additional work when not able to reconcile a
clusteringress. Pass DNS and Infrastructure around where needed for consistency
with the other refactored bits.
> controller: clean up error handling

- manifests/03-cluster-operator.yaml
This makes the operator conform to:
https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md
> manifests: Add ClusterOperator resource

- hack/uninstall.sh
Running hack/uninstall.sh would produces a not found error when attempting to delete the ClusterOperator" resource named 'openshift-ingress-operator'. This PR updates the name to 'ingress'.
> Updates ingress clusteroperator name in hack/uninstall

- pkg/dns/aws/dns.go
As example of this terraform-provider-aws [1]
[1]: https://github.com/terraform-providers/terraform-provider-aws/blob/98f11aecb078d82fd7d9b59e5307874797d8f359/aws/config.go#L420
> dns/aws: include operator version in UserAgent for AWS API calls

- pkg/dns/aws/dns.go
Before this change, the DNS manager made unfiltered AWS DescribeLoadBalancer
calls every time a clusteringress was reconciled. After this change, the
pertinent results of the DescribeLoadBalancer call are cached to reduce the
number of calls to once per existing load balancer service during the lifetime
of the operator process.
> dns/aws: cache load balancer hosted zones

- pkg/dns/aws/dns.go
- pkg/log/log.go
- pkg/operator/controller/controller.go
- pkg/operator/operator.go
PR #126 was merged before implementing final touches to improve contextual information of log messages. This PR prevents reporting the wrapper code as the caller and reduces the verbosity of logger names.
> Improves zapr logger contextual information

- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_dns.go
- pkg/operator/controller/controller_lb.go
- pkg/operator/controller/controller_router_deployment.go
- pkg/operator/controller/controller_router_deployment_test.go
Determine the effective HA configuration and persist it to the clusteringress's status at the beginning of reconciling a clusteringress. Use the HA configuration from status for subsequent reconciliation steps and future reconciling.
* `pkg/operator/controller/controller.go` (`Reconcile`): Use `enforceEffectiveIngressDomain` to ensure the clusteringress's status has the effective HA configuration in its status.
(`effectiveHighAvailability`): Rename...
(`enforceEffectiveHighAvailability`): ... to this.  Publish the effective HA configuration to the clusteringress's status.
(`ensureIngressDeleted`): Delete `ha` variable.  Delete argument to `finalizeLoadBalancerService`.
(`ensureRouterNamespace`): Delete `ha` variable and argument to `ensureRouterNamespace`, `ensureLoadBalancerService`, …
> Treat HA configuration as immutable

- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_default_certificate.go
- pkg/operator/controller/controller_dns.go
- pkg/operator/controller/controller_lb.go
- pkg/operator/controller/controller_router_deployment.go
- pkg/operator/controller/controller_service_monitor.go
- Do not use Result.Requeue or Result.RequeueAfter when returning errors
as controller will ignore these Requeue/RequeueAfter fields and the current
item is automatically rate limited.
- Some more cleanup:
* Caller will invoke sub methods only when the prereq args are valid.
* Tolerate some failures and try to create/update as many related resources
as possible during reconcile.
> Process as much as possible during reconcile and requeue in case of any errors

- cmd/cluster-ingress-operator/main.go
PR #122 was closed before PR #126 was implemented. This PR adds an info-level log message stating the secret being used by DNSManager. I found this to be helpful while troubleshooting dns and learning how DNSManager works.
> Adds info log msg indicating ns/secret used by DNSManager

- hack/uninstall.sh
- pkg/operator/controller/certificate/ca.go
- pkg/operator/controller/certificate/controller.go
- pkg/operator/controller/certificate/default_cert.go
- pkg/operator/controller/controller.go
- pkg/operator/operator.go
Relocate default wildcard certificate generation to the certificate controller to more
clearly decouple certificate management from ingress reconcilication.
Change the certificate controller event handling so that reconciliation is
triggered by clusteringress events. This makes the reconciliation code in the
controller easier to reason about and means we only do cert management if
there's a clusteringress around. It also means we can easily react to
clusteringresses being added/deleted.
Depends on https://github.com/openshift/cluster-ingress-operator/pull/140
Supports https://github.com/openshift/cluster-ingress-operator/pull/139
> controller/certificate: move cert generation to cert controller

- hack/uninstall.sh
- manifests/00-cluster-role.yaml
- pkg/log/log.go
- pkg/operator/controller/certificate/ca.go
- pkg/operator/controller/certificate/controller.go
- pkg/operator/controller/certificate/default_cert.go
- pkg/operator/controller/certificate/publish_ca.go
- pkg/operator/controller/certificate/publish_ca_test.go
- pkg/operator/controller/controller.go
- pkg/operator/controller/names.go
Move CA publishing logic into the certificate controller to finish the
separation of concerns between core ingress reconciliation and certificate
management.
Start consolidating object naming into `names.go` which is shared by
controllers.
Publish more events when possible.
Depends on https://github.com/openshift/cluster-ingress-operator/pull/141
Supports https://github.com/openshift/cluster-ingress-operator/pull/139
> controller/certificate: relocate CA publishing

- hack/uninstall.sh
- pkg/operator/controller/certificate/controller.go
- pkg/operator/controller/certificate/default_cert.go
- pkg/operator/controller/certificate/publish_certs.go
- pkg/operator/controller/certificate/publish_certs_test.go
- pkg/operator/controller/names.go
Publish a `router-certs` secret in the `openshift-config-managed` namespace that has all routers' configured default certificates and their private keys.
This commit resolves [NE-166](https://jira.coreos.com/browse/NE-166).
* `pkg/operator/controller/names.go` (`routerCertsGlobalSecretName`): New constant.
(`RouterCertsGlobalSecretName`): New function to generate the namespaced name for the secret with the routers' default certificates and their keys.
* `pkg/operator/controller/certificate/publish_certs.go`: New file.
(`ensureRouterCertsGlobalSecret`): New method that creates, updates, or deletes the secret as needed.
(`desiredRouterCertsGlobalSecret`): New function.
(`currentRouterCertsGlobalSecret`, `createRouterCertsGlobalSecret`, `updateRouterCertsGlobalSecret`, …
> Publish global secret with default certificates and keys

- pkg/operator/controller/certificate/default_cert.go
- pkg/operator/controller/certificate/publish_certs.go
- pkg/operator/controller/controller_router_deployment.go
- pkg/operator/controller/names.go
* `pkg/operator/controller/names.go`
(`RouterDefaultCertificateSecretName`): Rename...
(`RouterOperatorGeneratedDefaultCertificateSecretName`): ...to this.
(`RouterEffectiveDefaultCertificateSecretName`): New function to get the name of the in-use router default certificate secret.
* `pkg/operator/controller/certificate/default_cert.go` (`desiredRouterDefaultCertificateSecret`, `currentRouterDefaultCertificate`): Use `RouterOperatorGeneratedDefaultCertificateSecretName`.
* `pkg/operator/controller/certificate/publish_certs.go` (`desiredRouterCertsGlobalSecret`):
* `pkg/operator/controller/controller_router_deployment.go` (`desiredRouterDeployment`): Use `RouterEffectiveDefaultCertificateSecretName`.
---
This PR addresses https://github.com/openshift/cluster-ingress-operator/pull/139#discus …
> Add function for name of in-use default certificate

- pkg/operator/controller/certificate/default_cert.go
Fix a nil pointer dereference in the delete code path.
* `pkg/operator/controller/certificate/default_cert.go` (`ensureDefaultCertificateForIngress`): Use `current.Name` when recording the deletion event.
@ironcladlou
> ensureDefaultCertificateForIngress: Fix nil pointer

- pkg/manifests/manifests.go
- pkg/operator/controller/certificate/default_cert.go
- pkg/operator/controller/certificate/publish_ca.go
- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_lb.go
- pkg/operator/controller/controller_service_monitor.go
- If we are just creating resource with out get op, then IsAlreadyExists()
check is needed but when we are using get resource and in case of not found
error, creating the resource then this check is unnecessary as we know that
this error will not occur.
- Once we create the resource, we don't need to do get op on the same resource
to get the latest info of the object.
- Remove stale 'MetricsServiceMonitorAsset' constant, no longer needed
> Remove unnecessary IsAlreadyExists() checks during resource creation.

- pkg/operator/controller/certificate/ca.go
- pkg/operator/controller/certificate/publish_ca.go
- pkg/operator/controller/certificate/publish_certs.go
Avoid "Could not construct reference to: [...] due to: 'selfLink was empty, can't make reference'. Will not report event: [...]" errors from the event recorder by using an object we have gotten from the API, as opposed to one we have constructed ourselves (which is missing the self link).
* `pkg/operator/controller/certificate/ca.go` (`ensureRouterCASecret`): After creating the secret, get the newly created object from the API.  Use the object from the API for the event recorder and for the return value.
* `pkg/operator/controller/certificate/publish_ca.go` (`ensureRouterCAConfigMap`): After creating the configmap, get the newly created object from the API, and use this object for the event recorder. When updating the configmap, use the object we got earlier from the API for the event …
> Use object from API when recording an event

- pkg/operator/controller/controller_router_deployment.go
- pkg/operator/controller/controller_router_deployment_test.go
Fix assumptions in `deploymentConfigChanged` about the deployment's pod template spec, and make the comparison and update more general.  Specifically, do not assume that the deployment has any volumes, do use `cmp.Equal` to compare the entire slice of volumes rather than only checking the first, and use a `for` loop plus `DeepCopy` to copy the updated volumes.
Before this change, `deploymentConfigChanged` did not react to changes to other volumes and could even panic with an out-of-bounds index if there were no volumes.  Any deployment that the operator creates will always have at least one volume, but we might as well be resilient in case someone else directly modifies the deployment.
* `pkg/operator/controller/controller_router_deployment.go` (`deploymentConfigChanged`): Delete a stale …
> Improve and expand checks in deploymentConfigChanged

- pkg/operator/controller/controller_router_deployment.go
- pkg/operator/controller/controller_router_deployment_test.go
* `pkg/operator/controller/controller_router_deployment.go` (`deploymentConfigChanged`): Compare the container image.  Set the container image in the updated deployment.
* `pkg/operator/controller/controller_router_deployment_test.go` (`TestDeploymentConfigChanged`): Add a test case for the container image.
> Bug 1673993: deploymentConfigChanged: Check container image

- pkg/operator/controller/controller.go
* `pkg/operator/controller/controller.go` (`haTypeForInfra`): Use `HostNetwork` as the default endpoint publishing strategy if the platform is libvirt.
* `pkg/operator/controller/controller.go` (`haTypeForInfra`): Rename...
(`publishingStrategyTypeForInfra`): ...to this.
(`enforceEffectiveHighAvailability`): Rename...
(`enforceEffectiveEndpointPublishingStrategy`): ...to this.
> Bug 1688099: Default to HostNetwork on libvirt

- test/e2e/operator_test.go
The 30s poll time has caused CI test flakes. I recently experienced the flake locally for a new cluster. 60s should provide ample time to ensure a controller deployment has completed.
> Increases poll time to 60s for ingress create/delete e2e test

- cmd/cluster-ingress-operator/main.go
We're already declaring port 60000 for operator prometheus metrics.
This change enables the operator metrics listener on port 60000.
Example of metrics specific to controller-runtime which are captured by default:
```
$ curl http://localhost:60000/metrics                                                      
controller_runtime_reconcile_queue_length{controller="certificate-controller"} 0            
controller_runtime_reconcile_queue_length{controller="operator-controller"} 0                  
controller_runtime_reconcile_time_seconds_bucket{controller="certificate-controller",le="0.005"} 0
controller_runtime_reconcile_time_seconds_bucket{controller="certificate-controller",le="0.01"} 0
controller_runtime_reconcile_time_seconds_bucket{controller="certificate-controller",le="0.025"} 0 …
```
> metrics: enable by default

- manifests/00-ingress-credentials-request.yaml
in order to avoid the CVO periodically applying v1beta1 and then having the cloud-cred-operator migrate it to v1 (see https://bugzilla.redhat.com/show_bug.cgi?id=1690069 ), just update the credentialsrequest in the manifests dir to v1 (no changes from v1beta1 to v1)
> update credentialsrequest from v1beta1 to v1

- pkg/operator/controller/certificate-publisher/controller.go
- pkg/operator/controller/certificate-publisher/publish_certs.go
- pkg/operator/controller/certificate-publisher/publish_certs_test.go
- pkg/operator/controller/certificate/controller.go
- pkg/operator/operator.go
- test/e2e/certificate_publisher_test.go
- test/e2e/operator_test.go
Extract a new `certificate-publisher-controller` out of the existing `certificate-controller`.  The new controller watches ingresscontrollers in the operator namespace and default-certificate secrets in operand namespace and updates the `router-certs` secret in the `openshift-config-managed` namespace.
Because `certificate-controller` watches ingresscontrollers and not secrets, it was failing to update `router-certs` in some situations where the secret needed to be updated.  In particular, creating, updating, or deleting a secret _after_ creating an ingresscontroller that references the secret should cause `router-certs` to be updated.  The new controller ensures that `router-certs` is updated in this scenario.
* `pkg/operator/controller/certificate/controller.go` (`Reconcile`): Remove …
> Bug 1687931: Add certificate-publisher-controller

- pkg/operator/controller/controller_dns.go
- pkg/operator/controller/controller_lb.go
When finalizing a load-balancer service, check whether it has been provisioned, and if not, skip cleaning up its DNS records.
Before this commit, if an ingresscontroller was created with the `LoadBalancerService` endpoint publishing strategy and subsequently deleted before the load balancer had been provisioned, the finalization logic returned an error, which caused the controller to retry and fail to finalize the service repeatedly.
* `pkg/operator/controller/controller_dns.go` (`ensureDNS`): Check whether the load balancer has been provisioned.  Return an error if not.  Pass the host name from the load balancer to `desiredDNSRecords`.
(`desiredDNSRecords`): Take a host name instead of a load-balancer service.
* `pkg/operator/controller/controller_lb.go` (`finalizeLoadBalancerService`): …
> Fix load-balancer finalization

- cmd/cluster-ingress-operator/main.go
- pkg/operator/client/client.go
- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_internal_service.go
- pkg/operator/controller/controller_lb.go
- pkg/operator/controller/controller_router_deployment.go
- pkg/operator/controller/controller_service_monitor.go
- pkg/operator/controller/status.go
- pkg/operator/operator.go
- test/e2e/operator_test.go
- Use a new kube client for fetching and creating ServiceMonitor resource
to avoid cached REST scheme/mapper of controller client.
> Bug 1687640: Fix creation of service monitor to report router metrics

- pkg/operator/controller/controller_router_deployment.go
- pkg/operator/controller/controller_router_deployment_test.go
Fix several problems in how `deploymentConfigChanged` compares volumes that could cause spurious updates to the router deployment.
* `pkg/operator/controller/controller_router_deployment.go` (`cmpEnvs`): Add helper function.
(`deploymentConfigChanged`): Use it.
Ignore the ordering of volumes in the deployment's pod template spec when comparing deployments.
* `pkg/operator/controller/controller_router_deployment.go` (`deploymentConfigChanged`): Sort volumes on name when comparing volumes.
(`cmpVolumes`): New helper function.
* `pkg/operator/controller/controller_router_deployment_test.go` (`TestDeploymentConfigChanged`): Add test case for volumes changing ordering.
The default value for a secret volume source's default mode is 420, so treat a nil value as equal to 420.
* …
> deploymentConfigChanged: Fix volume comparison

- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
- pkg/operator/controller/controller.go
- pkg/operator/controller/status.go
Convert the `RouterNamespace` method into a function, and change it not to return an error value.
* `pkg/manifests/manifests.go` (`RouterNamespace`): Rename constant...
(`RouterNamespaceAsset`): ...to this.
(`RouterNamespace`): Drop the receiver and the error return value.  Panic if unable to read the asset.  Otherwise return the asset.
* `pkg/manifests/manifests_test.go`: Adjust test for `RouterNamespace`.
* `pkg/operator/controller/controller.go` (`ensureRouterNamespace`):
* `pkg/operator/controller/status.go` (`getOperatorState`): Adjust calls to `RouterNamespace`.
---
An alternative approach is to delete the router namespace asset and construct the namespace object in Go code.  See https://github.com/Miciah/cluster-ingress-operator/commit/895d7c5ebb6fc0fbbc06f0817654f1536faae65d:
* …
> manifests: Simplify RouterNamespace

- pkg/operator/controller/certificate/controller.go
- pkg/operator/controller/controller.go
- test/e2e/operator_test.go
Currently, the operator does not prevent duplicate domains among different IngressControllers.
This PR adds a domain conflict check. If an `IngressController` is created with a domain that is equal to an existing `IngressController`, the operator will log the conflict and dependent resources will not be created. When https://github.com/openshift/cluster-ingress-operator/pull/174 merges, the log message and checks for `len(status.domain) == 0` checkes should be transitioned to status condition checks.
> Bug 1683765: Ensure IngressController domain is unique

- pkg/operator/controller/controller.go
- pkg/operator/controller/ingress_status.go
- pkg/operator/controller/ingress_status_test.go
- pkg/operator/controller/status.go
- pkg/operator/controller/status_test.go
Previously, ingresscontroller status conditions were not implemented.
This commit does the following:
- Implements the ingresscontroller `Available` status condition.
- Refactors ingress operator `Progressing` and `Available` status conditions to be calucalted from the ingresscontroller `Available` condition.
- Replaces deployment logic from ingress operator unit tests with ingresscontroller `Available` conditions.
- Adds ingresscontroller `Available` condition unit tests.
Provides the foundation for fixing bug 1683765 by reporting domain conflicts through status conditions.
> Bug 1690333: Implement IngressController Available Status Condition

- HACKING.md
- Makefile
- hack/buildconfig.yaml
- hack/create-buildconfig.sh
- hack/start-build.sh
Provide a buildconfig, shell scripts, Makefile targets, and instructions for building the operator remotely on a cluster using the buildconfig.
* `HACKING.md`: Add instructions for building using a buildconfig.
* `Makefile`: Add `buildconfig` and `cluster-build` targets.
* `hack/buildconfig.yaml`: New file.
* `hack/create-buildconfig.sh`: New file.
* `hack/start-build.sh`: New file.
> Add instructions for building remotely on a cluster

- Makefile
- manifests/00-custom-resource-definition.yaml
PR #185 is required before merging.
Previously, `IngressController` resource fields were not validated. Additionally, the associated CRD was manually managed. This commit adds:
- OpenAPI v3 schema validation to the `IngressController` custom resource and partially fixes Bug [1683766](https://bugzilla.redhat.com/show_bug.cgi?id=1683766).
- Adds `make crd` and `make verify-crd` to generate and verify crd modification respectively.
__Note:__ The schema is based on the currently vendored api definitions (853a7faf74b1c63a56e4010d39057559fa13271f) and not the latest from openshift/api.
> Adds IngressController CRD Validation & Generation

- cmd/ingress-operator/main.go
- pkg/operator/controller/status.go
- Checks for `RELEASE_VERSION` env var and sets it to "unknown" if missing.
- Updates status code to stop checking for missing `RELEASE_VERSION`
- Decomposes `computeOperatorStatusConditions()` so individual conditions can be computed.
> Minor Operator Status Refactor

- pkg/operator/controller/controller_router_deployment.go
Always update tolerations if the router deployment has changed,
Before this commit, `deploymentConfigChanged` only updated the tolerations on the deployment if the deployment was expected to have tolerations.  As a result, `deploymentConfigChanged` did not remove tolerations when the deployment had tolerations and was expected not to.
* `pkg/operator/controller/controller_router_deployment.go` (`deploymentConfigChanged`): Delete condition for assignment of tolerations.
> Bug 1701462: deploymentConfigChanged: Fix deleting tolerations

- hack/start-build.sh
Do not override the `IMAGE` environment variable when patching the operator deployment.  `IMAGE` specifies the operand image, and the patch should only change the operator image.
* `hack/start-build.sh`: Delete the `IMAGE` environment variable from the patch to the operator deployment.
> start-build.sh: Don't patch operator IMAGE env var

- cmd/ingress-operator/main.go
This import was added accidentally.
* `cmd/cluster-ingress-operator/main.go`: Delete import of the client-go GCP auth plug-in.
> Delete registration of client-go GCP auth plug-in

- manifests/00-namespace.yaml
**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …
> Add node-selector annotation to namespace

- cmd/ingress-operator/main.go
- manifests/03-cluster-operator.yaml
- pkg/operator/config/config.go
- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_router_deployment.go
- pkg/operator/controller/controller_router_deployment_test.go
- pkg/operator/controller/status.go
- pkg/operator/controller/status_test.go
- pkg/operator/operator.go
- Always report 'operator' version irrespective of available condition.
- For upgrades, report old versions until the new version is fully applied.
> Bug 1704982: Fix updating versions for ingress cluster operator

- test/e2e/operator_test.go
Get the ingress controller from the API in between updates so that that each update uses the latest resource version in order to prevent the following test failure:
--- FAIL: TestIngressControllerScale (2.62s)
operator_test.go:517: failed to update ingresscontroller: Operation cannot be fulfilled on ingresscontrollers.operator.openshift.io "default": the object has been modified; please apply your changes to the latest version and try again
* `test/e2e/operator_test.go` (`TestIngressControllerScale`): Get the ingress controller in between updates to ensure we have the latest resource version for each update.
---
@ironcladlou, it looks like https://github.com/openshift/cluster-ingress-operator/pull/223 was insufficient—I saw the above failure here: …
> Bug 1705100: TestIngressControllerScale: Re-get between updates

- hack/release-local.sh
- As per the spec[1], ClusterOperator resource must be created by the operator.
[1] https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md#how-clusterversionoperator-handles-clusteroperator-in-release-imagehttps://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md#how-clusterversionoperator-handles-clusteroperator-in-release-image
> Fix hack/release.sh: Skip ClusterOperator resource creation

- manifests/02-deployment.yaml
In 4.1, we have taint-based evictions enabled. This changes logic in the node lifecycle controller in the kube-controller-manager significantly.
Historically, the node lifecycle controller would directly evict pods from node that had a Ready condition of False or Unknown after a pod eviction timeout set by the --pod-eviction-timeout flag on the kube-controller-manager. This setting applied to all pods cluster-wide. The default was 5m.
With taint-based evictions, all the node lifecycle controller does is taint the node with node.kubernetes.io/unreachable and/or node.kubernetes.io/not-ready taint with NoExecute effect. This would normally result in the immediate eviction of all pods that don't tolerate those taints, breaking the old behavior with pod eviction timeouts. Enter …
> Fix tolerations

- pkg/operator/controller/status.go
- pkg/operator/controller/status_test.go
* `pkg/operator/controller/status.go`:
* `pkg/operator/controller/status_test.go` (`syncOperatorStatus`): Pass old versions to `computeOperatorStatusConditions`.
(`computeOperatorStatusConditions`): Pass old versions to `computeOperatorProgressingCondition`.
(`computeOperatorProgressingCondition`): Add "Upgraded x to y" message if old and current versions of an image do not match.
(`TestComputeOperatorStatusConditions`): Add test cases.
---
See https://github.com/openshift/cluster-dns-operator/pull/104#issuecomment-489663676.
> Bug 1707085: Update Progressing condition if upgrade happened

- cmd/ingress-operator/main.go
- pkg/dns/aws/dns.go
Access to ec2 metadata will soon be restricted
(https://github.com/openshift/origin/pull/22826). Eliminate the ec2 metadata
dependency by discovering AWS region information from cluster config. This
commit uses the deprecated install config for metatadata; once
https://github.com/openshift/installer/pull/1725 merges, supported cluster
config will provide the region information and the code can be refactored.
> Bug 1706576: Eliminate ec2 metadata dependency

- pkg/operator/controller/controller.go
- pkg/operator/controller/ingress_status.go
- pkg/operator/controller/ingress_status_test.go
- pkg/operator/controller/status.go
- pkg/operator/controller/status_test.go
- LastTransitionTime field is only changed when there is a change,
so we expect LastTransitionTime to remain the same when there is no change.
- Some refactor related to handling of ingress status conditions and corresponding tests.
> Don't ignore LastTransitionTime when comparing ingress controller status conditions

- pkg/operator/controller/controller.go
This commit is related to [NE-185](https://jira.coreos.com/browse/NE-185).
* `pkg/operator/controller/controller.go` (`publishingStrategyTypeForInfra`): Use `LoadBalancerServiceStrategyType` for Azure.
---
API change: https://github.com/openshift/api/pull/311
> publishingStrategyTypeForInfra: Add case for Azure

- pkg/operator/controller/controller.go
- pkg/operator/controller/ingress_status.go
- pkg/operator/controller/ingress_status_test.go
- pkg/operator/operator.go
- test/e2e/operator_test.go
Compute LoadBalancer* status conditions on IngressController resources. Do so by
introducing some new cache/index capabilities.
> Add LoadBalancer status reporting on IngressController

- pkg/operator/controller/controller_service_monitor.go
Previously the selector of ServiceMonitor is null, it causes `TLS handshake error from x.x.x.x:xx: remote error: tls: bad certificate` in router pod logs if creating another custom ingresscontroller.
The message is gone after adding proper selector to each ServiceMonitor.
note: the `x.x.x.x` in the log is prometheus pod's IP.
> add selector to servicemonitor

- cmd/ingress-operator/main.go
- hack/uninstall.sh
- pkg/operator/controller/certificate-publisher/controller.go
- pkg/operator/controller/certificate/controller.go
- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_service_monitor.go
- pkg/operator/controller/status.go
- pkg/operator/operator.go
- pkg/util/restmapper.go
* Delete custom cache setup, switch exclusively to `MultiNamespacedCache`
* Consolidate client usage and use dynamic discovery (see https://github.com/kubernetes-sigs/controller-runtime/issues/321 — hat tip to @danwinship for https://github.com/openshift/cluster-network-operator/pull/95). Fixes [bz1717494](https://bugzilla.redhat.com/show_bug.cgi?id=1717494).
* Plumb the cache through for indexed lookups
> Bug 1717494: Refactor client and cache handling

- manifests/00-cluster-role.yaml
- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_lb.go
- pkg/operator/controller/ingress_status.go
- pkg/operator/controller/ingress_status_test.go
- pkg/operator/controller/names.go
- pkg/operator/operator.go
When an LB is determined to be pending, try and surface more detail by analyzing
events in the operand namespace related to the LB service, and if an LB creation
failure event is detected, propagate the message into IngressController status
and provide a more specific reason.
Replace the use of indexers with simpler inline cache lookups now that the
manager cache is available.
TODO
> Surface service-controller LB provisioning failures through status

- pkg/operator/controller/certificate-publisher/controller.go
- pkg/operator/controller/certificate/controller.go
- pkg/operator/controller/controller.go
Use a controller name which is always a valid metric name, allowing the
controller-runtime to successfully register all metrics which incorporate
the controller's name.
> metrics: fix metric registration bug

- pkg/operator/controller/controller.go
This PR refactors the main reconciliation loop to check for the presence of `ingress.DeletionTimestamp`. It makes the reconciliation loop easier to understand and more efficient by not making unnecessary api calls (i.e. `configv1.DNS`) for an `IngressController` deletion.
> Refactors main reconcile loop

- pkg/dns/aws/dns.go
- pkg/operator/controller/load_balancer_service.go
- test/e2e/operator_test.go
Use the correct annotation for AWS internal load balancers. Before this
change, the Internal endpoint publishing strategy scope was not correctly
honored on AWS.
> controller: fix AWS internal loadbalancer annotation

- cmd/ingress-operator/main.go
- pkg/operator/controller/certificate/controller.go
- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- pkg/operator/controller/ingress/dns.go
- pkg/operator/controller/ingress/dns_test.go
- pkg/operator/controller/ingress/internal_service.go
- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/monitoring.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
- pkg/operator/controller/names.go
- pkg/operator/controller/status/controller.go
- pkg/operator/controller/status/controller_test.go
- pkg/operator/operator.go
- test/e2e/operator_test.go
Move the ingress controller into its own package, and extract a separate status controller to create and update the `ClusterOperator` resource.
Fix a nil pointer dereference in case the namespace does not exist at the time that the `ClusterOperator` resource's `status` is computed.
Update references to the "operator controller", which is now more properly called the "ingress controller".
* `cmd/ingress-operator/main.go` (`main`): Update references to `UnknownVersionValue`, which is now in the `status` controller package.
* `pkg/operator/controller/certificate/controller.go` (`Reconcile`): Update reference to `IsStatusDomainSet`, which is now in the `ingress` controller package.
* `pkg/operator/controller/controller.go`: Rename...
* `pkg/operator/controller/ingress/controller.go`: ...to …
> Split ingress and status controllers

- manifests/02-deployment.yaml
* `manifests/02-deployment.yaml`: Delete the metrics port since we are not exposing it at this time.
> Delete metrics port from operator pod spec

- Makefile
- hack/run-local.sh
- pkg/api/v1/types.go
- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
- test/e2e/certificate_publisher_test.go
- test/e2e/operator_test.go
Add an ingresscontroller `Admitted` status condition which indicates that the
ingresscontroller has been defaulted, validated, and marked safe to process.
A rejected ingresscontroller will have a reason indicating why admission failed.
Refactor the controller loop in terms of distinct defaulting, validation, and
admission steps to both implement the admission concept and reduce branching
complexity.
Add an e2e test for admission, and refactor the other tests to reduce boilerplate.
> Introduce concept of ingresscontroller admission status

- manifests/03-cluster-operator.yaml
Add version info to manifest so the CVO can identify the operator's
version keys in the clusteroperator status.
> Bug 1726453: manifests: add version information

- manifests/00-cluster-role.yaml
- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/poddisruptionbudget.go
- pkg/operator/controller/names.go
- test/e2e/operator_test.go
For each ingress controller, create a pod disruption budget with a maximum of 25% unavailable pods.
* `manifests/00-cluster-role.yaml`: Allow the operator to manage `PodDisruptionBudget` resources.
* `pkg/operator/controller/ingress/controller.go` (`ensureIngressController`): Call `ensureRouterPodDisruptionBudget`.
* `pkg/operator/controller/ingress/poddisruptionbudget.go`: New file.
(`ensureRouterPodDisruptionBudget`): New method.  Ensure the appropriate pod disruption budget exists for the given ingress controller.  Get the current one using `currentRouterPodDisruptionBudget`.  If none exists, create one using the `desiredRouterPodDisruptionBudget` function and `createRouterPodDisruptionBudget` method.  If one already exists, update it if necessary using …
> Add a pod disruption budget for ingress controllers

- cmd/ingress-operator/main.go
* `cmd/ingress-operator/main.go` (`getPlatformStatus`): Check whether the cluster infrastructure config's `status.platformStatus` field is nil.
> Bug 1734192: getPlatformStatus: Check for nil platformStatus

- pkg/dns/azure/dns.go
Azure only accpets relative records for a DNS zone and so make sure the DNS record required is correctlty trimmed of the zone name, The DNS record must first be trimmed of any trailing `.` as Azure DNS zone names
cannot have trailing dots `.`
This prevents errors like:
```
The DNS provider failed to ensure the record: failed to update dns
a record: *.apps.adahiya-1.installer-azure.devcluster.openshift.com..adahiya-1.installer-azure.devcluster.openshift.com:
dns.RecordSetsClient#CreateOrUpdate: Failure responding to request: StatusCode=400
-- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest"
Message="The resource records'' relative name ''*.apps.adahiya-1.installer-azure.devcluster.openshift.com.''
must not end with a dot."
```
This error was …
> pkg/dns/azure: fix dns record trimming to create relative records for DNS queries

- cmd/ingress-operator/main.go
Use the deprecated `status.platform` field from the cluster infrastructure config to determine the platform if the `status.platformStatus` field is nil. In particular, `platformStatus` will be nil on a cluster that is being upgraded from 4.1.
* `cmd/ingress-operator/main.go` (`getPlatformStatus`): Use the `status.platform` field from the cluster infrastructure config as the platform type if `status.platformStatus is nil.`
> Bug 1734414: getPlatformStatus: Fix platform upgrading from 4.1

- pkg/dns/azure/dns_test.go
Use an absolute domain name in unit tests since the ingress controller now defines records using absolute domain names.
Follow-up to https://github.com/openshift/cluster-ingress-operator/pull/274 and https://github.com/openshift/cluster-ingress-operator/pull/278.
* `pkg/dns/azure/dns_test.go` (`TestEnsureDNS`, `TestDeleteDNS`): Add trailing period to domain names to make them absolute.
> dns/azure: Use absolute domain name in unit tests

- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
Before this change, ingresscontroller availability was determined based on
deployment available replicas from status. Now, consider the ingresscontroller
available if the deployment has an `Available=True` condition. Available
replicas is a weak proxy for deployment availability. The condition takes into
account the complex availability rules of a deployment and also provides
additional context as to why the condition is in a certain state.
> status: compute ingresscontroller availability from deployment conditions

- pkg/operator/controller/ingress/controller.go
When processing an ingresscontroller for admission, distinguish between error values that indicate that admission processing could not be completed and error values that indicate that the processing did complete and the ingresscontroller was rejected.  Do not update the "Admitted" condition in the first case.  Log the rejection and do not retry reconciliation in the latter case.
* `pkg/operator/controller/ingress/controller.go` (`admissionRejected`): New type for admission rejections.
(`Error`): New method for the new `admissionRejected` type.
(`Reconcile`): When admission rejects the ingresscontroller, log the rejection and do not retry.
(`admit`): Only set the "Admitted" condition if validation rejected the ingresscontroller.  Return the error value from `validate` if it is not nil. …
> Fix admission to log rejections and not retry

- manifests/00-ingress-credentials-request.yaml
Use consistent naming for credentialsrequests.
> Bug 1740441: manifests: make credentialsrequest names consistent

- manifests/00-cluster-role.yaml
- pkg/operator/controller/ingress/metrics.go
- pkg/operator/controller/ingress/monitoring.go
- pkg/operator/controller/ingress/monitoring_test.go
If a servicemonitor already exists but is not the same as the desired servicemonitor, update the current servicemonitor.
https://github.com/openshift/cluster-ingress-operator/pull/242 added a selector to the servicemonitor that `desiredServiceMonitor` returns, so the operator must update any servicemonitors created by older versions of the operator.
* `manifests/00-cluster-role.yaml`: Allow updating servicemonitors.
* `pkg/operator/controller/ingress/monitoring.go` (`ensureServiceMonitor`): Add godoc.  If a servicemonitor is needed and none exists, use `createServiceMonitor` to create it.  If a servicemonitor already exists, update it if needed using `updateServiceMonitor`.  Finally, return a Boolean value indicating whether a servicemonitor exists.
(`desiredServiceMonitor`): Add godoc. …
> Bug 1740595: ensureServiceMonitor: Update resource if needed

- manifests/00-ingress-credentials-request.yaml
After cloud credential operator starts supporting resource group
scoped credential minting for Azure, all CCO will be required to set
at least one role in role bindings. If a CCO failed to do so,
no secret with azure credential will be minted.
Contributor role permissions should be sufficient. If not, please extend the list of role bindings with additional roles.
PR adding the support for resource group scoped credentials: https://github.com/openshift/cloud-credential-operator/pull/95
> Set default role for minted credentials to Contributor

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- pkg/operator/controller/ingress/rsyslog_configmap.go
- pkg/operator/controller/names.go
If an ingresscontroller is annotated with `ingress.operator.openshift.io/unsupported-access-logging=true`, or if the ingresscontroller does not have an `ingress.operator.openshift.io/unsupported-access-logging` annotation and the ingress config does have it with value "true", inject a sidecar container running rsyslog into the router pod, and configure HAProxy to send access logs to the rsyslog process in that sidecar.
**Note that use of this annotation is unsupported and intended for diagnostic purposes only!**
* `pkg/operator/controller/ingress/controller.go` (`Reconcile`): Pass `ingressConfig` to `ensureIngressController`. (`ensureIngressController`): Add parameter for ingress config.  Pass ingress config to `ensureRouterDeployment`.  Call `ensureRsyslogConfigMap`.
* …
> Add unsupported annotation for enabling access logs

- hack/run-local.sh
- pkg/dns/azure/dns.go
- pkg/dns/azure/dns_test.go
- pkg/dns/gcp/provider.go
- pkg/operator/controller/dns/controller.go
- pkg/operator/controller/ingress/dns.go
- pkg/operator/controller/ingress/dns_test.go
Before this commit, wildcard DNS resource record TTLs were inconsistent:
* AWS alias record TTLs are not user-configurable.
* Azure records TTLs were zero (which is essentially undefined and so causes
unpredictable client behavior)
* GCP record TTLs were 120 seconds.
After this commit, all DNS records default to 30 seconds for any provider which
supports setting a TTL for the record type (Azure and GCP at this time). This
brings some consistency, and most importantly, eliminates the possibility of
zero TTLs.
> Bug 1747840: dns: add explicit TTL to all wildcard records

- manifests/00-cluster-role.yaml
- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_service_monitor.go
Backport of patches which fix prometheus integration when more than one
ingresscontroller exists.
https://github.com/openshift/cluster-ingress-operator/pull/289
https://github.com/openshift/cluster-ingress-operator/pull/242
> Bug 1740258: fix prometheus integration for multiple ingresscontrollers

- pkg/operator/controller/ingress/dns.go
Follow-up to #251.
* `pkg/operator/controller/ingress/dns.go` (`ensureWildcardDNSRecord`): Fix the name of the method in its godoc comment.
> ensureWildcardDNSRecord: Fix method name in godoc

- Makefile
- hack/run-local.sh
- Allow ingress-operator binary to be built with debug support
- Allow ingress-operator binary to be invoked via delve
If the environment variable `DELVE` is set then build the
ingress-operator binary with debug flags enabled. The default flags
passed to the compiler will disable optimisations and inlining for the
whole program.
Specifically, the GCFLAGS are:
- `-N` - disable optimizations
- `-l` - disable inlining
Running `hack/run-local.sh` will invoke the ingress-operator binary
under the auspices of the debugger (but only when the environment
variable `DELVE` is set):
```console
$ ./hack/run-local.sh
deployment.extensions/cluster-version-operator scaled
deployment.extensions/ingress-operator scaled
Image: openshift/origin-haproxy-router:v4.0
Release version: …
```
> Enable debug support when building/running ingress-operator

- pkg/dns/aws/dns.go
Do not include the DNSRecord resource in the error message that the AWS DNS provider returns in the case of a zone-lookup failure.
The DNS controller incorporates the error message from the DNS provider into the DNSRecord resource's "Failed" status condition message, which caused problems in the case of repeated zone-lookup failures.  Before this commit, such a failure would cause the controller to update the status condition message to include the DNSRecord from the previous failure, which would have a status condition message with the DNSRecord from the second previous failure, which would have a status condition message with the DNSRecord from the third previous failure, and so on.  As a result, the DNS controller was making many spurious updates with increasingly long status condition …
> dns/aws: Do not include record in error messages

- pkg/operator/controller/status/controller.go
Simplify relatedObjects computation by omitting resource names.
https://jira.coreos.com/browse/NE-219
> NE-219: status: Simplify relatedObjects

- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
Update the ingress operator's computeLoadBalancerStatus function's computation of the LoadBalancerReady condition to check for SyncLoadBalancerFailed-type events from the service controller.
https://jira.coreos.com/browse/NE-220
> Check for Kubernetes 1.15 LB provisioning failure events

- go.mod
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- pkg/operator/controller/names.go
- vendor/modules.txt
* `pkg/operator/controller/ingress/deployment_test.go` (`TestDeploymentConfigChanged`): Add test case that verifies that the ordering of tolerations is ignored.
Omit the affinity policy when using host network.  The scheduler already prevents colocation of pods that use host networking and request the same ports, so the affinity policy is superfluous in this case.
Change the affinity policy and deployment strategy when using the load-balancer or private endpoint publishing strategy as follows.  First, configure affinity for replicas of different generations of same controller.  Second, configure anti-affinity for replicas of same generation of same controller.  Finally, configure the deployment strategy to surge.
The intention of the changes for the load-balancer and private endpoint …
> Bug 1709958: Avoid dropping traffic during upgrade

- test/e2e/operator_test.go
Changes wait timeout from 10 seconds to 5 minutes for `ingresscontroller.status.ciphers` to update. 5 minutes was chosen to be consistent with `waitForIngressControllerCondition()`.
> Increases timeout for TestTLSSecurityProfile() e2e test

- pkg/operator/controller/ingress/deployment.go
When updating a router deployment, check whether the deployment strategy is changing; if it is, update the affinity policy first, and only update the deployment strategy once all pods have the new affinity policy.
This two-step migration is necessary because an old affinity policy may have an anti-affinity rule that prohibits colocation of pods belonging to the same ingresscontroller, the new deployment strategy may require surge, and the presence of pods with the old affinity policy would block a rolling update using the new deployment strategy.
Follow-up to #280.
* `pkg/operator/controller/ingress/deployment.go` (`updateRouterDeployment`): If the deployment strategy is changing, make sure to update the affinity policy first.
> Bug 1766851: Add migration for affinity and deployment strategy

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/load_balancer_service.go
Previously, a service of type `loadBalancer` would still exist after an `ingresscontroller` resource is deleted. Allowing the service to exist after an `ingresscontroller` is deleted can cause it to be reused when the same `ingresscontroller` is recreated.
> Bug 1766141: Ensures LB service finalizer is removed

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/controller_test.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
Converts `Modern` tls security profiles to `Intermediate`. Remove after haproxy is upgraded to an openssl version that supports tls v1.3.
/assign @Miciah
> Bug 1763605: Fixes tls security policy cipher handling

- pkg/operator/controller/ingress/poddisruptionbudget.go
- test/e2e/operator_test.go
Pod disruption budgets cause problems for people who want to run small clusters or drain all workers at once, and PDBs are not obviously solving any problems, so do not create PDBs, and delete any PDBs that previous versions of the operator have created.
* `pkg/operator/controller/ingress/poddisruptionbudget.go` (`desiredRouterPodDisruptionBudget`): Always return false.
> Remove pod disruption budgets

- pkg/operator/controller/ingress/deployment.go
Sets `minTLSVersion` to 1.1. Note that openshift/api defines `minTLSVersion` as TLS v1.0 for the Old profile, but this version is not supported for ingress. The oldest available TLS version for ingress is 1.1.
/assign @Miciah @ironcladlou
> Bug 1763639: Fixes minTLSVersion for Old profile

- pkg/api/v1/types.go
- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
- pkg/util/retryableerror/retryableerror.go
- pkg/util/retryableerror/retryableerror_test.go
Add a `DeploymentDegraded` status condition for ingresscontrollers.  Use the `Admitted`, `DeploymentDegraded`, `LoadBalancerReady`, and `DNSReady` status conditions to compute the status of the `Degraded` status condition.
* `pkg/api/v1/types.go` (`IngressControllerDeploymentDegradedConditionType`): New constant.
* `pkg/operator/controller/ingress/controller.go` (`Reconcile`): Requeue after the duration that `ensureIngressController` returns, if that duration is non-zero.
(`ensureIngressController`): Add a duration return value.  Return the duration value that `syncIngressControllerStatus` returns.
* `pkg/operator/controller/ingress/status.go` (`syncIngressControllerStatus`): Call `computeDeploymentDegradedCondition`.  Adjust call to `computeIngressDegradedCondition`.  Add a duration …
> Bug 1740374: status: Set Degraded using other status conditions

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/load_balancer_service.go
Previously, `ensureIngressDeleted()` was not ensuring `ingresscontroller` dependent resources no longer existed. This PR updates `ensureIngressDeleted()` to check for the existence of each `ingresscontroller` dependent resource. If a dependent resource still exists,  `ensureIngressDeleted()` will add an error to the error list. The `ingresscontroller` finalizer is only removed when no errors exist in the error list.
/assign @ironcladlou @Miciah
> Updates ensureIngressDeleted() to check for removal of deps

- pkg/operator/controller/certificate/controller.go
- pkg/operator/controller/certificate/publish_ca.go
- pkg/operator/controller/names.go
- test/e2e/operator_test.go
An explanation in code of how to fill in the router-ca.
Immediate mission: allow the default-ingress-ca to always contain a ca-bundle.crt that golang clients can use to validate the ingress wildcard certificate for the default ingresscontroller.  To do this
1. if you are not `oc get -n openshift-ingress-operator ingresscontroller/default`, do not publish
2. if the spec.DefaultCertificate.Name is set, use the `.data["tls.crt "]` value in that secret to the `router-ca.data["ca-bundle.crt"]`
3. if it is not set, use the `ensureRouterCASecret` secret's `.data.["tls.crt"]`
If we can agree to this approach to solve the immediate 4.1, 4.2, and 4.3 problem, then we can update the enhancement.
Future mission: it may be useful to have a ca bundle that can terminate any ingress wildcard.  This seems …
> publish a router-ca that can be used to verify routes in golang clients

- pkg/operator/controller/ingress/controller.go
- pkg/util/retryableerror/retryableerror_test.go
An error value from `syncIngressControllerStatus` may represent a failure to update status, in which case `syncIngressControllerStatus` itself adds a clear error message and wrapping it is therefore unnecessary; or the error value may represent a retryable error, in which case wrapping the error value loses the retryable error type and adds an inaccurate error message.
* `pkg/operator/controller/ingress/controller.go` (`ensureIngressController`): Do not wrap the error value from `syncIngressControllerStatus` when adding it to the list of returned error values.
* `pkg/util/retryableerror/retryableerror_test.go` (`TestRetryableError`): Add a test case with a nil error value, and add a nil error value to the "only retryable errors" test case to verify that nil error values are ignored.
> Bug 1781948: Do not wrap errors from syncIngressControllerStatus

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/operator_test.go
When computing the hash for a deployment for use in the pod template spec's labels and affinity policy, ignore `spec.replicas` and other fields to which updates should not trigger a rolling update of the deployment.
* `pkg/operator/controller/ingress/deployment.go` (`desiredRouterDeployment`): Use the new `deploymentTemplateHash` function instead of `deploymentHash`.
(`hashableDeployment`): Add a parameter to indicate whether to hash fields in the deployment spec besides the pod template spec.
(`deploymentHash`): Update call to `hashableDeployment`.
(`TestDesiredRouterDeployment`): Use `deploymentTemplateHash`.
(`otherToleration`): Factor out of `TestDeploymentConfigChanged`.
(`deploymentTemplateHash`): New function.  Use `hashableDeployment`.  Return a hash based on the deployment's …
> Bug 1783007: Ignore spec.replicas in deployment hash

- cmd/ingress-operator/start.go
- hack/run-local.sh
Add an option to configure the trusted CA bundle location, as the hard-coded
default location is hostile to local development environments.
Update the local run script to allow passing through options to the start
command to make it easier to use the new option.
> cmd/start: add option to configure shutdown trigger file

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
fix Bug https://bugzilla.redhat.com/show_bug.cgi?id=1789687.
The router template uses "v6" to match the env. 
```
{{- else if eq "v6" $router_ip_v4_v6_mode }}
bind :::{{env "ROUTER_SERVICE_HTTP_PORT" "80"}} v6only
```
see: https://github.com/openshift/router/blob/8af16cfb1e7bb1a0acf89f96c4e18529d591ec4d/images/router/haproxy/conf/haproxy-config.template#L152
> Bug 1789687: the env ROUTER_IP_V4_V6_MODE should uses v6 instead v6_only

- cmd/ingress-operator/start.go
If no DNS configuration is provided, don't try to set up provider clients.
This prevents an operator crash if DNS configuration is not provided on
platforms where managed DNS is expected to be supported (e.g. AWS).
In a followup, the provider configuration can be refactored into the provider
implementations themselves, so this part of the code won't need to know anything
about the provider setup beyond picking the right implementation. Then, it would
be safe to always use the appropriate provider for the platform and let the
provider surface configuration errors if DNS records are actually created to
exercise the provider.
> Bug 1793541: Only initialize DNS providers if DNS config is present

- pkg/operator/controller/ingress/deployment.go
Configure the same deployment strategy and affinity policy on the deployment for an `IngressController` that uses the "NodePortService" endpoint publishing strategy type as we do for an `IngressController` that uses the "LoadBalancerService" or "Private" strategy type.
Follow-up to #343.
* `pkg/operator/controller/ingress/deployment.go` (`desiredRouterDeployment`): Configure deployment strategy and affinity policy the same for "NodePortService" as for "LoadBalancerService" and "Private".
> Bug 1801410: Set affinity for "NodePortService"

- pkg/operator/controller/ingress/load_balancer_service.go
GCP and Azure both hardcode LB timeouts - set AWS to match the lower bound of Azure (2 failures @ 5s interval, 2 healthy). By default AWS is 6 failures @ 10s which is a very long timeout for the router.
In the future, if these attributes become customizable on GCP and Azure, they should be consistent with our AWS settings.
If we see flakiness at this lower check interval, we may want to consider bumping to 3 successive failures. However, it's generally best to start at the low end and then tune up to be as responsive
as possible to rollouts.
> Tune AWS load balancers to be consistent with other platforms

- pkg/operator/controller/ingress/deployment.go
In order to allow routers to be tuned to shutdown when a variable
length of connections have completed, the grace period needs to be
set fairly high. For now, set it to 1 hour until we determine what
tunable limits we should allow. In general few transactions will
take 1 hour to complete.
> Router should deploy with a very long grace period

- cmd/ingress-operator/start.go
- pkg/dns/aws/dns.go
- pkg/dns/azure/dns.go
Remove references to the cluster DNS configuration object from the configuration objects for the AWS and Azure DNS providers.
#121 added a reference to the cluster DNS configuration in the AWS provider configuration, and #231 added a similar reference in the Azure provider configuration, but neither provider ever used the reference.
* `cmd/ingress-operator/start.go`: Do not set the `DNS` field in the config argument to `NewProvider`.
* `pkg/dns/aws/dns.go` (`Config`):
* `pkg/dns/azure/dns.go` (`Config`): Delete the `DNS` field.
----
This is just a clean-up; no functional change.
> Delete cluster DNS config from DNS provider config

- pkg/operator/controller/ingress/load_balancer_service.go
Delete the declaration of the unused constant for the `service.kubernetes.io/ibm-load-balancer-cloud-provider-zone` annotation.
* `pkg/operator/controller/ingress/load_balancer_service.go` (`iksLBProxyRegionAnnotations`): Delete.
Rename the `iksLBProxyProtocolAnnotations` constant, which has nothing to do with PROXY protocol, but rather specifies the scope of the load balancer (public or private).
* `pkg/operator/controller/ingress/load_balancer_service.go` (`iksLBProxyProtocolAnnotations`): Rename...
(`iksLBScopeAnnotation`): ...to this.
> Delete iksLBProxyRegionAnnotations, rename iksLBProxyProtocolAnnotations

- pkg/operator/controller/ingress/deployment.go
Remove 4.3 → 4.4 migration logic.
This reverts #321.
> Revert "Add migration for affinity and deployment strategy"

- .github/ISSUE_TEMPLATE/config.yml
- README.md
Delete the version, which was "4.0.0", which does not exist; it is better not to specify a default version anyway as we cannot know the version against which the user is reporting an issue.
* `README.md`: Fix Bugzilla link.
* `.github/ISSUE_TEMPLATE/config.yml`: New file.  Add links to Bugzilla and documentation.
> Fix Bugzilla link and add GitHub issue template configuration

- Makefile
- hack/verify-deps.sh
Add a `verify` target and decouple from `test` because verification is only required as a
presubmit check once https://github.com/openshift/release/pull/8016 merges.
> Add a dependency verification script

- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
Reword the `LoadBalancerManaged` status condition's reason and message to avoid using phrases such as "unsupported" or "does not support" when the endpoint publishing strategy does not include managing a load balancer.
* `pkg/operator/controller/ingress/status.go` (`computeLoadBalancerStatus`): Change reason and message strings for the `LoadBalanacerManaged` status condition.
> Bug 1826113: status: Improve LoadBalancerManaged=false wording

- test/e2e/operator_test.go
Fix test code to output the error value if a client `Get` call fails.
* `test/e2e/operator_test.go` (`TestRouteAdmissionPolicy`): Log errors from `Get`.
Poll the ingress controller's deployment after changing the route admission policy to make sure that the deployment is updated and rolled out before checking that the new policy is in effect.
* `test/e2e/operator_test.go` (`TestRouteAdmissionPolicy`): Add polling to make sure that the ingress controller deployment is updated and rolled out.
---
@danehans
> Bug 1835025: TestRouteAdmissionPolicy: Wait for rolling update

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
* `pkg/operator/controller/ingress/deployment.go` (`updateRouterDeployment`): Add the diff of the previous and updated deployments to the "updated router deployment" log message.
When comparing deployments to determine whether an update is required, treat implicit and explicit default values as equal.
Before this commit, the update logic would keep trying to revert the default values that the API set for probe parameters.
* `pkg/operator/controller/ingress/deployment.go` (`hashableDeployment`): Use the new `hashableProbe` function so that two deployments have the same hash if the only difference between them is that one does not specify liveness or readiness probe parameters and the other specifies the default parameter values.
(`hashableProbe`): New function.  Return a copy of the given …
> Bug 1834989: hashableDeployment: Fix liveness/readiness probes

- pkg/operator/controller/ingress/deployment.go
- test/e2e/http2_disable_test.go
Changes to let the ingress controller override the ingress config if
the annotation is present and disabled (i.e., "false").
This is a follow-up to https://github.com/openshift/cluster-ingress-operator/pull/401.
> Bug 1837251: e2e: Rework http/2 e2e test for ingresscontroller precedence

- pkg/operator/controller/status/controller.go
We've used a message without a reason for `Progressing=False` since 7b6339ed6b (#229) and for Availabe=True since 28d343900d (#201).  But if we feel like we have a message we want to set to help humans understand the condition, we should be setting a reason string for machines too.  `AsExpected` follows [the library-go precedent][1].
[1]: https://github.com/openshift/library-go/blob/94c59dec54be25c8527e51e8c0a885712aeb01b5/pkg/operator/status/condition.go#L67
> pkg/operator/controller/status: AsExpected reason for Available and Progressing

- Makefile
This PR causes a `build` before locally running the operator. I did not include `build` in the `test-e2e` target because the operator may be deployed in the cluster via `release-local`.
> Makefile: Adds build target as a dep of run-local

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/dns.go
- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/monitoring.go
- pkg/operator/controller/ingress/nodeport_service.go
- pkg/operator/controller/ingress/poddisruptionbudget.go
- pkg/operator/controller/ingress/rsyslog_configmap.go
- pkg/operator/controller/ingress/serviceca_configmap.go
Switches all ensure<thing> functions in pkg/operator/controller/ingress
to use a have<thing> boolean rather than manually checking if
<thing> != nil for consistency. 
Also makes sure that failed update branches in each `ensure<thing>` function return the current object, if available, as mentioned in https://github.com/openshift/cluster-dns-operator/pull/176.
> controller: Make ensure conditions consistent

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/monitoring.go
- pkg/operator/controller/ingress/nodeport_service.go
- pkg/operator/controller/ingress/poddisruptionbudget.go
- pkg/operator/controller/ingress/rsyslog_configmap.go
- pkg/operator/controller/ingress/serviceca_configmap.go
Removes extra API get calls in pkg/operator/controller/ingress
when an Ingress resource already exists and no update is performed.
> controller/ingress: Remove excess API calls for ingress

- pkg/operator/controller/ingress/dns.go
- pkg/operator/controller/ingress/dns_test.go
- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
Add a `wantFoo` boolean to `ensureWildcardDNSRecord` &
`ensureLoadBalancerService` for consistency. Fixes a bug
accidentally introduced in #408.
Also fixes a small comment typo for `desiredWildcardDNSRecord`, as well as updates the necessary unit tests.
> Fix ensureWildcardDNSRecord & ensureLoadBalancerService

- pkg/dns/aws/dns.go
- pkg/dns/azure/dns.go
- pkg/operator/controller/dns/controller.go
Improve the logging in the DNS controller and DNS provider implementations to improve visibility into the controller's operation and to avoid printing old and possibly misleading status during reconciliation.
* `pkg/dns/aws/dns.go` (`change`):
* `pkg/dns/azure/dns.go` (`Ensure`, `Delete`): Log the dnsrecord's spec but not its status because the controller only updates the status after ensuring or deleting the dnsrecord.  Log the zone along with the dnsrecord's spec.
* `pkg/operator/controller/dns/controller.go` (`Reconcile`): Log when beginning reconciliation.  When updating the status, log the updated dnsrecord rather than the old dnsrecord (with the old status), and always log when updating (not only when the update fails).
(`publishRecordToZones`): Log when skipping a zone.  Log the …
> dns: Improve logging of reconciliation and updates

- test/e2e/operator_test.go
Follow-up to #396.
* `test/e2e/operator_test.go` (`TestRouteAdmissionPolicy`): Use `waitForDeploymentComplete` instead of `waitForIngressControllerCondition`.
(`waitForDeploymentComplete`): New function.  Wait for the given deployment to complete its rollout.
> Bug 1835025: TestRouteAdmissionPolicy: Fix wait for deployment

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/http2_disable_test.go
Annotation has been renamed to:
ingress.operator.openshift.io/default-enable-http2
and by default is "false".
> Bug 1853711: Invert http/2 kill switch logic

- pkg/operator/controller/ingress/nodeport_service.go
- pkg/operator/controller/ingress/nodeport_service_test.go
When comparing services to determine whether an update is required, treat implicit and explicit default values as equal.
Before this commit, the update logic would keep trying to revert the default value that the API set for the service's session affinity.
* `pkg/operator/controller/ingress/nodeport_service.go` (`nodePortServiceChanged`): Use the new `cmpServiceAffinity` function so that two services are considered equal if the only difference between them is that one does not specify the session affinity and the other service has the default value.
(`cmpServiceAffinity`): New function.
* `pkg/operator/controller/ingress/nodeport_service_test.go` (`TestNodePortServiceChanged`): Verify that `nodePortServiceChanged` returns false if the only mutation is that the session affinity has been …
> Bug 1842742: nodePortServiceChanged: Fix for session affinity

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
Delete the `DeploymentDegraded` status condition, add `DeploymentAvailable`, `DeploymentReplicasMinAvailable`, and `DeploymentReplicasAllAvailable` status conditions, and use the new conditions to compute the ingresscontroller's `Degraded` status condition.
The old `DeploymentDegraded` status condition was based on the deployment's `Available` status condition, but the deployment may report `Available=True` before the deployment's minimum availability is met, so relying on the deployment's `Available` condition alone is insufficient to determine if the ingresscontroller's deployment is degraded.
* `pkg/operator/controller/ingress/controller.go` (`IngressControllerDeploymentDegradedConditionType`): Delete the `DeploymentDegraded` condition type. …
> Bug 1830271: status: Replace "DeploymentDegraded" condition

- go.mod
- go.sum
- pkg/dns/azure/client/auth.go
- pkg/dns/azure/client/client.go
- pkg/dns/azure/dns.go
- pkg/operator/controller/dns/controller.go
- vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
- vendor/github.com/openshift/api/config/v1/types_feature.go
- vendor/github.com/openshift/api/config/v1/types_infrastructure.go
- vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
- vendor/github.com/openshift/api/operator/v1/0000_20_etcd-operator_01.crd.yaml
- vendor/modules.txt
Use the Azure cloud environment specified by the `status.platformStatus.azure.cloudName` field of the infrastructure.config.openshift.io resource.
See openshift/enhancements#321
> support other Azure cloud environments

- pkg/dns/aws/dns.go
- pkg/operator/controller/dns/controller.go
- pkg/util/network.go
- pkg/util/network_test.go
- test/e2e/operator_test.go
Adds support for using custom endpoints with AWS DNS provider clients.
Supports [NE-350](https://issues.redhat.com/browse/NE-350)
/assign @Miciah 
> Adds Support for AWS Custom Endpoints

- test/e2e/operator_test.go
Don't set the endpoint for the AWS ELB API in `TestIngressControllerCustomEndpoints`.  Unlike the Route 53 and tagging APIs, the ELB API needs a region-specific endpoint, and trying to use the us-west-2 endpoint when running in the us-east-1 region fails.
* `test/e2e/operator_test.go` (`TestIngressControllerCustomEndpoints`): Don't set a custom endpoint for the AWS ELB API.
----
@danehans
> Omit ELB EP in TestIngressControllerCustomEndpoints

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/operator_test.go
This change is related to [NE-320](https://issues.redhat.com/browse/NE-320).
* `pkg/operator/controller/ingress/deployment.go` (`RouterCaptureHTTPRequestHeaders`, `RouterCaptureHTTPResponseHeaders`): New constants with the names of the related environment variables.
(`desiredRouterDeployment`): Set the `ROUTER_CAPTURE_HTTP_REQUEST_HEADERS` and `ROUTER_CAPTURE_HTTP_RESPONSE_HEADERS` environment variables as appropriate.
(`accessLoggingForIngressController`): Set `HTTPCaptureHeaders`.
(`serializeCaptureHeaders`): New function.  Serialize HTTP header capture configuration into values suitable for the environment variables.
* `pkg/operator/controller/ingress/deployment_test.go` (`TestDesiredRouterDeployment`): Verify that `spec.logging.access.httpCaptureHeaders` has the expected effect.
* …
> Implement HTTP header/cookie capture APIs

- Makefile
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/forwarded_header_policy_test.go
- test/e2e/operator_test.go
This commit resolves [NE-318](https://issues.redhat.com/browse/NE-318).
* `pkg/operator/controller/ingress/deployment.go` (`RouterForwardedHeadersPolicy`): New constant with the name of the related environment variable.
(`desiredRouterDeployment`): Set the `ROUTER_SET_FORWARDED_HEADERS` environment variable as appropriate.
* `pkg/operator/controller/ingress/deployment_test.go` (`TestDesiredRouterDeployment`): Verify that `spec.httpHeaders.forwardedHeaderPolicy` has the expected effect.
* `test/e2e/forwarded_header_policy_test.go`: New file.
(`buildEchoPod`, `buildEchoService`, `buildRoute`, `testRouteHeaders`): New helper functions.
(`testPodCount`): New helper variable for `testRouteHeaders`.
(`TestForwardedHeaderPolicyAppend`, `TestForwardedHeaderPolicyReplace`, …
> Implement HTTP Forwarded header policy API

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
* `pkg/operator/controller/ingress/deployment.go` (`RouterUniqueHeaderName`, `RouterUniqueHeaderFormat`): New constants for the related environment variables.
(`desiredRouterDeployment`): Set the `ROUTER_UNIQUE_ID_HEADER_NAME` and `ROUTER_UNIQUE_ID_FORMAT` environment variables as appropriate.
* `pkg/operator/controller/ingress/deployment_test.go` (`TestDesiredRouterDeployment`): Verify that `spec.httpHeaders.uniqueId` has the expected effect.
* `test/e2e/operator_test.go` (`TestUniqueIdHeader`): New test.
> Implement HTTP Unique-Id header API

- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- `pkg/operator/controller/ingress/load_balancer_service.go`: Checks for the absence of AWS provider parameters.
- `pkg/operator/controller/ingress/load_balancer_service_test.go`: removes load balancer scope from "external classic load balancer without scope" test case.
> Follow-Up fixes for PR 427

- pkg/operator/controller/ingress/cluster-role.go
- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/namespace.go
On upgrades we have never needed to handle changes to the
openshift-ingress-router cluster role. This broke 4.5->4.6 upgrades
because the router switched to watching endpointslices in 4.6 and, as
this permission was not granted to the role, it failed to start.
This change now ensures that the cluster role gets updated/reconciled
with the (bindata) values from assets/router/cluster-role.yaml. In
this particular upgrade case it will now add the endpointslices RBAC
rules allowing the router to start.
> Bug 1862892: Reconcile openshift-ingress-router clusterrole on upgrades

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/forwarded_header_policy_test.go
- test/e2e/operator_test.go
- test/e2e/util.go
* `pkg/operator/controller/ingress/deployment.go` (`desiredRouterDeployment`): Escape the unique-id header format string.
* `test/e2e/operator_test.go` (`TestUniqueIdHeader`): New test.
> Bug 1866575: Escape unique-id format

- pkg/dns/aws/dns.go
- pkg/operator/controller/dns/controller.go
- test/e2e/operator_test.go
- Uses status instead of spec of `infrastructure` now that https://bugzilla.redhat.com/show_bug.cgi?id=1850681 is fixed.
- Removes the unnecessary poll from `defer()` after custom endpoints are removed from `infrastructure`.
- Adds the elb custom endpoint that was removed by https://github.com/openshift/cluster-ingress-operator/commit/21d57e5ab2a44787f57d7e4fa7261ce8332f14c9, this time using the region from platform status.
/assign @knobunc @Miciah 
/cc @sgreene570 @frobware
> Fixes Bug 1866299: Adds region verification for custom endpoints

- pkg/dns/aws/dns.go
- pkg/dns/aws/dns_test.go
A follow-on to https://github.com/openshift/cluster-ingress-operator/pull/433. Based upon [these docs](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-endpoints.html), GovCloud does provide a specific Route 53 endpoint. This PR updates `NewProvider()` to set the GovCloud Route 53 and Tagging endpoints and validates custom endpoint url's.
> Bug 1866299: Adds support for GovCloud endpoints

- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- `pkg/operator/controller/ingress/load_balancer_service.go`: Updates `desiredLoadBalancerService()` to only set the IBM private annotation for when the endpoint publishing strategy is nil or "Internal".
- `pkg/operator/controller/ingress/load_balancer_service_test.go`: Updates `TestDesiredLoadBalancerService()` to test service annotations for different supported providers.
/assign @knobunc @Miciah 
> Bug 1872058: Fixes IBM Cloud LB Annotations

- pkg/operator/controller/dns/controller.go
- pkg/operator/controller/dns/controller_test.go
In `publishRecordToZones`, when merging the updated status with the input status in order to produce the output status, first make a copy of the input status, and use the copy to avoid mutating the input status.
Before this change, `publishRecordToZones` mutated the input status, and so when the caller compared the input status with the output status, it would always find them to be identical.  As a result, the caller never updated the DNSRecord's status in the API, which caused the DNS controller to endlessly retry the update and the ingress controller to report `DNSReady=False`.
* `pkg/operator/controller/dns/controller.go` (`publishRecordToZones`): Make a copy of the zone statuses, and pass the copy to `mergeStatuses` to avoid mutating the original zone statuses that the caller passed …
> Bug 1873728: publishRecordToZones: Fix status merge

- pkg/dns/aws/dns.go
- Switches the preference of the AWS config to prefer infra config over local AWS env vars.
- Fixes the GovCloud handling of the Route53 client for standard and custom endpoints.
/assign @Miciah @knobunc 
> Bug 1866299: Fixes Route53 Client Handling of GovCloud Partition

- test/e2e/certificate_publisher_test.go
- test/e2e/forwarded_header_policy_test.go
- test/e2e/http2_disable_test.go
- test/e2e/operator_test.go
Make sure errs in the `wait.PollImmediate()` operator e2e test loops
are reported to prevent unnecessary retries and provide more precise
failure messages.
> Bug 1828618: Improve e2e test polling loops

- pkg/dns/aws/dns.go
- pkg/dns/aws/dns_test.go
As with other AWS partitions, the GovCloud Tagging client must be in the same region as the Route53 client to find the hosted zone of managed records. The AWS GovCloud [docs](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-endpoints.html) do not specify Group Tagging details, so this dependency was not included until tests confirmed the requirement.
/assign @Miciah @knobunc 
> Bug 1866299: Fixes AWS Tagging Client for GovCloud East Region

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/dns.go
- pkg/operator/controller/ingress/dns_test.go
- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- pkg/operator/controller/ingress/monitoring.go
- pkg/operator/controller/ingress/nodeport_service.go
- pkg/operator/controller/ingress/poddisruptionbudget.go
- pkg/operator/controller/ingress/rsyslog_configmap.go
- pkg/operator/controller/ingress/serviceca_configmap.go
This PR backports https://github.com/openshift/cluster-ingress-operator/pull/419 to `release-4.5`. The backport had to be done manually due to merge conflicts. PR https://github.com/openshift/cluster-ingress-operator/pull/408 was added to this backport to resolve the merge conflicts. https://github.com/openshift/cluster-ingress-operator/pull/408 introduced a regression, so https://github.com/openshift/cluster-ingress-operator/pull/412 has been added to this backport as well. All commits were applied as is without hitting any merge conflicts, so reviewing this should be straightforward.
This backport is needed to resolve https://bugzilla.redhat.com/show_bug.cgi?id=1876919.
/assign @danehans @Miciah 
/cc @frobware
> [release-4.5] Bug 1878148: Backport: Delete Router Deployment Only Upon DNSRecord Deletion

- pkg/dns/aws/dns.go
Route53 for GovCloud is based out of us-gov-west-1, so the tagging client must match this region even with custom endpoints configured. This PR updates the tagging client endpoint configuration to meet this requirement and removes unused constants.
/assign @Miciah @knobunc 
> Bug 1866299: Forces Tagging Client to us-gov-west-1 Region

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
- pkg/operator/controller/status/controller.go
- pkg/util/sort.go
* `pkg/operator/controller/status/controller.go` (`computeOperatorDegradedCondition`): For each ingresscontroller that is reporting `Degraded=True`, report the status condition's reason and message.
* `pkg/operator/controller/ingress/controller.go` (`IngressControllerPodsScheduledConditionType`): New constant.
(`ensureIngressController`): Get a list pods in the `openshift-ingress` namespace and pass the list to `syncIngressControllerStatus`.
* `pkg/operator/controller/ingress/status.go` (`syncIngressControllerStatus`): Add `pods` parameter.  Call `computeDeploymentPodsScheduledCondition`, passing in the deployment and pods.
(`computeDeploymentPodsScheduledCondition`): New function.  Use the deployment and pods to identify unscheduled pods, and compute and return the `PodsScheduled` status …
> Bug 1881155: Improve status reporting when pods cannot be scheduled

- test/e2e/forwarded_header_policy_test.go
* `test/e2e/forwarded_header_policy_test.go` (`testRouteHeaders`): If the polling loop fails, output the client pod's spec and logs as part of the failure message.
Ignore case when comparing the expected response and the actual response in the Forwarded header policy E2E tests. https://github.com/openshift/router/pull/194 turns off HAProxy's HTX option when HTTP/2 is not enabled.  As a result, HAProxy does not down-case HTTP header names.
* `test/e2e/forwarded_header_policy_test.go` (`testRouteHeaders`): Ignore case when comparing the expected response and the actual response.
> TestForwardedHeaderPolicy*: Make case-insensitive

- Dockerfile
Updating ose-cluster-ingress-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-cluster-ingress-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating ose-cluster-ingress-operator builder & base images to be consistent with ART

- HACKING.md
Adds brief directions for the `make run-local` (`hack/run-local.sh`) command to the `HACKING.md` document.
> Add run-local steps to hacking doc

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- test/e2e/operator_test.go
Add support for changing ingresscontroller load balancer scope.  On AWS and IBM cloud, this requires deleting the existing load balancer service and recreating it with the desired scope.   On Azure and GCP, it suffices to update the existing service's annotations.
This change also adds logic to remove the service finalizer, which is no longer needed to clean up DNS records since the DNSRecord CRD was added.
* `pkg/operator/controller/ingress/controller.go` (`setDefaultPublishingStrategy`): Update scope if needed.
* `pkg/operator/controller/ingress/load_balancer_service.go` (`externalLBAnnotations`): New variable.  Map platform type to the annotation for that platform that makes the load balancer external, if the platform requires an explicit annotation.
(`ensureLoadBalancerService`): Add …
> Bug 1891625: Support changing ingresscontroller load balancer scope

- cmd/ingress-operator/start.go
Configure the operator's metrics handler to listen on 127.0.0.1 only.
Before this change, metrics were exposed on port 60000, without authentication.  Although the pod spec does not advertise port 60000, the port was still accessible outside the pod.  After this change, port 60000 is inaccessible outside the pod, so the only way to get metrics is by connecting to port 9393 and authenticating with kube-rbac-proxy.
* `cmd/ingress-operator/start.go` (`NewStartCommand`): Configure metrics to listen on 127.0.0.1:60000.
> Bug 1896923: Configure operator metrics handler to use localhost

- pkg/operator/controller/dns/controller.go
Add a predicate to the DNS controller's watch on `DNSRecords` so that only updates a `DNSRecord's` spec triggers reconciliation (and updates to its status do not).
Before this change, one reconciliation could update the `DNSRecord's` status and trigger a second reconciliation.  In the case of a successful update, the second reconciliation would have no work to do, so it would complete without triggering a third reconciliation.  In the case of a failed update, the second reconciliation would retry the update.  If retrying the update then failed, the second reconciliation could update the `DNSRecord's` status to record the new failure, triggering a third reconciliation, which could similarly trigger a fourth reconciliation, and so on ad infinitum.
* …
> dns: Don't hotloop on updates to DNSRecord status

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
Bug 1880902 - If the endpoint publishing strategy type is set to hostnetwork then
we should automatically set the dnsPolicy with ClusterFirstWithHostNet.
> Bug 1880902: automatically set the dnsPolicy with ClusterFirstWithHostNet when endpoint publishing strategy type is set to hostnetwork

- hack/verify-generated-crd.sh
Add an exit code to the `hack/verify-generated-crd.sh`
script so discovered diffs return an exit code of 1,
rather than 0 (which fakes out the verify CI job).
> hack: verify-generated-crd.sh should fail on diffs

- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
BZ-1870373: Ingress Operator reports available when DNS fails to provision
- Check DNSReady and LoadBalancerReady when determining Availability in computeIngressAvailableCondition
- Call computeIngressAvailableCondition after computing other conditions in syncIngressControllerStatus
- Change unit tests for computeIngressAvailableCondition
- Refactor the checks for conditions into checkConditions, to share between computeIngressAvailable and computeIngressDegraded
> Bug 1870373: Ingress Operator reports available when DNS fails to provision

- pkg/operator/controller/ingress/load_balancer_service.go
If an ingresscontroller's `status.endpointPublishingStrategy.type` field is `LoadBalancerService` but `status.endpointPublishingStrategy.loadBalancer` is `nil`, assume the ingresscontroller should have an external load balancer.
#254 added support for internal scope for load balancers.  In doing so, it changed the operator logic to initialize `status.endpointPublishingStrategy.loadBalancer` to indicate the scope when an ingresscontroller was created, using the corresponding fields in the ingresscontroller's `spec` to determine the scope.  The same change also changed operator logic to assume that the ingresscontroller has internal scope if `status.endpointPublishingStrategy.loadBalancer` is `nil`. However, if an ingresscontroller already exists, the operator does not update …
> Bug 1904582: Assume ingresscontroller is external absent status

- cmd/ingress-operator/start.go
- pkg/manifests/manifests.go
- pkg/operator/controller/canary/controller.go
- pkg/operator/controller/canary/daemonset.go
- pkg/operator/controller/canary/route_test.go
- pkg/operator/controller/certificate/controller.go
- pkg/operator/controller/dns/controller.go
- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/monitoring.go
- pkg/operator/controller/names.go
- pkg/operator/controller/status/controller.go
- pkg/operator/controller/status/controller_test.go
- pkg/operator/operator.go
- test/e2e/canary_test.go
- test/e2e/operator_test.go
This PR addresses several fixups from [NE-199 Phase 1](https://github.com/openshift/cluster-ingress-operator/pull/476) and [Phase 2](https://github.com/openshift/cluster-ingress-operator/pull/493). The most notable being the redundant e2e test code in `test/e2e/canary_test.go` (see the [BZ 1903165](https://bugzilla.redhat.com/show_bug.cgi?id=1903165)).
---
Previous PR comments that this PR addresses (in addition to the canary status e2e test cleanup):
https://github.com/openshift/cluster-ingress-operator/pull/493#issuecomment-737430978
https://github.com/openshift/cluster-ingress-operator/pull/476/files#r513779823
https://github.com/openshift/cluster-ingress-operator/pull/476/files#r513784808.
See individual commit messages for more details.
> Bug 1903165: NE-199 Follow Up Fixes.

- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
Add support for updating the ingresscontroller load balancer health check interval on AWS.
* `pkg/operator/controller/ingress/load_balancer_service.go`(`ensureLoadBalancerService`): Add update logic.  Use the new `createLoadBalancerService` and `updateLoadBalancerService` methods to create or update the service as needed.
(`createLoadBalancerService`): New method.
(`updateLoadBalancerService`): New method.  Update the LoadBalancer service,using the new `loadBalancerServiceChanged` function.
(`loadBalancerServiceChanged`): New function.  Check if the `service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval` annotation changed.
* `pkg/operator/controller/ingress/load_balancer_service_test.go` (`TestLoadBalancerServiceChanged`): New test.
This change resolves …
> Bug 1908758: Update AWS LB health check interval annotation

- test/e2e/http_header_name_case_adjustment_test.go
test/e2e/http_header_name_case_adjustment_test.go:
Fix TestHeaderNameCaseAdjust to properly output the error
from the polling loop (when applicable) by not overwriting
the commonly used `err` variable.
---
This is a trivial fix for the TestHeaderNameCaseAdjust test function added in https://github.com/openshift/cluster-ingress-operator/pull/496.
> Bug 1906508: test/e2e: Don't clobber err in TestHeaderNameCaseAdjust

- pkg/operator/controller/ingress/load_balancer_service.go
related to unmerged PR: https://github.com/openshift/cluster-ingress-operator/pull/372
changes relate to: 
- Set traffic policy to cluster for IBM platform, per implementation details for IBM's LB. 
- persist traffic policy on loadBalancerServiceChanged, to ensure if user defines the policy it is honored.
> Bug 1912916: Set traffic policy to cluster for IBM platform

- pkg/operator/controller/certificate/default_cert.go
- pkg/operator/controller/certificate/default_cert_test.go
**pkg/operator/controller/certificate/default_certificate.go:**
If an ingress controller has the Spec.DefaultCertificate field set to the name of the operator generated default certificate, use/create the operator generated default certificate rather than delete it.
This commit resolves BZ#1912922 by enhancing `desiredRouterDefaultCertificateSecret` to explicitly check if `Spec.DefaultCertificate` is set to the same name as the operator generated default certificate before returning a false value
ndicating that an operator generated default certificate is not desired.
**pkg/operator/controller/certificate/default_cert_test.go:**
Add unit test for `desiredRouterDefaultCertificateSecret`.
> Bug 1912922: default_cert.go: Handle redundantly specified default certificate

- pkg/dns/aws/dns.go
- pkg/dns/azure/dns.go
- pkg/dns/dns.go
- pkg/dns/gcp/provider.go
- pkg/operator/controller/dns/controller.go
GCP: the dns targets in Google Cloud DNS is not updated after recreating loadbalancer service
> Bug 1898417: GCP the dns targets in Google Cloud DNS is not updated after recreating loadbalancer service

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/hard_stop_after_test.go
Annotating either an ingresscontroller or the ingress config with this
new annoation will redeploy the router and that will configure haproxy
to emit the haproxy "hard-stop-after" global option.
An ingresscontroller with a valid annotation set will override
ingresses.config/cluster (if set).
Examples:
Annotating the ingress config:
$ oc annotate ingresses.config/cluster ingress.operator.openshift.io/hard-stop-after=1h
Annotating the "default" ingresscontroller:
$ oc -n openshift-ingress-operator annotate ingresscontrollers/default ingress.operator.openshift.io/hard-stop-after=30m
> Bug 1905100: Add "ingress.operator.openshift.io/hard-stop-after" annotation

- pkg/operator/controller/canary/controller.go
- test/e2e/canary_test.go
**canary: Disable canary route rotation by default**
Forcing the router to reload every 5 minutes for canary testing has a
heavy performance impact for larger clusters. By default, disable the
canary route rotation logic. Canary route rotation can be enabled for
internal use or debugging by setting the new
"ingress.operator.openshift.io/rotate-canary-route" annotation to
"true" on the default ingress controller.
pkg/operator/controller/canary/controller.go:
Add a mutex to the canary controller's reconciler type
to make the new reconciler `enableCanaryRouteRotation` field
go-routine safe. Set this field to true when the default ingress
controller has the new  canary route rotation annotation
set to true. Use this field in the canary check polling loop
to determine if the canary route …
> Bug 1915079: Disable canary route churn by default

- pkg/operator/controller/dns/controller.go
**pkg/operator/controller/dns/controller.go:**
When deleting DNS records from the provider, only delete records that
have been successfully published by the provider. This resolves
BZ#1916401, in which an ingress controller created with a domain
that refers to a non-existent zone cannot be deleted. If the provider
failed to publish the DNS record, it will also fail to delete it.
It is safe to delete a DNSRecord resource in the cluster when the record
does not exist in the provider, since no upstream record needs to be
deleted first.
---
> Bug 1916401: DNS: Skip deleting records that were not published.

- pkg/operator/controller/canary/route.go
- pkg/operator/controller/canary/route_test.go
**pkg/operator/controller/canary/route.go:** 
Check that the canary service is not nil and that the canary service has a non-empty spec.ports field when building the canary route via `desiredCanaryRoute` to avoid nil dereferences.
**pkg/operator/controller/canary/route_test.go:** 
Ensure `desiredCanaryRoute` does not return any errors.
---
These changes resolve [BZ 1917942](https://bugzilla.redhat.com/show_bug.cgi?id=1917942), in which canary controller panic's were observed in OpenShift CI.
> Bug 1917942: canary: Check canary service for nil elements

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/hard_stop_after_test.go
This is a manual backport of https://github.com/openshift/cluster-ingress-operator/pull/522
Annotating either an ingresscontroller or the ingress config with this
new annoation will redeploy the router and that will configure haproxy
to emit the haproxy "hard-stop-after" global option.
An ingresscontroller with a valid annotation set will override
ingresses.config/cluster (if set).
Examples:
Annotating the ingress config:
$ oc annotate ingresses.config/cluster ingress.operator.openshift.io/hard-stop-after=1h
Annotating the "default" ingresscontroller:
$ oc -n openshift-ingress-operator annotate ingresscontrollers/default ingress.operator.openshift.io/hard-stop-after=30m
> Bug 1918371: Add "ingress.operator.openshift.io/hard-stop-after" annotation

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/status.go
`status.DeploymentDegraded` was removed in favor of several more specific status fields in 4.6, but if the cluster was upgraded from 4.5 or earlier, the existing `DeploymentDegraded` status will continue to be reported
If the cluster was upgraded from 4.1 or earlier, `status.EndpointPublishingStrategy.LoadBalancer` (introduced in 4.2?) may not be present when `status.EndpointPublishingStrategy.Type` is set to `LoadBalancerService`. Internally, the assumption is made that this is equivalent to `status.EndpointPublishingStrategy.LoadBalancer` being set to `.LoadBalancer.scope: External`, but this PR makes that implicit assumption explicit.
> Bug 1905778: Fix inconsistent ingress operator status after upgrade

- pkg/dns/aws/dns.go
- pkg/dns/aws/dns_test.go
- pkg/operator/controller/dns/controller.go
- pkg/operator/controller/dns/controller_test.go
- vendor/k8s.io/client-go/testing/actions.go
- vendor/k8s.io/client-go/testing/fake.go
- vendor/k8s.io/client-go/testing/fixture.go
- vendor/modules.txt
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
- vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
When running in an AWS C2S region, the ingress operator has two issues
* It needs to use a custom CA bundle to access the AWS API.
* It cannot use the resourcegrouptagging API since that is not available.
> Bug 1917614: get hostedzone tags from route53 on AWS C2S

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/hard_stop_after_test.go
This is a manual back port of #522.
Annotating either an ingresscontroller or the ingress config with this
new annoation will redeploy the router and that will configure haproxy
to emit the haproxy "hard-stop-after" global option.
An ingresscontroller with a valid annotation set will override
ingresses.config/cluster (if set).
Examples:
Annotating the ingress config:
$ oc annotate ingresses.config/cluster ingress.operator.openshift.io/hard-stop-after=1h
Annotating the "default" ingresscontroller:
$ oc -n openshift-ingress-operator annotate ingresscontrollers/default ingress.operator.openshift.io/hard-stop-after=30m
> Bug 1920421: Add "ingress.operator.openshift.io/hard-stop-after" annotation

- cmd/ingress-operator/start.go
- vendor/github.com/openshift/api/unidling/v1alpha1/types.go
- vendor/modules.txt
**operator.go: Add endpoint/service idle annotations check**
pkg/operator/operator.go:
Add a new function, `ensureServicesHaveIdledAnnotation(...)` that
mirrors over any idling annotations from endpoint resources when the
idling annotations are not present on the corresponding service. Call
this function during the operator start up logic so that it only runs
once (rather than calling this function within the ingress controller's
reconcile function).
**vendor: Import openshift unidling API**
> Bug 1925245: Verify that Serivce resources have idle annotations from corresponding Endpoint resources, should they exist.

- pkg/operator/controller/ingress/load_balancer_service.go
Add logic to remove the operator's finalizer on LoadBalancer services, which is no longer needed to clean up DNS records since the DNSRecord CRD was added.
* `pkg/operator/controller/ingress/load_balancer_service.go` (`ensureLoadBalancerService`): Use the new `deleteLoadBalancerService` method to delete the service as needed.  Use the new `deleteLoadBalancerServiceFinalizer` method to delete any finalizer on any existing service in the delete and update cases.
(`desiredLoadBalancerService`): Delete logic to add a finalizer to the service.
(`deleteLoadBalancerServiceFinalizer`): New method.  Delete any finalizer from the service.
(`finalizeLoadBalancerService`): Refactor to use the new `deleteLoadBalancerServiceFinalizer` method.
(`deleteLoadBalancerService`): New method.
> Bug 1914127: Delete the ingress.openshift.io/operator finalizer

- pkg/operator/controller/canary/http.go
- pkg/operator/controller/canary/route.go
- pkg/operator/controller/canary/route_test.go
**Canary: Perform canary test probes over https**
pkg/operator/controller/canary/http.go:
Commit `c98416` switched the canary route from a cleartext route to an edge terminated route. Prior to this change, the canary client made periodic test probes to the canary backend pods using http, since the insecure traffic would be redirected to https by the ingress controller. Some clusters expose the default ingress controller using an external load balancer that blocks all traffic on port 80, so this is not feasible.
**Canary: Reconcile updates for the canary route**
pkg/operator/controller/canary/route.go:
Trigger updates for the canary route when the canary route's Spec.TLS field in the cluster differs from what the operator expects.
pkg/operator/controller/canary/route_test.go:
Enhance …
> Bug 1934773: Canary: Perform canary test probes over https 

- pkg/operator/controller/canary/http.go
pkg/operator/controller/canary/http.go:
Commit b796725 overrides the default go HTTP transport
by setting a TLS configuration. The default HTTP transport
takes environment proxy settings into account, while our current
transport declaration does not. This commit explicitly adds
the `Proxy` field to the Canary `Client.Transport` field.
Note that if a cluster-wide proxy is not configured, then no proxy will
be used.
See https://golang.org/pkg/net/http/ (search for DefaultTransport)
for more information.
> Bug 1935528: Canary: Use cluster-wide proxy for canary client

- pkg/operator/controller/canary/route.go
- pkg/operator/controller/ingress/cluster-role.go
- pkg/operator/controller/ingress/dns.go
- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/monitoring.go
- pkg/operator/controller/ingress/nodeport_service.go
- pkg/operator/controller/ingress/nodeport_service_test.go
- pkg/operator/controller/ingress/poddisruptionbudget.go
- pkg/operator/controller/ingress/rsyslog_configmap.go
- pkg/operator/controller/ingress/serviceca_configmap.go
This change improves log output when reconciling managed resources to include the diff between the current and updated resources when updating resources.
* `pkg/operator/controller/canary/route.go` (`updateCanaryRoute`): Log the diff between the current and updated resources when updating the route.
* `pkg/operator/controller/ingress/cluster-role.go` (`ensureClusterRole`): Move logging of updates from here...
(`updateClusterRole`): ...to here.  Log diff.
* `pkg/operator/controller/ingress/dns.go` (`ensureWildcardDNSRecord`): Move logging of updates from here...
(`updateDNSRecord`): ...to here.  Log diff.
* `pkg/operator/controller/ingress/load_balancer_service.go` (`ensureLoadBalancerService`): Move logging of updates from here...
(`updateLoadBalancerService`): ...to here.  Log diff.
* …
> Bug 1936030: Fix spurious reconciliation of NodePort services

- cmd/ingress-operator/start.go
- vendor/github.com/openshift/api/unidling/v1alpha1/types.go
- vendor/modules.txt
**operator.go: Add endpoint/service idle annotations check**
pkg/operator/operator.go:
Add a new function, `ensureServicesHaveIdledAnnotation(...)` that
mirrors over any idling annotations from endpoint resources when the
idling annotations are not present on the corresponding service. Call
this function during the operator start up logic so that it only runs
once (rather than calling this function within the ingress controller's
reconcile function).
**vendor: Import openshift unidling API**
---
This a manual backport of https://github.com/openshift/cluster-ingress-operator/pull/542 for 4.6.
> Bug 1927364: Verify that Serivce resources have idle annotations from corresponding Endpoint resources, should they exist.

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
Before this PR, the operator configured HAProxy with log level "debug" to enable access logs.  However, access logs are emitted at the "info" or "error" levels, so setting the log level to "info" is sufficient and avoids logging superfluous information.
* `pkg/operator/controller/ingress/deployment.go` (`desiredRouterDeployment`): Set the `ROUTER_LOG_LEVEL` environment variable's value to "info" instead of to "debug" when enabling access logs.
* `pkg/operator/controller/ingress/deployment_test.go` (`TestDesiredRouterDeployment`): Expect "info" instead of "debug" for `ROUTER_LOG_LEVEL`.
> Use HAProxy log level "info" to enable access logs

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/status.go
4.6 backport of #526 
`status.DeploymentDegraded` was removed in favor of several more specific status fields in 4.6, but if the cluster was upgraded from 4.5 or earlier, the existing `DeploymentDegraded` status will continue to be reported
If the cluster was upgraded from 4.1 or earlier, `status.EndpointPublishingStrategy.LoadBalancer` (introduced in 4.2?) may not be present when `status.EndpointPublishingStrategy.Type` is set to `LoadBalancerService`. Internally, the assumption is made that this is equivalent to `status.EndpointPublishingStrategy.LoadBalancer` being set to `.LoadBalancer.scope: External`, but this PR makes that implicit assumption explicit.
> [release-4.6] Bug 1921193: Fix inconsistent ingress operator status after upgrade

- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
Annotation `service.beta.kubernetes.io/aws-load-balancer-internal` is
currently set as `"0.0.0.0/0"` in the operator-created load balancer
service when using an internal load balancer on AWS. The prefered value
for this annotation is now `"true"`[1][2], although both values seem to be
valid.
[1] https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
[2] https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html
> Bug 1907315: Change AWS interal LB annotation to match documentation

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/controller_test.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/http_header_buffer_test.go
**Implement Router Tunable Buffer Sizes**
pkg/operator/controller/ingress/controller.go:
New func, `validateHTTPHeaderBufferValues`, to validate `HTTPHeaderBuffer` values when an ingress controller specifies them. Reject ingress controllers that specify improper `HTTPHeaderBuffer` values (ie `HeaderBufferBytes < HeaderBufferMaxRewrite`).
pkg/operator/controller/ingress/controller_test.go:
Add unit test coverage for `validateHTTPHederBufferValues`.
pkg/operator/controller/ingress/deployment.go:
Append `ROUTER_BUF_SIZE` and `ROUTER_MAX_REWRITE_SIZE` env variables to an IngressController's deployment when an IngressController specifies either `HeaderBufferBytes` or `HeaderBufferMaxRewriteBytes` via `Spec.HTTPHeaderBuffer`.
pkg/operator/controller/ingress/deployment_test.go:
Add valid …
> NE-354: Implement Tunable router header buffers

- pkg/operator/controller/ingressclass/ingressclass.go
- test/e2e/operator_test.go
Comment out the logic that sets marks the default ingresscontroller's ingressclass as the default ingressclass because it breaks the "[sig-network] IngressClass [Feature:Ingress] should not set default value if no default IngressClass" test.
* `pkg/operator/controller/ingressclass/ingressclass.go` `(`desiredIngressClass): Don't set default annotation.
* `test/e2e/operator_test.go` (`TestDefaultIngressClass`): Don't check for default annotation.
> Bug 1946788: ingressclass: Don't set default annotation

- test/e2e/configurable_route_test.go
When updating the `ingresses.config.openshift.io/cluster` object, get the current object before updating it so that we don't blank out fields that are already set.
* `test/e2e/configurable_route_test.go` (`TestConfigurableRouteRBAC`, `TestConfigurableRouteNoSecretNoRBAC`, `TestConfigurableRouteNoConsumingUserNoRBAC`): Get the ingress cluster config object before updating it.
---
This change is intended to resolve the following error condition from the authentication operator:
```
Operator degraded (APIServerDeployment_UnavailablePod::IngressConfig_Invalid::OAuthClientsController_SyncError::OAuthServerRouteEndpointAccessibleController_SyncError::RouterCerts_NoIngressDomain): APIServerDeploymentDegraded: 1 of 3 requested instances are unavailable for apiserver.openshift-oauth-apiserver (2 …
```
> configurable_route_test: Preserve ingress spec

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/nbthread_test.go
- test/e2e/util.go
ingress operator reads the IngressController's `spec.tuningOptions.threadCount` field, and sets the `"ROUTER_THREADS"` environment variable in the desired router deployment according to its value.
this is dependent on [openshift/api #875](https://github.com/openshift/api/pull/875), and part of the implementation of [openshift/enhancements #708](https://github.com/openshift/enhancements/pull/708)
> NE-302: Add field for configuring number of HAProxy threads in router

- pkg/dns/azure/dns.go
pkg/dns/azure/dns.go: Log when using domain not in zone
Modify getARecordName so that the DNS controller logs a message when
DNS record with domain strings that do not contain the given zone name
are updated.
> Bug 1919151: Azure: Log when using domain not in zone

- pkg/operator/controller/ingressclass/controller.go
- test/e2e/operator_test.go
Use the correct group name in the predicate for the watch on ingressclasses in the ingressclass controller so that the controller reconciles events for ingressclasses that reference the ingress-to-route controller.
* `pkg/operator/controller/ingressclass/controller.go` (`ingressClassHasIngressController`): Use the correct string for the group name.
* `test/e2e/operator_test.go` (`TestDefaultIngressClass`): Verify that the ingressclass controller recreates the ingressclass should it be deleted.
> Bug 1949435: ingressclass: Fix API group name in watch predicate

- pkg/operator/controller/ingress/poddisruptionbudget.go
- test/e2e/operator_test.go
Bring imports up to date with k8s 1.21 so that deprecation messages go away.
pkg/operator/controller/ingress/poddisruptionbudget.go
test/e2e/operator_test.go
> Bug 1947498: policy v1 beta1 PodDisruptionBudget is deprecated

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/namespace.go
- pkg/operator/controller/ingress/namespace_test.go
**ingress: Reconcile openshift-ingress namespace on upgrade**
Commits `263c2aa` and `3505256` added new annotations and labels to the
openshift-ingress namespace, which is managed by the ingress-operator.
This commit adds logic to reconcile the openshift-ingress namespace
resource during cluster upgrades. To prevent overwriting changes made to
the namespace resource by other controllers (or cluster-admins), the
namespace reconciliation logic added in this commit explicitly syncs
namespace labels and annotations that the operator sets.
pkg/operator/controller/ingress/namespace.go:
Refactor `ensureRouterNamespace` so that it handles creating and updating
the openshift-ingress namespace resource (and nothing else).
Add new functions: `currentRouterNamespace`, `updateRouterNamespace`, & …
> Bug 1954330: Reconcile openshift-ingress namespace on upgrade

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
Specify topology spread constraints on router deployments to encourage the scheduler to spread router pod replicas across availability zones.
Add a to-do to replace the hard anti-affinity rule with soft anti-affinity once the descheduler has support for enforcing soft anti-affinity rules.
* `pkg/operator/controller/ingress/deployment.go` (`desiredRouterDeployment`): Rename `needDeploymentHash` to `configureAffinity` as we now always need to compute the deployment hash but do not always specify an affinity policy. Specify `spec.template.spec.topologySpreadConstraints`.  Specify max skew 1, unsatisfiable-constraint action `ScheduleAnyway`, topology key `topology.kubernetes.io/zone`, and a label selector on the deployment hash label so as to specify a preference for spreading replicas of the …
> Bug 1900819: Specify topology spread constraints

- pkg/operator/controller/ingress/namespace.go
- pkg/operator/controller/ingress/namespace_test.go
Commit `ea085e7` added logic to reconcile the Ingress namespace during
cluster upgrades. This follow-up commit fixes some mistakes introduced
by that commit.
pkg/operator/controller/ingress/namespace.go:
Fix a typo: `opensift.io/cluster-monitoring`.
We are, after all, in the computing business, and not the baking
business.
Check if annotation/label map values exist since comparing a
non-existent map value to the empty string will always return true
in this case.
pkg/operator/controller/ingress/namespace_test.go:
Add unit test to prove that a map value that does not exist
is equivalent to the empty string.
Rename the `original` namespace to `desired`.
Switch ordering of `desired` and `mutated` in `routerNamespaceChanged`
calling sites to better reflect the intent of the unit tests.
--- …
> Bug 1954330: ingress: Fix up openshift-ingress namespace reconciliation

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/http_header_buffer_test.go
- test/e2e/operator_test.go
Ingress components may run directly behind load balancers and thus
need to delay deployment rollout long enough for the load balancers
to see the new process. Without minReadySeconds, the upgrade process
will immediately delete the old pod as soon as the new pod is ready,
which means that the LB may briefly see no pods, which then triggers
on some LB the behavior of including all hosts (generally if all
hosts are unhealthy the LB will allow requests to go to any host
as opposed to failing closed).
while we test with this
> Bug 1959194: Ingress rollouts should specify minReadySeconds

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
BZ https://bugzilla.redhat.com/1901648
The following use case is fixed now by this fix:
1. Create Ingress with a custom domain
2. Ingress status gets updated by OpenShift Ingress controller with router canonical hostname
3. Use external-dns to sync with Route 53
The problem was the canonical router hostname didn't exist in the DNS. It is not created by OpenShift. OpenShift creates this *.apps.<cluster_name>.<base_domain> DNS record and not this one apps.<cluster_name>.<base_domain>. So canonical router hostname was not right. Now this fix sets it to router-default.apps.<cluster_name>.<base_domain>
> Bug 1901648: Canonical router hostname not correct

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/nodeport_service.go
- pkg/operator/controller/ingress/nodeport_service_test.go
- test/e2e/operator_test.go
* `pkg/operator/controller/ingress/deployment.go` (`desiredRouterDeployment`): Mention that the deployment exposes port 1936 in addition to ports 80 and 443.
When creating the `NodePort`-type service for an ingresscontroller that specifies the `NodePortService` endpoint publishing strategy type, include a "metrics" port with port 1936 so that external load balancers can use the `/healthz/ready` endpoint.
* `pkg/operator/controller/ingress/nodeport_service.go` (`ensureNodePortService`): Pass an argument to `desiredNodePortService` to tell it not to add a "metrics" port if the service already exists and omits the port.
(`desiredNodePortService`): Add a `wantMetricsPort` parameter.  Add port 1936 to the service's ports spec if `wantMetricsPort` is true.
* …
> Bug 1881210: desiredNodePortService: Add port 1936

- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- pkg/operator/controller/ingress/nodeport_service.go
- pkg/operator/controller/ingress/nodeport_service_test.go
- test/e2e/operator_test.go
Set the `traffic-policy.network.alpha.openshift.io/local-with-fallback` annotation on LoadBalancer- and NodePort-type services that use the `Local` external traffic policy.
* `pkg/operator/controller/ingress/load_balancer_service.go` (`localWithFallbackAnnotation`): New const.  Define the annotation key for the `local-with-fallback` service annotation.
(`desiredLoadBalancerService`): Set the `local-with-fallback` annotation when using the `Local` external traffic policy.
(`managedLoadBalancerServiceAnnotations`): New variable.  Define the keys for annotations that the operator manages on LoadBalancer-type services, which now include the `local-with-fallback` annotation.
(`loadBalancerServiceChanged`): Fix the update logic to properly handle annotations with empty values using go-cmp and …
> Bug 1960284: Set the "local-with-fallback" service annotation

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/namespace.go
- pkg/operator/controller/ingress/namespace_test.go
This PR is a manual 4.7 cherry-pick for https://github.com/openshift/cluster-ingress-operator/pull/608 & https://github.com/openshift/cluster-ingress-operator/pull/611.
Since the operator explicitly _does not_ manage any Router namespace annotations in 4.7 and prior, some minor modifications were made to the included commits. In doing so, code was only removed, and no new code has been added. Kindly review the "backport friendly" versions of `routerNamespaceChanged` and `testRouteNamespaceChanged`.
> [release-4.7] Bug 1960776: Reconcile openshift-ingress namespace on upgrade 

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/controller_test.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/operator_test.go
Delete filterTLS13Ciphers and simplify
Simplify the logic in validateTLSSecurityProfile so that filterTLS13Ciphers
is no longer needed, and delete the superfluous function definition.
* pkg/operator/controller/ingress/controller.go
(validateTLSSecurityProfile): Simplify TLSv1.3 ciphers check.
(filterTLS13Ciphers): Delete function.
Allow TLSv1.3 and the "Modern" TLS profile
OpenShift 4.6 is built using UBI 8, which has OpenSSL 1.1.1, which supports
TLSv1.3, so allow specifying spec.tlsSecurityProfile.type: Modern or
spec.tlsSecurityProfile.custom.minTLSVersion: VersionTLS13.
* pkg/operator/controller/ingress/controller.go
tlsProfileSpecForSecurityProfile): Allow use of the "Modern" profile.
(validTLSVersions): Add configv1.VersionTLS13.
(validateTLSSecurityProfile): Verify that some …
> NE-472:Add tlsv1.3 support

- pkg/operator/controller/canary/daemonset.go
- pkg/operator/controller/canary/daemonset_test.go
Commit 8332af2 changed the Canary daemonset image and command values
in OCP 4.8.
Prior to commit 8332af2, the Canary's daemonset logic did not trigger
updates to the Canary daemonset when the `command` field was modified.
When downgrading from OCP 4.8 to OCP 4.7, the 4.7 Canary container
is fed a startup command intended for the 4.8 Canary image, which
results in Canary endpoints that don't actually send back the
expected response body.
This commit is a partial backport of commit 8332af2 in order
to remove unwanted daemonset `command` values available in OCP 4.8
that should not exist on the daemonset in OCP 4.7.
pkg/operator/controller/canary/daemonset.go:
Update the canary daemonset when the canary server, image, or container
name changes (e.g. handle downgrades from OCP 4.8 to OCP 4.7). …
> [release-4.7] Bug 1973983: Canary: Handle downgrades from 4.8 to 4.7 properly

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/operator_test.go
Add an unsupported config override to enable OpenShift router's dynamic config manager for HAProxy.
* `pkg/operator/controller/ingress/deployment.go` (`RouterHAProxyConfigManager`): New const.
(`desiredRouterDeployment`): Add unsupported config override for `ROUTER_HAPROXY_CONFIG_MANAGER`.
* `pkg/operator/controller/ingress/deployment_test.go` (`TestDesiredRouterDeployment`): Verify that `desiredRouterDeployment` sets `ROUTER_HAPROXY_CONFIG_MANAGER` as expected.
* `test/e2e/operator_test.go` (`TestDynamicConfigManagerUnsupportedConfigOverride`): Verify that the operator sets `ROUTER_HAPROXY_CONFIG_MANAGER` on a router deployment for an IngressController that enables the unsupported config override.
> Add unsupported config override for config manager

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/rsyslog_configmap.go
Stop unnecessarily passing `ingressConfig` to `ensureRsyslogConfigMap` and `desiredRsyslogConfigMap`, which previously used the value but no longer do.
Follow-up to #374.
* `pkg/operator/controller/ingress/controller.go` (`ensureIngressController`): Remove the `ingressConfig` argument in the call to `ensureRsyslogConfigMap`.
* `pkg/operator/controller/ingress/rsyslog_configmap.go` (`ensureRsyslogConfigMap`, `desiredRsyslogConfigMap`): Remove the `ingressConfig` parameter.
> ensureRsyslogConfigMap: Remove ingressConfig param

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/operator_test.go
* `pkg/operator/controller/ingress/deployment.go` (`RouterReloadIntervalEnvName`): New const.
(`desiredRouterDeployment`): Add unsupported config override for `RELOAD_INTERVAL`.
* `pkg/operator/controller/ingress/deployment_test.go` (`TestDesiredRouterDeployment`): Verify the `desiredRouterDeployment` sets `RELOAD_INTERVAL` as expected.
> Add unsupported config override for reload interval

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/canary_test.go
- test/e2e/client_tls_test.go
- test/e2e/http_header_buffer_test.go
- test/e2e/http_header_name_case_adjustment_test.go
- test/e2e/operator_test.go
This PR bundles (in logically separate commits) a fix to the reload interval override, a small fix to the E2E tests, and a new unsupported config override for `ROUTER_MAX_CONNECTIONS`.
* `test/e2e/operator_test.go` (`waitForDeploymentEnvVar`): Use the provided timeout parameter instead of a hard-coded value of 1 minute.
Specify a time unit suffix "s" for seconds in the value of the `RELOAD_INTERVAL` environment variable in router deployments.  Omitting the time unit causes the following warning:
router "msg"="invalid interval, using default"  "default"=5 "interval"="5" "name"="RELOAD_INTERVAL"
* `pkg/operator/controller/ingress/deployment.go` (`desiredRouterDeployment`): Add "s" time unit suffix to the reload interval.
* `pkg/operator/controller/ingress/deployment_test.go` …
> Add unsupported config override for maxconn

- go.mod
- pkg/manifests/manifests.go
- test/e2e/hsts_policy_test.go
- test/e2e/operator_test.go
- test/e2e/util.go
- vendor/modules.txt
Simple e2e test to ensure:
- updated CRD is available
- HSTS validation is operational
- HSTS header is returned from query to annotated route
> Bug 1986228: NE-310 E2E test for HSTS

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/metrics.go
- pkg/operator/controller/ingress/metrics_test.go
- vendor/github.com/prometheus/client_golang/prometheus/testutil/lint.go
- vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/promlint.go
- vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
- vendor/modules.txt
Enhance the finalize logic for the deleted ingress controller with the cleanup of the corresponding condition metrics.
```bash
$ oc exec ingress-operator-946847d8-2f7cl -c ingress-operator -- curl -s http://127.0.0.1:60000/metrics | grep ingress_controller_conditions 
ingress_controller_conditions{condition="Available",name="default"} 1
ingress_controller_conditions{condition="Degraded",name="default"} 0
$ oc apply -f ~/manifests/custom-ingresscontroller.yaml
ingresscontroller.operator.openshift.io/test-12345 created
$ oc -n openshift-ingress get pods -o wide
NAME                                READY   STATUS    RESTARTS   AGE   IP            NODE                                       NOMINATED NODE   READINESS GATES
router-default-596b45c968-jvlgq     1/1     Running   0          57m …
```
> Bug 1972977: cleanup condition metrics for deleted ingress controllers

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/controller_test.go
Check that any patterns specified using an ingresscontroller's `spec.clientTLS.allowedSubjectPatterns[*]` field are valid PCRE patterns, and set the `Admitted` status condition to `False` if any patterns are invalid.
* `pkg/operator/controller/ingress/controller.go` (`validate`): Call the new `validateClientTLS` function.
(`validateClientTLS`): New function.  Validate an ingresscontroller's client TLS configuration, in particular `allowedSubjectPatterns`.
* `pkg/operator/controller/ingress/controller_test.go` (`TestValidateClientTLS`): New test.  Verify that `validateClientTLS` behaves as expected.
> Bug 1989005: Validate spec.clientTLS.allowedSubjectPatterns[*]

- pkg/operator/controller/ingress/deployment.go
- test/e2e/haproxy_timeouts_test.go
- test/e2e/util.go
This PR adds 2 tests to the e2e suite:
TestHAProxyTimeouts: 
- Set timeouts for all 6 new timeout fields, and verify that all timeout values are reflected in the router deployment's environment.
- Most of the values are set to durations that, if converted directly from `Duration` to `string`, would be invalid strings to HAProxy. E.g. `90 * time.Second` would string-ify as "1m30s", but HAProxy requires it to only use one time unit, such as "90s". This makes sure the `durationToHAProxyTimespec` function is working as intended.
- One timeout value is set higher than the maximum HAProxy will allow, to make sure that the timeout is clipped to HAProxy's max.
TestHAProxyTimeoutsRejection:
- Sets timeouts for all 6 new timeout fields that are allowed by the API, but are not actually valid timeout …
> Bug 1986575: Add e2e test cases for haproxy timeout api fields, and reject negative timeout values

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
Configure OpenShift router to use the "source" balancing algorithm for passthrough routes in order to provide some session-affinity.
This was the behavior for passthrough routes before OpenShift 4.8, and changing it was unintentional.
Follow-up to https://github.com/openshift/cluster-ingress-operator/pull/589/commits/e83b057c6b5e18341cad743a056795ba255bc3cf.
* `pkg/operator/controller/ingress/deployment.go` (`RouterTCPLoadBalancingAlgorithmEnvName`): New const for the `ROUTER_TCP_BALANCE_SCHEME` environment variable.
(`desiredRouterDeployment`): Set `ROUTER_TCP_BALANCE_SCHEME` to "source".
* `pkg/operator/controller/ingress/deployment_test.go` (`TestDesiredRouterDeployment`): Verify that `desiredRouterDeployment` sets `ROUTER_TCP_BALANCE_SCHEME` appropriately.
> Bug 1997407: Configure router to use "source" for passthrough

- pkg/operator/controller/ingress/controller.go
Delete duplicate entries in `tlsVersion13Ciphers`.
The entries in `tlsVersion13Ciphers` were copied from a table in <https://www.openssl.org/docs/man1.1.1/man1/ciphers.html>, which lists each cipher suite twice: once by its name in the relevant specification and once by its name in OpenSSL, and these names happen to be identical in the case of TLSv1.3 cipher suites.  Logically, only the OpenSSL names should be included in `tlsVersion13Ciphers`.
Follow-up to <https://github.com/openshift/cluster-ingress-operator/pull/315/commits/92914d9200dfb604fcb2f315c701b1406b7c3bc3>.
* `pkg/operator/controller/ingress/controller.go` (`tlsVersion13Ciphers`):
Reformat and delete duplicate entries.
> tlsVersion13Ciphers: Delete duplicates

- pkg/dns/ibm/client/client.go
- pkg/dns/ibm/client/fake_client.go
- pkg/dns/ibm/dns.go
Related bugzilla report: https://bugzilla.redhat.com/show_bug.cgi?id=2001479
This PR fixes bugs in IBM Cloud DNS Provider:
- initialize provider map
- fix cis url
- set valid TTL for dns records
- trim dot from the end of dns record name before listing records (issue during wildcard record operations)
- remove unused NewGetDnsRecordOptions from interface
> Bug 2001479: Fix IBM Cloud DNS bugs

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
This is a manual cherry-pick of https://github.com/openshift/cluster-ingress-operator/pull/650.
> [release-4.8] Bug 2000414: Configure router to use "source" for passthrough

- test/e2e/dns_ingressdegrade_test.go
Follow-up to https://github.com/openshift/cluster-ingress-operator/pull/662/commits/fe8c1ee814a5d1c361461ab39b49543ba61666f1 based on review comments on the release-4.9 backport: https://github.com/openshift/cluster-ingress-operator/pull/664#pullrequestreview-793432926
* `test/e2e/dns_ingressdegrade_test.go` (`updateDNSConfig`): Replace integer literals with `len(injectError)`.  Change `injectError` to a const.
> Bug 2014710: test/e2e: updateDNSConfig: Replace integer literals

- test/e2e/dns_ingressdegrade_test.go
This is a manual cherry-pick of #662 and #672.
---
The recently added `TestIngressStatus` test fails on Azure, causing the e2e-azure-operator CI jobs in the cluster-ingress-operator repository to fail consistently.  This backport fixes the test so that it passes on Azure.  This is needed so that we can verify cluster-ingress-operator PRs to the release-4.9 branch on Azure.  This change has no direct impact on users.
> [release-4.9] Bug 2014711: Fix for Azure dns privateZone degrade e2e test

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
- pkg/operator/controller/status/controller.go
- pkg/operator/controller/status/controller_test.go
- test/e2e/operator_test.go
Add support for changing ingresscontroller load balancer scope. On AWS and IBM cloud, this requires deleting the existing load balancer service and recreating it with the desired scope; if the administrator changes the scope on the ingresscontroller, the operator will report `Progressing=True` until the administrator either reverts the change or deletes the service. If the administrator deletes the service, then the operator will recreate the service with the desired scope.  On Azure and GCP, it suffices to update the existing service's annotations.
This commit is based on #472, which was reverted by commit #514.  Unlike the original implementation of this feature, the operator does not delete the service but instead leaves it up to the administrator to do so as needed.
* …
> NE-621: Support changing ingresscontroller load balancer scope

- pkg/dns/alibaba/dns.go
- pkg/dns/alibaba/dns_test.go
- pkg/dns/alibaba/service.go
- pkg/dns/alibaba/util/credentials.go
- pkg/dns/alibaba/util/numbers.go
- pkg/dns/alibaba/util/numbers_test.go
- pkg/operator/controller/dns/controller.go
Here's a follow-up PR for #636 to get some code improvements based on the code review, and unit test for Alibaba DNS part.
This PR changes the logic of retrieving private zone ID by moving it to before every request, and caches it in local (dns.go:226).
And unit test is still work in progress, it should be pushed in a few days.
Signed-off-by: xiayu.lyt <xiayu.lyt@alibaba-inc.com>
> Code improvements and unit tests for Alibaba DNS

- test/e2e/configurable_route_test.go
Fix intermittent failures in the `TestConfigurableRouteRBAC`, `TestConfigurableRouteNoSecretNoRBAC`, and `TestConfigurableRouteNoConsumingUserNoRBAC` tests that were caused by incorrect update retry logic.
These tests use the `eventuallyUpdateIngressSpec` and `eventuallyUpdateIngressStatus` helper functions to update the cluster ingress config.  Before this change, these helper functions attempted to update the ingress config using a polling loop that gets the current config, assigns a value provided as an argument to the helper function to a field in the config value from the API, and then updates the config in the API using the modified config value.  The argument value is a complex data type, and so the assignment causes the argument value and the modified config value to reference the …
> Fix update retry logic in TestConfigurableRoute*

- pkg/operator/controller/ingress/controller.go
Refactor the update logic in `setDefaultPublishingStrategy`.  Also, fix `setDefaultPublishingStrategy` to return true if the scope changed.  (Nothing uses this return value, so this change is only for correctness.)
* `pkg/operator/controller/ingress/controller.go` (`setDefaultPublishingStrategy`): Use a switch statement for the update logic so that the logic only looks at parameters related to the selected endpoint publishing strategy type.
Fix the update logic in `setDefaultPublishingStrategy` so that updates are properly handled when `status.endpointPublishingStrategy.hostNetwork` or `status.endpointPublishingStrategy.nodePort` is null.
Before OpenShift 4.8, the IngressController API did not have any fields under the `status.endpointPublishingStrategy.hostNetwork` and …
> Bug 1997226: Fix enabling PROXY protocol on an upgraded cluster

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/controller_test.go
Make a copy of `spec.endpointPublishingStrategy` to avoid mutating it, and add unit tests for `setDefaultDomain` and `setDefaultPublishingStrategy`.
Follow-up to #681.
* `pkg/operator/controller/ingress/controller.go` (`setDefaultPublishingStrategy`): Use a deep copy of `ic.Spec.EndpointPublishingStrategy`.
* `pkg/operator/controller/ingress/controller_test.go` (`TestSetDefaultDomain`, `TestSetDefaultPublishingStrategySetsPlatformDefaults`, `TestSetDefaultPublishingStrategyHandlesUpdates`): New tests.
---
@candita, @miheer
> Bug 1997226: setDefaultPublishingStrategy: Deep copy, tests

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
- pkg/operator/controller/status/controller.go
- pkg/operator/controller/status/controller_test.go
This change sets the `Upgradeable` condition for the IngressController. If the corresponding load balancer _Service_ has been modified, particularly the AWS resource tags fields then the IngressController is marked as `Upgradable=False`. This in turn marks the operator as `Upgradeable=False`.
> Bug 2039339: Upgradeable Condition in Operator and IC status

- pkg/operator/controller/canary/http.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2037447
If keepalives are enabled then we see an accumulation of established
canary connections that remain in ESTABLISHED state. Given that we
only probe once per minute it's not clear we gain anything from
keepalives so let's just disable them when probing the canary host.
This helps prevent resource exhaustion.
> BUG 2037447: Disable keepalive for canary probe

- pkg/operator/controller/ingress/load_balancer_service.go
- test/e2e/operator_test.go
The AWS cloud-provider implementation checks the `service.beta.kubernetes.io/aws-load-balancer-internal` service annotation to determine whether a service load-balancer (SLB) should be internal.  The cloud-provider implementation recognizes both the value "0.0.0.0/0" and the value "true" as indicating that the SLB should be internal.  OpenShift 4.7 and earlier use the value "0.0.0.0/0", and OpenShift 4.8 and later use the value "true".  A service that was created on an older cluster might have the value "0.0.0.0/0", which can cause comparisons that check for the "true" value to return the wrong result.  This PR adds logic to normalize the annotation value to "true".
Follow-up to <https://github.com/openshift/cluster-ingress-operator/pull/543> and to …
> Bug 2055470: Normalize the AWS internal LB annotation value

- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
If an ingresscontroller's default certificate has a Common Name (CN) for the ingress domain but has no Subject Alternative Name (SAN) for the same, report that the cluster cannot be upgraded by setting the `Upgradeable=False` status condition on the ingresscontroller and clusteroperator.
Clients built using Go 1.17 reject certificates without SANs.  OpenShift 4.10 is built using Go 1.17, which means that various operators that connect to routes that use the default certificate would reject the certificate and fail to complete the TLS handshake after upgrading to OpenShift 4.10 if the ingress operator didn't block the upgrade on a cluster with a problematic certificate.
* `pkg/operator/controller/ingress/status.go` (`syncIngressControllerStatus`): Get the default certificate secret and …
> Bug 2057762: Set Upgradeable=False if default cert has no SAN

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
- pkg/operator/controller/status/controller.go
- pkg/operator/controller/status/controller_test.go
This change sets the `Upgradeable` condition for the IngressController. If the corresponding load balancer _Service_ has been modified, particularly the AWS resource tags fields then the IngressController is marked as `Upgradable=False`. This in turn marks the operator as `Upgradeable=False`.
> Bug 2058699: Upgradeable Condition in Operator and IC status

- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
This is a manual cherry-pick of https://github.com/openshift/cluster-ingress-operator/pull/708 with an additional fix for an issue introduced in #709 (see https://github.com/openshift/cluster-ingress-operator/pull/709#discussion_r817929252).  
---
Don't use `infraConfig.Status.PlatformStatus` directly; `infraConfig.Status` could be nil.
Follow-up to #709.
* `pkg/operator/controller/ingress/status.go`: Use `GetPlatformStatus`.
If an ingresscontroller's default certificate has a Common Name (CN) for the ingress domain but has no Subject Alternative Name (SAN) for the same, report that the cluster cannot be upgraded by setting the `Upgradeable=False` status condition on the ingresscontroller and clusteroperator.
Clients built using Go 1.17 reject certificates without SANs.  OpenShift 4.10 is …
> [release-4.9] Bug  2060111: Set Upgradeable=False if default cert has no SAN

- pkg/manifests/manifests.go
- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/load_balancer_service.go
Delete the deletion logic for the "ingress.openshift.io/operator" finalizer for LoadBalancer-type services.  This finalizer has not been needed since OpenShift 4.2, when the DNSRecord CRD was added.  OpenShift 4.8 removed the logic that added the finalizer and added logic to remove the finalizer. Thus with OpenShift versions after OpenShift 4.8, this finalizer no longer exists, and the corresponding logic can be deleted.
Follow-up to https://github.com/openshift/cluster-ingress-operator/pull/549.
* `pkg/manifests/manifests.go` (`LoadBalancerServiceFinalizer`): Delete const.
* `pkg/operator/controller/ingress/controller.go` (`ensureIngressDeleted`): Delete calls to `finalizeLoadBalancerService`.
* `pkg/operator/controller/ingress/load_balancer_service.go` (`ensureLoadBalancerService`): …
> Bug 2069457: Delete LoadBalancer-type service finalizer logic

- pkg/dns/ibm/dns_test.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- pkg/operator/controller/ingress/nodeport_service_test.go
Running `go test ./...` using go 1.18 results in errors along the lines
of:
```
...
pkg/operator/controller/ingress/load_balancer_service_test.go:548:4: (*testing.common).Errorf does not support error-wrapping directive %w
pkg/operator/controller/ingress/nodeport_service_test.go:137:4: (*testing.common).Errorf does not support error-wrapping directive %w
...
```
This PR should fix that
> Bug 2072106: Fix test `Errorf` limitation in go 1.18

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/operator_test.go
- test/e2e/util.go
Allow users to set the `timeoutSeconds` parameter on the liveness, readiness, and startup probes for router deployments other than that of the default ingresscontroller.
* `pkg/operator/controller/ingress/deployment.go` (`ensureRouterDeployment`): Check the ingresscontroller's name to determine whether it is the default ingresscontroller and pass a Boolean value indicating the same to `desiredRouterDeployment` and `updateRouterDeployment`.
(`desiredRouterDeployment`): Add a `defaultIngressController` parameter and pass its argument to `deploymentTemplateHash`.
(`deploymentHash`, `deploymentTemplateHash`): Add a `defaultIngressController` parameter and pass the argument to `hashableDeployment`.
(`hashableDeployment`): Add a `defaultIngressController` parameter and pass its argument to …
> NE-781: Allow users to tune kubelet probe timeouts

- pkg/operator/operator.go
An empty string was included in MultiNamespacedCacheBuilder which was intended to capture
Cluster Scoped Resources, but it erroneously included ALL objects in ANY namespace.
It also duplicated other objects that had already been selected by a namespace. It is not
needed since cluster scoped resources are already included in the cache by default.
This may fix many inefficiencies such as double reconcilations and cache overloading.
> Bug 2075671: Fix k8s client cache object global inclusion and duplication.

- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- pkg/operator/controller/ingress/nodeport_service.go
- test/e2e/operator_test.go
If custom created service in the openshift-ingress namespace has the same naming convention of what the ingress controllers uses, it will be deleted. This fix ensures that the only services that get deleted are owned by the ingress controller responsible for creating it.
> BUG 2054200: Fix removing custom created service in openshift-ingress with same name

- test/e2e/configurable_route_test.go
RBAC tests fail in teardown with:
configurable_route_test.go:301: failed to restore cluster ingress resource to original state: Operation cannot be fulfilled on ingresses.config.openshift.io "cluster": the object has been modified; please apply your changes to the latest version and try again
configurable_route_test.go:305: failed to restore cluster ingress resource to original state: Operation cannot be fulfilled on ingresses.config.openshift.io "cluster": the object has been modified; please apply your changes to the latest version and try again
Change the defer logic for all the RBAC e2e tests to make multiple
attempts to restore both the spec and status when the test completes.
> BUG 2076984: test/e2e: add resilience to RBAC test teardown

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/checkinterval_test.go
[NE-585](https://issues.redhat.com/browse/NE-585) Expose and make configurable ROUTER_BACKEND_CHECK_INTERVAL to customize the length of time between subsequent liveness checks on backends. Details in the [enhancement proposal](https://github.com/openshift/enhancements/blob/master/enhancements/ingress/haproxy-healthcheckinterval.md)
Refactor some unit tests and add e2e test.
> NE-585: Make ROUTER_BACKEND_CHECK_INTERVAL configurable

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- pkg/operator/controller/ingress/replicas.go
- pkg/operator/operator.go
Implementation of the https://github.com/openshift/enhancements/blob/master/enhancements/single-node/single-node-openshift-with-workers.md
enhancement.
The installation process now sets the new `DefaultPlacement`
API field in the Ingress Config CR's status (https://github.com/openshift/installer/pull/5746
still unmerged at the time of writing this message).
This PR introduces two new changes -
- While creating the default `IngressController`, or while creating
deployments corresponding to `IngressController` resources which
don't have their number of replicas set, we determine the number
of replicas according to the value of the new `DefaultPlacement`
parameter.
- When creating Deployments out of `IngressController` resources
which don't have their nodeSelector set, we determine the …
> MGMT-9797: Determine number of replicas according to `DefaultPlacement`

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
Set `ROUTER_DOMAIN` to the IngressController's domain in the router deployment so that the router can use the domain to construct a default host for routes that specify an empty value for `spec.host` and a nonempty value for `spec.subdomain`.
* `pkg/operator/controller/ingress/deployment.go` (`desiredRouterDeployment`): Set `ROUTER_DOMAIN`.
* `pkg/operator/controller/ingress/deployment_test.go` (`TestDesiredRouterDeployment`): Verify that `ROUTER_DOMAIN` is set as expected.
> NE-882: Set `ROUTER_DOMAIN` to enable route subdomain field

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
Follow-up to #694.
* `pkg/operator/controller/ingress/deployment_test.go` (`TestDeploymentConfigChanged`): Update the correct ports in the test cases for mutating the "https" and "metrics" ports.
Specify `deployment.spec.template.spec.containers[0].ports[*].protocol` in router deployments.
Before this change, the operator left the protocol field unspecified, and as a consequence, the update logic would keep trying to revert the default value that the API set for this field.  The default value for this field is "TCP", so specifying "TCP" has the result that the API does not need to update the deployment to fill in the default value, and so the operator's update logic is no longer triggered by the API's defaulting of this field.
Follow-up to #694.
* …
> Bug 2081447: `desiredRouterDeployment`: Fix for port defaulting

- pkg/dns/aws/dns.go
This PR is just #703 with the requested fix implemented.
>  Add support for route53 in the us-isob-east-1 region + fix

- pkg/dns/aws/dns.go
Currently the operator defaults to using the us-east-1 region endpoint for route53 in the us-isob-east-1 region which does not work. Add support for the route53 in the us-isob-east-1 region.
> Add support for route53 in the us-isob-east-1 region

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/operator_test.go
After attempting to use random as the default algorithm and subsequently
reverting, we discovered that reducing haproxy's weight to 1 for backends
with a single service significantly reduces the memory overhead of
the random balance algorithm and provides the same exactly functionality.
We are now turning back on random again since we have mitigated the memory
overhead issue.
> NE-825: Update router to use random balancing algorithm once again

- Makefile
- hack/verify-e2e-test-all-presence.sh
- test/e2e/all_test.go
- test/e2e/canary_test.go
- test/e2e/certificate_publisher_test.go
- test/e2e/checkinterval_test.go
- test/e2e/client_tls_test.go
- test/e2e/forwarded_header_policy_test.go
- test/e2e/haproxy_timeouts_test.go
- test/e2e/hsts_policy_test.go
- test/e2e/http_header_buffer_test.go
- test/e2e/http_header_name_case_adjustment_test.go
- test/e2e/maxconn_test.go
- test/e2e/operator_test.go
- test/e2e/router_compression_test.go
- test/e2e/util.go
This PR changes the entry point for the e2e test to the new function `TestAll`.
The new test/e2e/`TestAll` function groups tests that can be run in parallel and those that must run in series via two overarching sub-tests. The new `TestAll` function guarantees consistent ordering of all e2e tests; serial tests will not start until the parallel tests run to completion. Parallel tests are those that do not mutate the ingressconfig object, the default ingress controller, the infrastructure object, default certificates, et al. Those tests that stand up a private ingress controller, for example, are deemed to be self-contained and are grouped into the parallel set. Each test that can run in parallel must call `t.Parallel()`.
- All tests can be run via `make test-e2e`. 
- The set of all serial …
> Bug 2080379: Group all e2e tests as parallel or serial

- pkg/dns/azure/client/client.go
- pkg/dns/azure/dns.go
- pkg/operator/controller/dns/controller.go
The installer adds a cluster tag to the api.* and the api-int.*
records during creation and uses that tag to identify the dns
records that belong to the cluster and delete them. Adding the
cluster tag to the *.apps domain record to be able to identify
it during destroy.
> Bug 2055601: Add cluster tag to *.apps domain record

- test/e2e/all_test.go
- test/e2e/operator_test.go
Adding a simple e2e for BZ2075671 (that was already closed) to validate that the ingress operator's cache isn't including all objects.
> Bug 2075671: Add a e2e test that verifies the ingress operator's cache doesn't include everything

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
OVN-Kubernetes in OpenShift 4.9 and earlier does not support `externalTrafficPolicy: Local`, and specifying it is reported to result in imbalanced traffic for some users.  This change checks the cluster network type and sets `externalTrafficPolicy: Cluster` on the LoadBalancer-type service that the operator creates for ingress if the network type is "OVN-Kubernetes".
* `pkg/operator/controller/ingress/controller.go` (`ensureIngressController`): Pass the network config to `ensureLoadBalancerService` and `syncIngressControllerStatus`.
* `pkg/operator/controller/ingress/load_balancer_service.go` (`ensureLoadBalancerService`, `loadBalancerServiceIsUpgradeable`): Add a parameter for the network config.  Pass the network type from the network config to `desiredLoadBalancerService`. …
> Bug 2079517: Use externalTrafficPolicy: Cluster with OVN

- test/e2e/haproxy_timeouts_test.go
Adjust both TestHAProxyTimeouts and TestHAProxyTimeoutsRejection to search for their timeout values explicitly, rather than finding all timeouts of a particular type. In order to make it more likely that the test is finding the correct line, also use more unique timeout values in TestHAProxyTimeouts
Also fix the output of stderr in these tests when they fail
> Bug 2094962: Fix flakey logic in haproxy timeout tests

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
Check whether the ingresscontroller's `status.endpointPublishingStrategy.hostNetwork` field is nil before trying to dereference it.
Before this change, the operator would crash-loop with a nil pointer dereference if the cluster had been upgraded from an earlier version of OpenShift where the cluster had had an ingresscontroller with `status.endpointPublishingStrategy.type` set to "HostNetwork".
Follow-up to #694.
* `pkg/operator/controller/ingress/deployment.go` (`desiredRouterDeployment`): Check whether the ingresscontroller's `status.endpointPublishingStrategy.hostNetwork` field is nil before trying to dereference it.
* `pkg/operator/controller/ingress/deployment_test.go` (`TestDesiredRouterDeploymentHostNetworkNil`): New test.  Verify that `desiredRouterDeployment` behaves correctly …
> Bug 2095229: desiredRouterDeployment: Check for nil hostNetwork

- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
Fix `loadBalancerServiceAnnotationsChanged` to use the provided `annotations` argument when updating annotations.  Before this change, `loadBalancerServiceAnnotationsChanged` used the `annotations` argument when checking whether annotations had changed, but then it used `managedLoadBalancerServiceAnnotations` when setting the annotations in the updated service object.
When checking whether the service is upgradeable for the purpose of setting the ingresscontroller's "Upgradeable" status condition, `loadBalancerServiceTagsModified` calls `loadBalancerServiceAnnotationsChanged` with an `annotations` argument that includes the "service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags" annotation key, which is not in `managedLoadBalancerServiceAnnotations`.  As a result, …
> Bug 2097555: Fix loadBalancerServiceAnnotationsChanged check and update

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/router_status.go
- pkg/operator/controller/ingress/status.go
- test/e2e/all_test.go
- test/e2e/operator_test.go
- test/e2e/router_status_test.go
Updates for fixing stale route status which is impacting various operations such as sharding and ingress operator status.
> Bug 1944851: Clear route status when an ingress controller is deleted or a route is un-admitted

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/controller_test.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/dns.go
- pkg/operator/controller/ingress/dns_test.go
- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
- test/e2e/all_test.go
- test/e2e/domain_not_matching_base_test.go
This change implements a check for ingresscontrollers with a spec.domain that does not match the spec.baseDomain of the cluster DNS config. As a result of this check, operator does not create DNS records and sets `DNSManaged` condition to `False` for the respective ingresscontroller. 
- `pkg/operator/controller/ingress/controller.go`: `platformStatus` was being calculated in many different functions before. With this change, it is only calculated once in controller.go and passed to the other functions as an argument. It also uses `manageDNSForDomain` function while admitting the ingresscontroller to emit a warning event.
- `pkg/operator/controller/ingress/controller_test.go`: This updates the tests to use `platformStatus` instead of `infraConfig`.
- …
> Bug 2041616: Do not create DNS records for IngressControllers with domain not matching baseDomain

- test/e2e/haproxy_timeouts_test.go
Adjust both TestHAProxyTimeouts and TestHAProxyTimeoutsRejection to
search for their timeout values explicitly, rather than finding all
timeouts of a particular type. In order to make it more likely that
the test is finding the correct line, also use more unique timeout
values in TestHAProxyTimeouts
---
This is a manual cherry-pick of #775.
> Bug 2100630: Fix flakey logic in haproxy timeout tests

- test/e2e/operator_test.go
Add simple debug logic because @frobware and I saw a flake for TestIngressOperatorCacheIsNotGlobal. We need to log the condition to help us understand why the test is failing.
> Bug 2086887: Add better debug logging to TestIngressOperatorCacheIsNotGlobal to help debug flakes

- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
This is a manual cherry-pick of #783.  #707 introduced a conflict that required resolution.  
Fix `loadBalancerServiceAnnotationsChanged` to use the provided `annotations` argument when updating annotations.  Before this change, `loadBalancerServiceAnnotationsChanged` used the `annotations` argument when checking whether annotations had changed, but then it used `managedLoadBalancerServiceAnnotations` when setting the annotations in the updated service object.
When checking whether the service is upgradeable for the purpose of setting the ingresscontroller's "Upgradeable" status condition, `loadBalancerServiceTagsModified` calls `loadBalancerServiceAnnotationsChanged` with an `annotations` argument that includes the "service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags" …
> [release-4.10] Bug 2097735: Fix loadBalancerServiceAnnotationsChanged check and update

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/controller_test.go
This is a manual cherry-pick of #681 and #691.  #582 introduced conflicts that required resolution.  
---
Refactor the update logic in `setDefaultPublishingStrategy`.  
* `pkg/operator/controller/ingress/controller.go` (`setDefaultPublishingStrategy`): Use a switch statement for the update logic so that the logic only looks at parameters related to the selected endpoint publishing strategy type.
Fix the update logic in `setDefaultPublishingStrategy` so that updates are properly handled when `status.endpointPublishingStrategy.hostNetwork` or `status.endpointPublishingStrategy.nodePort` is null.
Before OpenShift 4.8, the IngressController API did not have any fields under the `status.endpointPublishingStrategy.hostNetwork` and `status.endpointPublishingStrategy.nodePort` fields.  As result, …
> [release-4.9] Bug 2084336: Fix enabling PROXY protocol on an upgraded cluster

- pkg/operator/controller/ingress/router_status.go
This is a follow up fix to https://github.com/openshift/cluster-ingress-operator/pull/724 which resolves a race condition caused using the cache for determining if the router deployment is still rolling out. The cache says it isn't rolling out immediately after it started rolling out.
> Bug 2101878: Fix route status clearing race condition caused by using the cache

- pkg/operator/controller/ingress/router_status.go
I thought I fixed https://bugzilla.redhat.com/show_bug.cgi?id=2101878 with https://github.com/openshift/cluster-ingress-operator/pull/794, but it failed to pass QA. I must have gotten frustratingly lucky with testing...
Upon a more detailed investigation, I found that the check in `isRouterDeploymentRolloutComplete` of `deployment.Status.Replicas != deployment.Status.UpdatedReplicas` is sometimes prematurely successful due to another race condition. The cluster-ingress-operator reconcilation sometimes happens quicker than K8S can start the router deployment rollout; though it appears that `metadata.Generation` was incremented by 1 while `Status.ObservedGeneration` was untouched.
Therefore, this PR adds a check for generation id to validate we don't check rollout status prematurely.
> Bug 2101878: Fix another issue with route status clearing race condition caused by not validating generation id

- test/e2e/util.go
This fixes the e2e breakage introduced with the recent adjustment of the default security policy.
Signed-off-by: Thejas N <thn@redhat.com>
> OCPBUGS-368: Fix e2e tests for pod security violations

- .github/ISSUE_TEMPLATE/config.yml
- README.md
Update Bugzilla links that reference the "Routing" component" to instead use the "Networking" component and "router" subcomponent.
* `.github/ISSUE_TEMPLATE/config.yml`:
* `README.md`: Update Bugzilla links.
> DPP-10860: Update Bugzilla links to "Networking" component

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/controller_test.go
This is a manual cherry-pick of #681 and #691.  #582 introduced conflicts that required resolution.  
---
Refactor the update logic in `setDefaultPublishingStrategy`.  
* `pkg/operator/controller/ingress/controller.go` (`setDefaultPublishingStrategy`): Use a switch statement for the update logic so that the logic only looks at parameters related to the selected endpoint publishing strategy type.
Fix the update logic in `setDefaultPublishingStrategy` so that updates are properly handled when `status.endpointPublishingStrategy.hostNetwork` or `status.endpointPublishingStrategy.nodePort` is null.
Before OpenShift 4.8, the IngressController API did not have any fields under the `status.endpointPublishingStrategy.hostNetwork` and `status.endpointPublishingStrategy.nodePort` fields.  As result, …
> [release-4.8] Bug 2084337: Fix enabling PROXY protocol on an upgraded cluster

- test/e2e/canary_test.go
Specify a low-privileged security context for the curl pod that the `TestCanaryRoute` test creates so as not to run afoul of pod security constraints.
* `test/e2e/canary_test.go` (`buildCanaryCurlPod`): Specify a low-privileged security context.
> OCPBUGS-1049: test/e2e: Fix TestCanaryRoute security context

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
When a router deployment the ingress controller is rolling out, set progressing=true in the cluster operator status with a message.
> Bug 2066560: Make ingress clusteroperator progressing=true when router deployment is rolling out

- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- pkg/operator/controller/ingress/nodeport_service.go
- test/e2e/operator_test.go
This is an manual cherry-pick of https://github.com/openshift/cluster-ingress-operator/pull/707 due to merge conflicts for the release-4.10 branch.
Merge Conflicts:
[gspence@gspence cluster-ingress-operator]$ git cherry-pick dba837a8b5314a3baa8167554f951bbb6f458c1e
```
Auto-merging test/e2e/operator_test.go
CONFLICT (content): Merge conflict in test/e2e/operator_test.go
Auto-merging pkg/operator/controller/ingress/load_balancer_service_test.go
CONFLICT (content): Merge conflict in pkg/operator/controller/ingress/load_balancer_service_test.go
Auto-merging pkg/operator/controller/ingress/load_balancer_service.go
```
**test/e2e/operator_test.go:**
- `TestTunableRouterKubeletProbesForDefaultIngressController` and `TestTunableRouterKubeletProbesForCustomIngressController` moved/removed while I …
> [release-4.10] BUG 2094051: Fix removing custom created service in openshift-ingress with same naming convention

- pkg/operator/controller/configurable-route/controller.go
- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/controller_test.go
- pkg/operator/controller/ingress/deployment_test.go
- pkg/operator/controller/ingress/load_balancer_service.go
- test/e2e/all_test.go
- test/e2e/checkinterval_test.go
- test/e2e/operator_test.go
- test/e2e/reloadinterval_test.go
As an user/admin, I want to switch an OCP Ingress from an AWS Classic Load Balancer to AWS Network Load Balancer. I should be able to do this without having to delete and recreate the IngressController object.
Using this fix one can update the ingress controller object with change of LB type details and get the LB service reflected with the necessary changes without the need for recreation.
Fixes https://issues.redhat.com/browse/NE-865
`pkg/operator/controller/configurable-route/controller.go` We need to mention the key or an error is thrown.
`pkg/operator/controller/ingress/controller.go` Logic added for setting the right endpoint publishing strategy while switching from ELB to NLB or vice-versa.
`pkg/operator/controller/ingress/controller_test.go` Unit tests for switching between NLB …
> Enable switching of AWS CLB to NLB without deletion of IngressController object.

- pkg/operator/controller/dns/controller.go
- pkg/operator/controller/dns/controller_test.go
- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/controller_test.go
- pkg/operator/controller/ingress/dns.go
- pkg/operator/controller/ingress/dns_test.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
- test/e2e/all_test.go
- test/e2e/domain_not_matching_base_test.go
- test/e2e/forwarded_header_policy_test.go
- test/e2e/http_header_buffer_test.go
- test/e2e/http_header_name_case_adjustment_test.go
- test/e2e/operator_test.go
- test/e2e/unmanaged_dns_test.go
- test/e2e/util_test.go
Add `dnsManagementPolicy` option to ingresscontrollers
---
- `pkg/operator/controller/dns/controller.go` 
- Create DNS provider based on `dnsManagementPolicy` on `DNSRecord` CR.
- Add sanitize function for purging deprecated fields on DNS record status.
- Refactor `publishRecordToZones()`
- `pkg/operator/controller/ingress/controller.go` - Reconcile changes made to `dnsManagementPolicy` on ingress spec.
- `pkg/operator/controller/ingress/dns.go` 
- Create desired `DNSRecord` with `dnsManagementPolicy` derived from ingresscontroller status.
- Converge domain mismatch check with `UmanagedDNS` policy. 
- `pkg/operator/controller/ingress/status.go` - Update status of types `DNSManaged` and `DNSReady`.
- Renamed `test/e2e/util.go` -> `test/e2e/util_test.go` to allow `gopls` to index …
> NE-568: Add dnsManagementPolicy option to ingresscontrollers

- Makefile
I am updating with `CGO_ENABLED=1` per discussion/debugging of @miheer 
I've asked @miheer and @manojnkumar to review.
We are currently verifying with fips enabled on ppc64le.
Signed-off-by: Paul Bastide <pbastide@redhat.com>
> Bug 2107462: Update CGO_ENABLED=1

- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
Added nil check for service object which without causes the ingress operator to panic when using ingress.operator.openshift.io/auto-delete-load-balancer annotation and changing scope of loadbalancer from external to internal.
- `pkg/operator/controller/ingress/status.go`: Add nil check for `computeAllowedSourceRanges`
- `pkg/operator/controller/ingress/status_test.go`: Add unit test for `computeAllowedSourceRanges`
> OCPBUGS-2334: Added nil check for service object on load balancer scope change

- test/e2e/reloadinterval_test.go
OCPBUGS-2429: Fix TestReloadInterval min value test cases to 1s and fix race condition in which it passes as a false positive by forcing the ingress operator to recreated the router deployment instead of waiting on the ingress operator to report Available.
- `test/e2e/reloadinterval_test.go`: Add deletion of router deployment to trigger reconcile and fix min value test cases
> OCPBUGS-2429: Fix TestReloadInterval min value test cases and race conditions

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/controller_test.go
- pkg/operator/operator.go
- test/e2e/all_test.go
- test/e2e/operator_test.go
**Note:** Cloned from https://github.com/openshift/cluster-ingress-operator/pull/798 so that I could modify.
The cluster ingress config object can now specify the AWS ELB type that was specified when installing the cluster. The ingress operator will refer to this object whenever someone deletes the default ingresscontroller and the
operator has to recreate it. Before this commit, the operator would always set the default ELB type
(Classic ELB) when creating the default ingresscontroller. Fixes https://issues.redhat.com/browse/NE-975
- `pkg/operator/operator.go`: Check if infrastructure object was set with the LB type "NLB" and create the ingresscontroller accordingly.
- `pkg/operator/ingress/controller.go`: setDefaultPublishingStrategy refactoring. Introduce a new …
> NE-975: Use ingress config to set default LB type on AWS

- test/e2e/unmanaged_dns_test.go
- test/e2e/util_test.go
OCPBUGS-2493: Fix TestUnmanagedDNSToManagedDNSInternalIngressController E2E flake
`test/e2e/unmanaged_dns_test.go`:
- Fixed service deletion race condition by ensuring loadbalancer service changed
- Fixed check for IsServiceInternal which was actually checking for internal
when should have been checking for external
- Fixed IsServiceInternal using outdated service object
`test/e2e/util_test.go`:
- Add HTTP responce body close in waitForHTTPClientCondition (the main issue)
- Increased timeout to 10 minutes for verifyInternalIngressController and verifyExternalIngressController
- Added curl pod restart in case of failure to verifyInternalIngressController
- Added wait for DNS Resolution in waitForHTTPClientCondition for debuggability
> OCPBUGS-2493: Fix TestUnmanagedDNSToManagedDNSInternal E2E test race conditions

- test/e2e/router_compression_test.go
Fix a nil-pointer dereference in the `getHttpHeaders` helper for `TestRouterCompressionOperation`.
Follow-up to #679.
* `test/e2e/router_compression_test.go` (`getHttpHeaders`): Don't dereference the response value from `client.Do` if it returned a non-nil error value.
> OCPBUGS-2435: TestRouterCompressionOperation: Nil-pointer fix

- test/e2e/haproxy_timeouts_test.go
Adjust both TestHAProxyTimeouts and TestHAProxyTimeoutsRejection to search for their timeout values explicitly, rather than finding all timeouts of a particular type. In order to make it more likely that the test is finding the correct line, also use more unique timeout values in TestHAProxyTimeouts
Also fix the output of stderr in these tests when they fail
---
This is a manual cherry-pick of #775
> [release-4.9] Bug 2100631: Fix flakey logic in haproxy timeout tests

- .ci-operator.yaml
- Dockerfile
- pkg/manifests/bindata.go
- pkg/operator/controller/certificate/controller.go
- pkg/util/aws/shared_credentials_file.go
- test/e2e/maxconn_test.go
Reconciling with https://github.com/openshift/ocp-build-data/tree/b44f15ec9e84d1831eac81f8c757b3bed985dbeb/images/ose-cluster-ingress-operator.yml
This PR is based on #802 but additionally includes changes to the formatting of `pkg/manifests/bindata.go` that result from using the updated Go 1.19 builder image, as well as formatting changes to several other files to appease gofmt.  Including these changes is necessary in order for the verify job to pass.
> Updating ose-cluster-ingress-operator images to be consistent with ART

- pkg/operator/controller/crl/controller.go
- pkg/operator/controller/crl/crl_configmap.go
Determine when the next CRL needs to be updated based on the CRL's nextUpdate field. Re-reconcile at that time in order to pick up the updated CRL.
> Bug 2117524: Update CRLs when they expire

- pkg/operator/operator.go
bdb5b649635df239379b2a4d5120af36af784964 introduced a log call with
formatting that doesn't work, resulting in a log line that looks like this:
```
2022-06-22T10:04:12.616Z        INFO    operator.init   operator/operator.go:236        Patched %q ingress config defaultPlacement status to %q {"cluster": "Workers"}
```
This should fix it... It's very unlikely customers will run into this
fix because it will only happen in <=4.10 to >=4.12 upgrades, unless we
backport this. But I'm not sure it's worth the effort of backporting
> OCPBUGS-1807: Fix bad `handleSingleNode4Dot11Upgrade` log message

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- pkg/operator/controller/names.go
Adding node affinity rule to router deployement that will not allow
router to run on remote worker node (node with custom role label)
> OPNET-133: Support remote worker

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/metrics_test.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
Remove the `PodsScheduled` status condition on IngressController objects, and report the information that `PodsScheduled` reported instead in the `DeploymentReplicasMinAvailable` status condition's message when its status is "False".
Before this change, the `PodsScheduled` status condition could erroneously signal that there was a problem when some misscheduled pods existed even if there were enough correctly scheduled and available pods.
The `PodsScheduled` status condition was added in order to provide diagnostic information when there was a problem.  That is, `PodsScheduled` was intended to indicate *why* there was a problem, not *whether* there was a problem. The `DeploymentReplicasMinAvailable` status condition definitively indicates *whether* there is a problem, and its status …
> OCPBUGS-434: Absorb PodsScheduled condition into MinAvailable

- pkg/operator/controller/ingressclass/ingressclass.go
updateIngressClass: Fix log message
* pkg/operator/controller/ingressclass/ingressclass.go
(updateIngressClass): Log when the update succeeds, not when it fails.
> OCPBUGS-6700: updateIngressClass: Fix log message

- pkg/operator/controller/ingress/nodeport_service.go
ensureNodePortService reports error with a loadbalancer-type service name, not a nodeport-type service name.
* pkg/operator/controller/ingress/nodeport_service.go
(ensureNodePortService): Report the correct name for a conflicting service.
> OCPBUGS-6698: Fix conflict error message in ensureNodePortService

- pkg/operator/controller/ingressclass/ingressclass.go
- pkg/operator/controller/ingressclass/ingressclass_test.go
Specify spec.parameters.scope on ingressclasses that the operator creates.
Before this commit, the update logic would try to revert the default value that the API set for an ingressclass's scope field.
* pkg/operator/controller/ingressclass/ingressclass.go (desiredIngressClass): Specify spec.parameters.scope with the default value: "Cluster".
* pkg/operator/controller/ingressclass/ingressclass_test.go (Test_desiredIngressClass): Update test to expect spec.parameters.scope to be set.
> OCPBUGS-6701: Avoid spurious updates for scope in IngressClass

- pkg/dns/alibaba/dns_test.go
Test_getRR: Fix typo: "excepted" → "expected"
* pkg/dns/alibaba/dns_test.go (Test_getRR): Replace "excepted" with "expected" in test case struct definition.
> NE-1186: Test_getRR: Fix typo: "excepted" → "expected"

- pkg/operator/controller/configurable-route/controller.go
Replace `source.NewKindWithCache(&foo{}, mgr.GetCache())` with `&source.Kind{Type: &foo{}}` in the configurable-route controller.
Using `source.NewKindWithCache()` is needlessly complicated since this controller uses the default cache anyway.  Moreover, using `source.NewKindWithCache()` causes controller-runtime's logging to be more noisy (see https://github.com/kubernetes-sigs/controller-runtime/pull/2057).  Before this PR, the operator emitted log messages like the following on startup:
2022-11-23T08:47:35.646-0600    INFO    operator.init   controller/controller.go:241    Starting EventSource    {"controller": "configurable_route_controller", "source": "&{{%!s(*v1.Role=&{{ } {      0 {{0 0 <nil>}} <nil> <nil> map[] map[] [] [] []} []}) …
> OCPBUGS-4054: configurable-route: Don't use NewKindWithCache

- pkg/operator/controller/sync-http-error-code-configmap/controller_test.go
Test_desiredHttpErrorCodeConfigMap: Kill dead code
* pkg/operator/controller/sync-http-error-code-configmap/controller_test.go
(Test_desiredHttpErrorCodeConfigMap): Delete some dead code.
[NE-1185](https://issues.redhat.com//browse/NE-1185): Test_desiredHttpErrorCodeConfigMap: Fix format
* pkg/operator/controller/sync-http-error-code-configmap/controller_test.go
(Test_desiredHttpErrorCodeConfigMap): Replace Ruby-style #{} syntax for
string interpolation with Go string formats.
> NE-1184: Test_desiredHttpErrorCodeConfigMap: Kill dead code and fix format

- test/e2e/client_tls_test.go
- test/e2e/operator_test.go
Wait for old router pods to be cleaned up before testing new mTLS config.
After updating the ingresscontroller configuration, the router deployment reports when all new pods are ready, but sometimes the pods from the older generation still haven't terminated. If those older generation pods are still marked ready when `TestClientTLS` curls an endpoint, sometimes the connections are handled by the older generation router, and that test case will fail.
This PR makes the test wait until the older generation pod(s) are completely terminated before running curl, ensuring that only the correct router pods are used.
> OCPBUGS-10846: Fix TestClientTLS flakes

- test/e2e/router_compression_test.go
Wait for old router pods to be cleaned up before proceeding with testing compression.
- `test/e2e/router_compression_test.go`: Use waitForDeploymentCompleteWithOldPodTermination
Same issue as https://github.com/openshift/cluster-ingress-operator/pull/904
> OCPBUGS-12913: Deflake TestRouterCompressionOperation

- test/e2e/operator_test.go
TestAWSELBConnectionIdleTimeout has been very flakey due to the fact that the CI test runner cluster is failing to resolve the newly created wildcard DNS Record in a reasonable time. To work around this, we switch to using ELB's hostname, which is consistently resolving and adding the "Host" header to the HTTP request.
`test/e2e/operator_test.go`: Modify TestAWSELBConnectionIdleTimeout to use ELB hostname and Host header with route hostname
WIP PR with debugging output (which helped me arrive at this solution): https://github.com/openshift/cluster-ingress-operator/pull/940
**Why it's failing:**
- It's important to note that TestAWSELBConnectionIdleTimeout is the only test where we create a new ingress controller, wait for the new wildcard DNS Record to propagate to DNS Servers in our CI …
> OCPBUGS-13810: Update TestAWSELBConnectionIdleTimeout to not use wildcard DNS record

- test/e2e/operator_test.go
This will help **debug** flakes in which `waitForIngressControllerCondition` fails, but there is no logging of status condition reasons or messages which would help with debugging.
`test/e2e/operator_test.go`: Add ingress controller status logging on `waitForIngressControllerCondition`
For OCPBUGS-13106, TestInternalLoadBalancer* and TestScopeChange GCP CI flakes, it fails because `DNSReady:False` and `LoadBalancerReady:False` are false, but doesn't provide additional information presented in the Ingress Controller Status conditions. 
This is also a general improvement that would help with future failures of `waitForIngressControllerCondition`
> OCPBUGS-13106: Add ingress controller status logging on waitForIngressControllerCondition

- pkg/operator/controller/gateway-service-dns/controller.go
- pkg/operator/controller/gateway-service-dns/controller_test.go
Before this change, in `ensureDNSRecordsForGateway` we didn't add a trailing dot to the domain before creating the dnsrecord, causing the DNS name to fail to be published on a GCP platform.
Add a trailing dot if one doesn't exist, add test to check that only one dot is added, and change expectations of other tests to check for a trailing dot in the domain name.
> OCPBUGS-15100: Create valid DNS names for Gateway API on GCP

- pkg/dns/aws/dns.go
To support Shared VPC, we split the DNS client into public and private providers, the private using the RoleARN (Account A) and the public using the default (Account B). However, the RoleARN only provides API access for Account A's Route53 service, not the ability to describe Account B's ELBs. The ingress-operator DNS Logic uses the AWS API to describe the ELBs in order to determine the Zone ID. This fix isolates the RoleARN to only be used with Route53 API services.
`pkg/dns/aws/dns.go`: Create a separate Route53 session object that uses the RoleARN when provided.
> OCPBUGS-14998: Only use RoleARN for Route53 API

- test/e2e/operator_test.go
Due to controller-runtime v0.15.0 bump and changes made in https://github.com/kubernetes-sigs/controller-runtime/pull/2317, you must set a logger for controller-runtime and client.go was not initializing the logger.
`test/e2e/operator_test.go`: Initialize controller-runtime logger in init() function
> OCPBUGS-14396: Set controller-runtime logger to a null logger for E2E

- pkg/operator/controller/gateway-service-dns/controller.go
- pkg/operator/controller/gateway-service-dns/controller_test.go
Add the trailing dot to the hostname if missing, early enough so that all references use the trailing dot.
Update hashed DNS record names in unit tests.
Addresses https://github.com/openshift/cluster-ingress-operator/pull/949/files#r1245950185
> OCPBUGS-15100: Fix previous attempt of adding a missing trailing dot to hostname

- pkg/operator/controller/gateway-service-dns/controller.go
- pkg/operator/controller/gateway-service-dns/controller_test.go
Backport of b58456ac0d60c6a749c and 8ad42fa58ec2232169bb.
Before this change, in ensureDNSRecordsForGateway we didn't add a trailing dot to the domain
before creating the dnsrecord, causing the DNS name to fail to be published on a GCP platform.
Add a trailing dot if one doesn't exist, add test to check that only one dot is added, and
change expectations of other tests to check for a trailing dot in the domain name.
> OCPBUGS-15434: [release-4.13] Fix invalid DNS name formatting for GCP

- pkg/operator/controller/ingress/poddisruptionbudget.go
- pkg/operator/controller/ingress/poddisruptionbudget_test.go
We currently set maxUnavailable as a 50% percentage for replica count < 4, and in the pod disruption budget, Kubernetes rounds up the number of Pods that may be disrupted.   With 3 pods if you set maxUnavailable to "50%", it means 2 pods may be disrupted.  We currently set it to 25% for replica count >= 4, and this changes it for replica count >= 3.
Update the test.
[Git history for PDB](https://github.com/openshift/cluster-ingress-operator/commits/master/pkg/operator/controller/ingress/poddisruptionbudget.go) shows that we went back and forth on how low to set this because some teams would want to use very small clusters and didn't care about high availability. "Pod disruption budgets cause problems for people who want to run small clusters or drain all workers at once"  
Hopefully …
> OCPBUGS-7546: Allow only 1 disruption with 3 replicas

- README.md
Follow-up to #916.
* `README.md`: Update the Bugzilla link to point instead to the Red Hat Issue Tracker.
> OCPBUGS-12790: README: Fix Bugzilla link

- manifests/00-ingress-credentials-request.yaml
Instead of requesting the "Contributor" role, request the individual permissions that the operator requires in order to manage DNS records on Azure.
* `manifests/00-ingress-credentials-request.yaml`: Replace the "Contributor" role with a list of permissions.
---
Notes for reviewers:  Per discussions on [NE-1244](https://issues.redhat.com//browse/NE-1244), this PR restricts the CredentialsRequest for Azure to a specific set of permissions.  Because of the way the e2e-azure-operator job is configured, this job doesn't actually use the precise rules or permissions that are listed in the CredentialsRequest, but the e2e-azure-manual-oidc job that was added by https://github.com/openshift/release/pull/41502 does.
> NE-1244: Use permissions instead of the "Contributor" role in Azure CredentialsRequest

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
Set `spec.template.spec.containers[*].ports[*].hostPort` on a router deployment if the deployment sets `spec.template.spec.hostNetwork` to true.
Before this change, the operator left the `hostPort` field unspecified. As a result, the API set a default value for `hostPort`.  The operator detected this as an external update and attempted to revert it.  The change in this PR prevents the operator from making these spurious updates in response to API defaulting.
* `pkg/operator/controller/ingress/deployment.go` (`desiredRouterDeployment`): Set each container port's `HostPort` to the port's `ContainerPort` value when `HostNetwork` is enabled for the deployment.
* `pkg/operator/controller/ingress/deployment_test.go` (`checkContainerPort`): Verify that `HostPort` is set to `ContainerPort` if …
> OCPBUGS-14995: desiredRouterDeployment: Set HostPort if needed

- go.mod
- go.sum
- vendor/modules.txt
- vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
- vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
- vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
Backport of https://github.com/openshift/cluster-ingress-operator/pull/913.
Upstream backport: https://github.com/kubernetes-sigs/controller-runtime/pull/2288.
> [release-4.12] OCPBUGS-13049: bump controller-runtime to fix the multi namespace cache indexing

- pkg/operator/controller/canary/controller.go
- pkg/operator/controller/canary/http.go
- pkg/operator/controller/canary/route.go
- pkg/operator/controller/canary/route_test.go
- test/e2e/canary_test.go
- test/e2e/client_tls_test.go
- test/e2e/operator_test.go
- test/e2e/router_compression_test.go
- test/e2e/util_test.go
Change `Test_desiredCanaryRoute` to check both the route's and the service's owner references, and print the correct error message if either the route or the service has an unexpected value.
Before this change, `Test_desiredCanaryRoute` checked the route's owner references but erroneously referred to the service in the failure message if the route had an unexpected value.
* `pkg/operator/controller/canary/route_test.go` (`Test_desiredCanaryRoute`): Fix checks for owner references.
* `pkg/operator/controller/canary/route_test.go` (`Test_desiredCanaryRoute`): Use `assert.Equal` and `assert.True` from the testify package.
Set `spec.subdomain` on the canary route so that the route is exposed using the respective domain of any shard that exposes the route.
Before this change, the canary route …
> OCPBUGS-16089: Set spec.subdomain on the canary route

- test/e2e/client_tls_test.go
- test/e2e/hsts_policy_test.go
- test/e2e/util_test.go
Use the "openshift/tools" image from the cluster image registry instead of using the "openshift/origin-node" image pullspec in E2E tests.
Before this change, the E2E tests were inadvertently pulling the "openshift/origin-node" image from Docker Hub and getting rate-limited.
The choice to use "openshift/tools" is based on a similar change here: https://github.com/openshift/origin/pull/24887/commits/4cbb844d1d5f3a3ac6dd08325db17b807e7129f2
Follow-up to #410 and #451.
* `test/e2e/util_test.go` (`buildEchoPod`, `buildSlowHTTPDPod`): Replace the "openshift/origin-node" image pullspec with "image-registry.openshift-image-registry.svc:5000/openshift/tools:latest".
* `test/e2e/hsts_policy_test.go` (`TestHstsPolicyWorks`): Dump events in case of test failure, using the new `dumpEventsInNamespace` …
> OCPBUGS-17359: test/e2e: Don't use openshift/origin-node

- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
When reporting the "DNSReady" status condition on an IngressController, check the status conditions for both the public zone and the private zone of the associated DNSRecord.
Before this change, only the status condition for the private zone was used to compute the "DNSReady" status condition.  If the operator failed to publish a DNS record in the public zone, this failure was not reported in the IngressController's status conditions or the "ingress" clusteroperator status conditions.
Follow-up to #641.
* `pkg/operator/controller/ingress/status.go` (`checkZoneInConfig`): Use the new `zonesMatch` helper function to check both the public zone as well as the private zone.
(`zonesMatch`): New function.  Return a Boolean value indicating whether two DNS zones match, based on their respective …
> OCPBUGS-15978: Check public DNS zone when reporting status

- test/e2e/all_test.go
- test/e2e/client_tls_test.go
- test/e2e/tuning_options_test.go
- test/e2e/util_test.go
This PR adds a new test, `TestCookieLen`, which verifies that cookies in `spec.logging.access.httpCaptureCookies` are truncated to the specified max length.
This tests the fix in openshift/router#436
> OCPBUGS-3356: E2E test for cookie length truncation

- test/e2e/client_tls_test.go
HTTP status codes will always be 3 digits if curl gets one, so only try parsing the status code if stdout from curl is 3 characters or longer.
> OCPBUGS-15900: TestMTLSWithCRLs: only try to parse HTTP status code from curl output when stdout is long enough.

- pkg/operator/controller/gatewayclass/servicemeshcontrolplane.go
Add PILOT_ENABLE_GATEWAY_API_GATEWAYCLASS_CONTROLLER=false to SMCP PILOT ENV variables to disable the GatewayClass Controller in OSSM. This will prevent OSSM from recreating the openshift-default GatewayClass.
`pkg/operator/controller/gatewayclass/servicemeshcontrolplane.go`: Add PILOT_ENABLE_GATEWAY_API_GATEWAYCLASS_CONTROLLER=false to SMCP.
> OCPBUGS-18248: Prevent GatewayClass from getting recreated

- pkg/operator/controller/route-metrics/controller.go
- pkg/operator/controller/route-metrics/controller_test.go
- test/unit/util.go
To fix OCPBUGS-3541, don't create metrics for ingress controller that are not admitted. The Ingress Operator won't add the finalizer if the Ingress Controller was not admitted. Since there is no finalizer, we can't delete any metrics that we created for the Ingress Controller upon deletion. Only adding metrics for Ingress Controllers that are admitted will correct this bug.
Furthermore, if an ingress controller is not admitted, it can't have any routes, so there isn't a large point in creating the metrics for it yet.
> OCPBUGS-3541: Don't create route metrics for ingress controllers that are not admitted

- pkg/manifests/assets/router/deployment.yaml
- pkg/operator/controller/ingress/deployment_test.go
Setting the filesystem to read only in the router container prevents it from rendering the haproxy config, and causes haproxy to be unable to start. Adding the security context constraint `readOnlyRootFilesystem: false` makes sure the security profile it is assigned does not require a read only filesystem.
> OCPBUGS-20192: Require non-readonly filesystem in router container

- test/e2e/maxconn_test.go
This commit adds a test case to verify that the maxConnections setting
can be configured with the absolute upper limit of 2000000, as defined
by the API
```sh
% oc explain ingresscontroller.spec.tuningOptions.maxConnections
KIND:     IngressController
VERSION:  operator.openshift.io/v1
FIELD:    maxConnections <integer>
DESCRIPTION:
maxConnections defines the maximum number of simultaneous
connections that can be established per HAProxy process.
Increasing this value allows each ingress controller pod to
handle more connections but at the cost of additional system
resources being consumed. Permitted values are: empty, 0, -1, and
the range 2000-2000000.
```
This change requires https://github.com/openshift/router/pull/527.
Fixes: https://issues.redhat.com/browse/OCPBUGS-21803.
> OCPBUGS-21803: test/e2e: Add test case for 2000000 maxConnections

- test/e2e/client_tls_test.go
- test/e2e/hsts_policy_test.go
- test/e2e/util_test.go
Use the "openshift/tools" image from the cluster image registry instead of using the "openshift/origin-node" image pullspec in E2E tests.
Before this change, the E2E tests were inadvertently pulling the "openshift/origin-node" image from Docker Hub and getting rate-limited.
The choice to use "openshift/tools" is based on a similar change here: https://github.com/openshift/origin/pull/24887/commits/4cbb844d1d5f3a3ac6dd08325db17b807e7129f2
Follow-up to #410 and #451.
* `test/e2e/util_test.go` (`buildEchoPod`, `buildSlowHTTPDPod`): Replace the "openshift/origin-node" image pullspec with "image-registry.openshift-image-registry.svc:5000/openshift/tools:latest".
* `test/e2e/hsts_policy_test.go` (`TestHstsPolicyWorks`): Dump events in case of test failure, using the new `dumpEventsInNamespace` …
> [release-4.13] OCPBUGS-22402: test/e2e: Don't use openshift/origin-node

- test/e2e/client_tls_test.go
- test/e2e/hsts_policy_test.go
- test/e2e/util_test.go
Use the "openshift/tools" image from the cluster image registry instead of using the "openshift/origin-node" image pullspec in E2E tests.
Before this change, the E2E tests were inadvertently pulling the "openshift/origin-node" image from Docker Hub and getting rate-limited.
The choice to use "openshift/tools" is based on a similar change here: https://github.com/openshift/origin/pull/24887/commits/4cbb844d1d5f3a3ac6dd08325db17b807e7129f2
Follow-up to #410 and #451.
* `test/e2e/util_test.go` (`buildEchoPod`, `buildSlowHTTPDPod`): Replace the "openshift/origin-node" image pullspec with "image-registry.openshift-image-registry.svc:5000/openshift/tools:latest".
* `test/e2e/hsts_policy_test.go` (`TestHstsPolicyWorks`): Dump events in case of test failure, using the new `dumpEventsInNamespace` …
> [release-4.12] OCPBUGS-22432: test/e2e: Don't use openshift/origin-node

- test/e2e/client_tls_test.go
- test/e2e/hsts_policy_test.go
- test/e2e/util.go
Use the "openshift/tools" image from the cluster image registry instead of using the "openshift/origin-node" image pullspec in E2E tests.
Before this change, the E2E tests were inadvertently pulling the "openshift/origin-node" image from Docker Hub and getting rate-limited.
The choice to use "openshift/tools" is based on a similar change here: https://github.com/openshift/origin/pull/24887/commits/4cbb844d1d5f3a3ac6dd08325db17b807e7129f2
Follow-up to #410 and #451.
* `test/e2e/util_test.go` (`buildEchoPod`, `buildSlowHTTPDPod`): Replace the "openshift/origin-node" image pullspec with "image-registry.openshift-image-registry.svc:5000/openshift/tools:latest".
* `test/e2e/hsts_policy_test.go` (`TestHstsPolicyWorks`): Dump events in case of test failure, using the new `dumpEventsInNamespace` …
> [release-4.11] OCPBUGS-22433: test/e2e: Don't use openshift/origin-node

- pkg/operator/controller/clientca-configmap/controller.go
- pkg/operator/controller/clientca-configmap/controller_test.go
- pkg/operator/operator.go
Don't add the clientca-configmap finalizer to an IngressController if it is marked for deletion.
Before this change, the clientca-configmap controller would attempt to add (or re-add) its finalizer to an IngressController that had been marked for deletion.  This attempt resulted in the following error from the API:
IngressController.operator.openshift.io "test-client-ca-configmap" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{"ingresscontroller.operator.openshift.io/finalizer-clientca-configmap"}
The controller would retry adding the finalizer repeatedly, causing the same error to be repeatedly logged until the deletion completed.
* `pkg/operator/controller/clientca-configmap/controller.go` …
> OCPBUGS-14994: Don't add clientca-configmap finalizer if deleting

- pkg/operator/controller/monitoring-dashboard/controller.go
- pkg/operator/controller/monitoring-dashboard/dashboard.json
- pkg/operator/controller/monitoring-dashboard/monitoring_dashboard.go
- pkg/operator/controller/monitoring-dashboard/monitoring_dashboard_test.go
- pkg/operator/operator.go
- test/e2e/all_test.go
- test/e2e/dashboard_test.go
This PR add a new controller to manage a configmap to deploy monitoring dashboard.
The configmap is deployed as long as the controlPlaneTopology is not set to external.
The dashboard itself is there as an example but I wanted to open the PR to start getting review on the controller part.
I am going to look more precisely about what would be the most valuable to display in the dashboard.
> NETOBSERV-1052: Add monitoring dashboard controller to create dashboard configmap

- manifests/00-ingress-credentials-request.yaml
Add capability annotations to cloud credentials requests
> OCPVE-780: annotate credentials request manifests

- test/e2e/operator_test.go
- test/e2e/unmanaged_dns_test.go
Skip CI for scope change until OCPBUGS-24044 is resolved.
test/e2e/unmanaged_dns_test.go
- TestUnmanagedDNSToManagedDNSInternalIngressController
- TestUnmanagedDNSToManagedDNSInternalIngressController
test/e2e/operator_test.go
- TestScopeChange
> OCPBUGS-24531: Skip CI for scope change until OCPBUGS-24044 is resolved

- test/e2e/operator_test.go
- test/e2e/unmanaged_dns_test.go
This reverts commit 7a44e03198ea8efd27ee92ecc41aefa405ef2087, in PR #1007, reversing changes made to 9a872878deb0421105da88c9fe25b1079aa2f2ea, and adds changes to skip tests that will fail for Azure and GCP (only) until OCPBUGS-24044 is resolved.
> OCPBUGS-24531: Revert "Merge pull request #1007 from candita/OCPBUGS-24531-SkipScopeChangeTest" and add changes to skip test only for Azure and GCP

- test/e2e/operator_test.go
- test/e2e/unmanaged_dns_test.go
This reverts commit fe6809626569beeec32c561c9a5fe6a1f249b65d.
> OCPBUGS-24531: Revert " OCPBUGS-24531 Skip CI for scope change until OCPBUGS-24044 is resolved"

- manifests/00-ingress-credentials-request.yaml
Instead of using a predefined role in the cloud credentials request for GCP, enumerate permissions explicitly.
The Google Cloud DNS API permissions are documented here: <https://cloud.google.com/dns/docs/access-control>
Each method in the Cloud DNS API has a corresponding permission.  The operator's DNS provider implementation for GCP only calls two methods:
- `dns.changes.create`
- `dns.resourcerecordsets.list`
These methods require the following permissions:
- `dns.changes.create`
- `dns.resourceRecordSets.create`
- `dns.resourceRecordSets.update`
- `dns.resourceRecordSets.delete`
- `dns.resourceRecordSets.list`
This PR replaces the `dns.admin` role with these permissions in the credentials request.
* `manifests/00-ingress-credentials-request.yaml`: Replace the `roles/dns.admin` …
> CCO-249: Replace GCP role with explicit permissions

- manifests/00-ingress-credentials-request.yaml
This is a manual cherry-pick of #844, which merged as a feature and therefore cannot be automatically cherry-picked.
--
Instead of using a predefined role in the cloud credentials request for GCP, enumerate permissions explicitly.
The Google Cloud DNS API permissions are documented here: <https://cloud.google.com/dns/docs/access-control>
Each method in the Cloud DNS API has a corresponding permission.  The operator's DNS provider implementation for GCP only calls two methods:
- `dns.changes.create`
- `dns.resourcerecordsets.list`
These methods require the following permissions:
- `dns.changes.create`
- `dns.resourceRecordSets.create`
- `dns.resourceRecordSets.update`
- `dns.resourceRecordSets.delete`
- `dns.resourceRecordSets.list`
This PR replaces the `dns.admin` role with these …
> OCPBUGS-26544: Replace GCP role with explicit permissions

- go.mod
> NE-1490: update to go v1.20

- manifests/02-deployment-ibm-cloud-managed.yaml
- manifests/02-deployment.yaml
All openshift operators must include FallbackToLogsOnError to ease debugging.
> OCPBUGS-28230: add FallbackToLogsOnError for easier debugging

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- pkg/operator/operator.go
Use `RouterExternalCertificate` feature gate and add `ROUTER_ENABLE_EXTERNAL_CERTIFICATE` env var to the router pod based on the feature gate according to the EP https://github.com/openshift/enhancements/pull/1307.
> CFE-987: Use RouterExternalCertificate feature gate for adding ROUTER_ENABLE_EXTERNAL_CERTIFICATE env var to the router pods

- test/e2e/operator_test.go
Remove the `t.Parallel()` call inside `TestHostNetworkPortBinding`.  The test is listed in `TestAll` as a serial test, but the test itself calls `t.Parallel()`, which causes it to run in parallel with other serial tests.  This likely causes occasional failures of the test in CI.
> OCPBUGS-30091: TestHostNetworkPortBinding: Delete t.Parallel()

- pkg/operator/controller/canary/controller.go
- pkg/operator/controller/canary/controller_test.go
The ingress canary sets the status condition `CanaryChecksSucceeding` to false when 5 or more successive checks fail. With this PR, the associated status message will include the error messages from the ~~5~~ 3 most recent failures
> OCPBUGS-3522: Include recent errors in canary checks fail

- test/e2e/client_tls_test.go
The latest tag for `quay.io/centos7/httpd-24-centos7` is no longer available, but the same image is accessible with the centos7 tag. In the long term, a different httpd image should probably be used, but this change should get tests passing.
> OCPBUGS-31722: Use centos7 tag for quay.io/centos7/httpd-24-centos7 image

- .ci-operator.yaml
- go.mod
- go.sum
Update go.mod and .ci-operator.yaml to sync with ART 4.16.  Generate go.sum.
Replaces https://github.com/openshift/cluster-ingress-operator/pull/1033
> OCPBUGS-30834: Update to go 1.21

- manifests/00-ingress-credentials-request.yaml
xref: OCPBUGS-25193
When installing a private cluster on azure, the customer supplies a
custom resource group for their existing vnet to which the ingress
operator (among others) must have access to. From within this custom
vnet, the operator must be able to read and join the various existing
subnets that the customer has supplied.
see also: https://github.com/openshift/cloud-credential-operator/pull/682
> OCPBUGS-25193: Add vnet subnet read and join permission for azure

- manifests/00-cluster-role.yaml
- manifests/00-ingress-credentials-request.yaml
- manifests/00-namespace.yaml
- manifests/0000_90_ingress-operator_00_prometheusrole.yaml
- manifests/0000_90_ingress-operator_01_prometheusrolebinding.yaml
- manifests/0000_90_ingress-operator_02_servicemonitor.yaml
- manifests/0000_90_ingress-operator_03_prometheusrules.yaml
- manifests/01-cluster-role-binding.yaml
- manifests/01-role-binding.yaml
- manifests/01-role.yaml
- manifests/01-service-account.yaml
- manifests/01-service.yaml
- manifests/01-trusted-ca-configmap.yaml
- manifests/02-deployment-ibm-cloud-managed.yaml
- manifests/02-deployment.yaml
- manifests/03-cluster-operator.yaml
- profile-patches/ibm-cloud-managed/02-deployment.yaml.patch
This PR adds the `Ingress` capability annotation to all the resources related to the cluster-ingress-operator: CRDS, Deployment, RBAC, CredentialsRequests. 
Enhancement Proposal: https://github.com/openshift/enhancements/pull/1415.
PR which added the `Ingress` capability to the API: https://github.com/openshift/api/pull/1724.
> NE-1317: manifests - add ingress capability annotation

- manifests/00-cluster-role.yaml
Before this change, cluster-ingress-operator did not have permission to update `spec.host` or `spec.subdomain` on an existing route as the operator's serviceaccount did not have the necessary "routes/custom-host" permission.  #965 added logic to the operator to clear `spec.host` and instead set `spec.subdomain`, but without the required permission, the update would fail with the following error message:
ERROR   operator.init   controller/controller.go:265    Reconciler error {"controller": "canary_controller", "object": {"name":"default","namespace":"openshift-ingress-operator"}, "namespace": "openshift-ingress-operator", "name": "default", "reconcileID": "463061e3-93a1-4067-802e-03e3f1f8cdd0", "error": "failed to ensure canary route: failed to update canary route …
> OCPBUGS-32887: Allow operator to update Route spec.subdomain

- pkg/manifests/assets/gateway-api/gateway.networking.k8s.io_gatewayclasses.yaml
- pkg/manifests/assets/gateway-api/gateway.networking.k8s.io_gateways.yaml
- pkg/manifests/assets/gateway-api/gateway.networking.k8s.io_httproutes.yaml
- pkg/manifests/assets/gateway-api/gateway.networking.k8s.io_referencegrants.yaml
- pkg/operator/controller/gatewayclass/servicemeshcontrolplane.go
OSSM 2.5 supports Istio 1.18 and therefore only Gateway API v0.6.2 CRDS. 
- Pull the new CRD yaml from upstream and update pkg/manifests/assets/gateway-api
- Update the pkg/operator/controller/gatewayclass/servicemeshcontrolplane.go to reflect changes required by OSSM 2.5.
> NE-1400: Bump to OSSM 2.5 and Gateway API v0.6.2 CRDs

- pkg/manifests/assets/router/deployment.yaml
- pkg/manifests/assets/router/service-cloud.yaml
- pkg/manifests/assets/router/service-internal.yaml
- pkg/operator/controller/canary/daemonset_test.go
- pkg/operator/controller/canary/namespace_test.go
- pkg/operator/controller/canary/route_test.go
- pkg/operator/controller/gatewayapi/crds.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- pkg/operator/controller/ingress/internal_service.go
- pkg/operator/controller/ingress/internal_service_test.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- pkg/operator/controller/ingress/monitoring_test.go
- pkg/operator/controller/ingress/namespace_test.go
- pkg/operator/controller/ingress/nodeport_service.go
- pkg/operator/controller/ingress/nodeport_service_test.go
- pkg/operator/controller/ingress/poddisruptionbudget_test.go
- pkg/operator/controller/ingressclass/ingressclass_test.go
- test/e2e/all_test.go
- test/e2e/operator_test.go
Fix `internalServiceChanged` to copy target ports from the expected service rather than preserving target ports from the current service.    Only copy `NodePort` and other fields that we want to preserve.
Before this PR, the `internalServiceChanged` function explicitly preserved the current service's ports' target ports when reconciling the service.  However, the function was intended to update the target ports if they changed.
In particular, if the current service specifies a numeric target port for the metrics port, then the operator should replace the port number with a port name so that the service uses the correct port even if the pod container's port number changes.  Without this change, updating an IngressController's `spec.endpointPublishingStrategy.hostNetwork.statsPort` API …
> OCPBUGS-23221: internalServiceChanged: Fix target port logic

- pkg/operator/controller/clientca-configmap/controller.go
- pkg/operator/controller/clientca-configmap/controller_test.go
- pkg/operator/operator.go
This is a manual cherry-pick of https://github.com/openshift/cluster-ingress-operator/pull/1063
Replaces https://github.com/openshift/cluster-ingress-operator/pull/1071
git cherry-pick 30fd7012
In this backport to 4.13, we replace time.DateTime with time.RFC3339, since time.DateTime is not available in go 1.19.
git add pkg/operator/controller/clientca-configmap/controller_test.go
git cherry-pick a6fa2b8ffb
go mod vendor
go mod tidy
make generate
make update
**clientca-configmap: Remove OperatorNamespace field**
* pkg/operator/controller/clientca-configmap/controller.go (Config):
* pkg/operator/controller/clientca-configmap/controller_test.go (Test_Reconcile):
* pkg/operator/operator.go (New): Remove unused OperatorNamespace field.
**Don't add clientca-configmap finalizer if deleting** …
> [release-4.13] OCPBUGS-34765: Don't add clientca-configmap finalizer if deleting

- go.mod
- pkg/operator/controller/clientca-configmap/controller.go
- pkg/operator/controller/clientca-configmap/controller_test.go
- pkg/operator/operator.go
This is a manual cherry-pick of https://github.com/openshift/cluster-ingress-operator/pull/1073
Replaces https://github.com/openshift/cluster-ingress-operator/pull/1078
git cherry-pick 9e7477014f6cf99
git cherry-pick d2126f8ce248539
go mod vendor
go mod tidy
make generate
make update
Modified-by: candita
Module vendoring, update go.mod
**clientca-configmap: Remove OperatorNamespace field**
* pkg/operator/controller/clientca-configmap/controller.go (Config):
* pkg/operator/controller/clientca-configmap/controller_test.go (Test_Reconcile):
* pkg/operator/operator.go (New): Remove unused OperatorNamespace field.
commit 3de9c80280762cbd53db644991a77b17a849aa6a
Author: Miciah Masters <miciah.masters@gmail.com>
Date:   Wed Jun 14 22:36:53 2023 -0400
Don't add clientca-configmap finalizer if …
> [release-4.12] OCPBUGS-35027: Don't add clientca-configmap finalizer if deleting

- go.mod
- go.sum
- pkg/manifests/assets/router/deployment.yaml
- pkg/manifests/assets/router/service-cloud.yaml
- pkg/manifests/assets/router/service-internal.yaml
- pkg/operator/controller/canary/daemonset_test.go
- pkg/operator/controller/canary/namespace_test.go
- pkg/operator/controller/canary/route_test.go
- pkg/operator/controller/gatewayapi/crds.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- pkg/operator/controller/ingress/internal_service.go
- pkg/operator/controller/ingress/internal_service_test.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- pkg/operator/controller/ingress/monitoring_test.go
- pkg/operator/controller/ingress/namespace_test.go
- pkg/operator/controller/ingress/nodeport_service.go
- pkg/operator/controller/ingress/nodeport_service_test.go
- pkg/operator/controller/ingress/poddisruptionbudget_test.go
- pkg/operator/controller/ingressclass/ingressclass_test.go
- test/e2e/all_test.go
- test/e2e/operator_test.go
- vendor/k8s.io/utils/integer/integer.go
- vendor/k8s.io/utils/pointer/pointer.go
- vendor/k8s.io/utils/ptr/OWNERS
- vendor/k8s.io/utils/ptr/README.md
- vendor/k8s.io/utils/ptr/ptr.go
- vendor/k8s.io/utils/trace/trace.go
- vendor/modules.txt
This is a manual cherry-pick of #1072
Replaces #1079 
git cherry-pick 71eead5286597657de281306876b5d94dea7e4ad 5d0939ad56e239919acfd962882ab7c076b4b7d9 14daecdb9ca49a7742afd922a8a9b55acf6935a6 f2060e0c0440d9ac79e0c456b564ef0047709007 0cbd86a4438c45be8c2917b781503b06f52bd55e 826745c3a1db822c0538f3322e98b33bd628ed13 50e8a730070d8f0864694df476da4c9fdf2a168b eb1623e71ca636ab3a3ecf2b39ab59e42209f5b8 87975f7833badbe8cbb9942eaf0a46c3c9481f9a caeca655be660dd93be63d3bc370c8616deb8641 2aed24f184b7f98124547d293a5a316e3eeca535 
go mod tidy (to add module update to 2aed24f1)
go mod vendor
modify pkg/operator/controller/ingress/deployment_test.go 
git add go.*
git add vendor/*
git add pkg/operator/controller/ingress/deployment_test.go 
git commit --amend (to add Modified-by to 2aed24f1)
make update …
> [release-4.15] OCPBUGS-35028: internalServiceChanged: Fix target port logic

- Makefile
The Makefile variable `Test` is assigned `TestAll` by default so that the E2E tests in `all_test.go` run by default. However, since Go interprets this as a regexp, both `TestAllowedSourceRanges` and `TestAllowedSourceRangesStatus` get run twice because their names starts with `TestAll`. Adding a regexp anchor will ensure the default `make test-e2e` command only runs the tests in `all_test.go`.
> OCPBUGS-35368: Add Regexp Anchor to TestAll

- pkg/manifests/assets/canary/daemonset.yaml
- pkg/manifests/assets/canary/route.yaml
- pkg/manifests/assets/canary/service.yaml
- pkg/operator/controller/canary/controller.go
- pkg/operator/controller/canary/daemonset.go
- pkg/operator/controller/canary/daemonset_test.go
- pkg/operator/controller/canary/route_test.go
- pkg/operator/controller/canary/service.go
- pkg/operator/controller/canary/service_test.go
- test/e2e/all_test.go
- test/e2e/canary_test.go
- test/e2e/client_tls_test.go
- test/e2e/router_compression_test.go
- test/http/serve-healthcheck.go
When the default ingress controller is configured to use mTLS, connecting to edge or reencrypt routes requires the client to have a valid certificate/key pair. There is no way for a user to provide a client certificate or key to the ingress operator, so canary checks using edge encryption fail. This PR changes the canary route to be passthrough and has the canary host handle the TLS handshake, allowing it to function even if mTLS is otherwise required.
> OCPBUGS-9037: Change Canary to use passthrough route

- go.mod
- go.sum
- pkg/manifests/assets/router/deployment.yaml
- pkg/manifests/assets/router/service-cloud.yaml
- pkg/manifests/assets/router/service-internal.yaml
- pkg/operator/controller/canary/daemonset_test.go
- pkg/operator/controller/canary/namespace_test.go
- pkg/operator/controller/canary/route_test.go
- pkg/operator/controller/gatewayapi/crds.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- pkg/operator/controller/ingress/internal_service.go
- pkg/operator/controller/ingress/internal_service_test.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- pkg/operator/controller/ingress/monitoring_test.go
- pkg/operator/controller/ingress/namespace_test.go
- pkg/operator/controller/ingress/nodeport_service.go
- pkg/operator/controller/ingress/nodeport_service_test.go
- pkg/operator/controller/ingress/poddisruptionbudget_test.go
- pkg/operator/controller/ingressclass/ingressclass_test.go
- test/e2e/all_test.go
- test/e2e/operator_test.go
- vendor/k8s.io/utils/integer/integer.go
- vendor/k8s.io/utils/pointer/pointer.go
- vendor/k8s.io/utils/ptr/OWNERS
- vendor/k8s.io/utils/ptr/README.md
- vendor/k8s.io/utils/ptr/ptr.go
- vendor/k8s.io/utils/trace/trace.go
- vendor/modules.txt
This is a manual cherry-pick of https://github.com/openshift/cluster-ingress-operator/pull/1081
git cherry-pick 71eead5 5d0939a 14daecd f2060e0 0cbd86a 826745c 50e8a73 eb1623e  caeca65 2aed24f
fix merge conflict in deployment_test.go
git add pkg/operator/controller/ingress/deployment_test.go
git cherry-pick --continue
go mod tidy
go mod vendor
make update
make verify
make build
make test
test failed, fix another issue in deployment_test.go
go mod tidy
go mod vendor
make update
make verify
make build
make test
git add go.*
git add vendor/*
git add pkg/operator/controller/ingress/deployment_test.go
git commit --amend
git cherry-pick 1f9795b 77595d0
go mod tidy
go mod vendor
make update
make verify
make build
make test
> [release-4.14] OCPBUGS-35399: Internal service changed: fix target port logic

- test/e2e/router_status_test.go
Use updateIngressControllerSpecWithRetryOnConflict to resolve E2E flakiness caused by the IngressController being updated after the E2E test retrieves a local copy, resulting in an "object has been modified" error.
[Example Flake](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-ingress-operator/1014/pull-ci-openshift-cluster-ingress-operator-release-4.15-e2e-azure-operator/1800626575222247424#1:build-log.txt:284-285)
[Search.CI Link](https://search.dptools.openshift.org/?search=FAIL%3A+TestAll%2Fparallel%2FTestIngressControllerRouteSelectorUpdateShouldClearRouteStatus&maxAge=48h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)
> OCPBUGS-35356: Retry IngressController updates in router status E2E

- pkg/operator/controller/ingress/controller.go
This PR revises the triggered log messages for the Cluster-ingress-operator
As mentioned in the issue:
In the cluster ingress operator, I addressed a logic error related to the log message triggered during updates to the Infrastructure CR. Previously, the log entry was generated even when no changes were made to the CR. 
To rectify this, I revised the logic to ensure that the log entry is now triggered only when a legitimate update to the Infra CR takes place.
> OCPBUGS-34413: Refine logging for accurate infra CR status updates

- pkg/operator/controller/canary/route.go
- test/e2e/all_test.go
- test/e2e/canary_test.go
Fix the update logic for the canary route to handle clearing `spec.host`. Attempts to clear `spec.host` using a simple update may be ignored (see https://github.com/openshift/origin/commit/54c072c122b48c5d7074fe8904d493d0534733e2).  Therefore it is necessary to delete and recreate the route.  
Before this change, the operator would set `spec.subdomain`, but it did not actually clear `spec.host`, and so setting `spec.subdomain` had no effect.
After this change, the operator should clear `spec.host`, and `spec.subdomain` should be in effect.
Follow-up to #1047.
> OCPBUGS-36465: Delete and recreate canary route to clear spec.host

- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/status.go
This PR revises status condition messages of IngessController with small changes.
As mentioned in the issue:
The ingress controller provides the `SyncLoadBalancerFailed` status for the `LoadBalancerReady` condition with a message that says `The kube-controller-manager logs may contain more details.`.
This is no longer true following the move from in-tree cloud providers to external cloud providers that are implemented by using the Cloud Controller Manager. To reflect that, the message is changed to `The cloud-controller-manager logs may contain more details.`
I was having trouble reproducing the Load Balancer service pending state as a day 2 operation to see the status message in the cluster. However, this is only a cosmetic change.
- `pkg/operator/controller/ingress/status.go` …
> OCPBUGS-31664: Fix SyncLoadBalancerFailed status message of IngressController

- pkg/operator/controller/canary/route.go
- test/e2e/all_test.go
- test/e2e/canary_test.go
Fix the update logic for the canary route to handle clearing `spec.host`. Attempts to clear `spec.host` using a simple update may be ignored (see https://github.com/openshift/origin/commit/54c072c122b48c5d7074fe8904d493d0534733e2).  Therefore it is necessary to delete and recreate the route.  
Before this change, the operator would set `spec.subdomain`, but it did not actually clear `spec.host`, and so setting `spec.subdomain` had no effect.
After this change, the operator should clear `spec.host`, and `spec.subdomain` should be in effect.
Follow-up to #1047.
---
This is manual cherry-pick of #1095.  #978 added the `TestCanaryWithMTLS` test to `test/e2e/all_test.go` in the release-4.17 branch, and this test is not in the release-4.16 branch, so it caused a conflict for this backport that …
> [release-4.16] OCPBUGS-32887: Delete and recreate canary route to clear spec.host

- manifests/00-cluster-role.yaml
- pkg/operator/controller/canary/route.go
- test/e2e/all_test.go
- test/e2e/canary_test.go
Before this change, cluster-ingress-operator did not have permission to update `spec.host` or `spec.subdomain` on an existing route as the operator's serviceaccount did not have the necessary "routes/custom-host" permission.  #965 added logic to the operator to clear `spec.host` and instead set `spec.subdomain`, but without the required permission, the update would fail with the following error message:
ERROR   operator.init   controller/controller.go:265    Reconciler error {"controller": "canary_controller", "object": {"name":"default","namespace":"openshift-ingress-operator"}, "namespace": "openshift-ingress-operator", "name": "default", "reconcileID": "463061e3-93a1-4067-802e-03e3f1f8cdd0", "error": "failed to ensure canary route: failed to update canary route …
> [release-4.15] OCPBUGS-36466: Allow operator to update Route spec.subdomain

- manifests/00-cluster-role.yaml
- pkg/operator/controller/canary/route.go
- test/e2e/all_test.go
- test/e2e/canary_test.go
Before this change, cluster-ingress-operator did not have permission to update `spec.host` or `spec.subdomain` on an existing route as the operator's serviceaccount did not have the necessary "routes/custom-host" permission.  #965 added logic to the operator to clear `spec.host` and instead set `spec.subdomain`, but without the required permission, the update would fail with the following error message:
ERROR   operator.init   controller/controller.go:265    Reconciler error {"controller": "canary_controller", "object": {"name":"default","namespace":"openshift-ingress-operator"}, "namespace": "openshift-ingress-operator", "name": "default", "reconcileID": "463061e3-93a1-4067-802e-03e3f1f8cdd0", "error": "failed to ensure canary route: failed to update canary route …
>  [release-4.14] OCPBUGS-36467: Allow operator to update Route spec.subdomain

- test/e2e/canary_test.go
- test/e2e/client_tls_test.go
- test/e2e/operator_test.go
- test/e2e/router_compression_test.go
- test/e2e/util_test.go
Some E2E tests were calling `getRouteHost` and expected it not to call `t.Fatal` when the hostname couldn't be found. However, `getRouteHost` did call `t.Fatal`, causing E2E test flakes. This fix moves the `t.Fatal` call outside of `getRouteHost`, allowing the function callers to handle the error as they wish.
> OCPBUGS-37627: Fix getRouteHost error handling

- .gitignore
- pkg/operator/controller/gatewayapi/controller.go
- test/e2e/gateway_api_test.go
- test/e2e/util_gatewayapi_test.go
Added watch for Gateway API CRDs to recreate CRDs if they get deleted
> NE-1273: Add a watch to the ingress operator so it will recreate the gwapi crds

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/controller_test.go
- test/e2e/lb_subnets_test.go
- test/e2e/operator_test.go
`NetworkLoadBalancerParameters` in the status wasn't being initialized when the IngressController was first created as a NLB. This fix addresses the issue and adds E2E test coverage for this scenario.
Additionally, fix a bug in `TestAWSLBSubnets` E2E for `verifyIngressControllerSubnetStatus` logic to ensure that NLB parameters are empty when the LB Type is Classic, and vice versa.
Additionally, fix a bug in both `TestAWSLBSubnets` and `TestUnmanagedAWSLBSubnets` where they only waited for the IngressOperator Available conditions. They did not wait for `Progressing=False` to ensure the `LoadBalancerProgressing=False` state, which is necessary to ensure the subnet update was accomplished.
> NE-1531: Fix Initialization of NLB Status Parameters

- pkg/dns/azure/client/auth.go
For ARO HCP, we need to override the authentication type to be MSI. For more information please see https://github.com/openshift/enhancements/pull/1659.
> NE-1688: Enable Azure MSI authentication for ARO HCP

- test/e2e/lb_eip_test.go
- test/e2e/lb_subnets_test.go
- test/e2e/util_test.go
The subnets and EIP E2E tests in AWS previously were testing connectivity using the route host name. However, we've found in the past that using the ELB host name with the Host header is much more reliable. This fix resolves these E2E flakes.
Prior Example Flake Fix: https://github.com/openshift/cluster-ingress-operator/pull/944
[Detailed Analysis of Why](https://issues.redhat.com/browse/OCPBUGS-13810?focusedId=22419881&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22419881)
CI DNS Bug: https://issues.redhat.com/browse/OCPBUGS-14966
> OCPBUGS-38441: Resolve DNS Resolution CI Flakes in Subnets and EIP E2E

- manifests/00-cluster-role.yaml
- pkg/manifests/assets/router/cluster-role.yaml
Give router pods permission to use the "restricted" securitycontextconstraint.  This permission is required since OpenShift 4.11 in order to use the "restricted" SCC.
[The OCP 4.11 release notes mention](https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-auth-pod-security-admission) that explicit permission is now required to use the "restricted" SCC:
The restricted SCC is no longer available to users of new clusters, unless the access is explicitly granted. In clusters originally installed in OpenShift Container Platform 4.10 or earlier, all authenticated users can use the restricted SCC when upgrading to OpenShift Container Platform 4.11 and later.
Router pods already have permission to use the "hostnetwork" SCC as they need this SCC …
> OCPBUGS-34418: Allow router pods to use the "restricted" SCC

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/controller_test.go
- pkg/operator/controller/ingress/status.go
When the LB type is changed, the status parameters for the previously selected type should be cleared. This fix ensures that the status remains consistent with the currently selected LB type.
> OCPBUGS-38217: Clear LB Status Parameters on LB Type Change

- pkg/operator/controller/dns/controller.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
- pkg/operator/controller/status/controller.go
The status was not being set to degraded because the lastTransitionTime was being set unnecessarily. It should only be set when the status changes.  See https://github.com/openshift/cluster-dns-operator/pull/375
The fix involves recognizing when the condition status changes, and only updating the transition time when this happens.
* pkg/operator/controller/condition.go - export the ConditionChanged func
for use by all previous callers.
* pkg/operator/controller/dns/controller.go - use the new ConditionChanged,
update logic for setting condition transition time.
* pkg/operator/controller/ingress/status.go - use the new ConditionChanged,
update logic for setting condition transition time.
* pkg/operator/controller/status/controller.go - use the new ConditionChanged,
update logic for setting …
> OCPBUGS-37491: Ingress operator status not degraded when canary route fails

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
Currently, the code does not set `deployment.Spec.Strategy` before breaking out in the SingleReplica case. This results in the kube-apiserver defaulting the `Strategy`. On the next reconcile pass, this code will attempt to unset the defaulted values leading to a hot reconciliation loop.
To avoid this, explicitly set the `Strategy` to the kube default before the `break` out of the switch.
xref https://github.com/openshift/cluster-ingress-operator/pull/810
> OCPBUGS-38871: ingress: deployment: explicitly set DeploymentStrategy in SingleReplica case

- pkg/operator/controller/ingress/load_balancer_service.go
The instructions for effectuating a scope change were missing because the `loadBalancerServiceIsProgressing` did not account for the PowerVS, Alibaba, and OpenStack platform types. This update add those instructions for these platforms when they change an IngressController's scope.
Originally split from https://github.com/openshift/cluster-ingress-operator/pull/1133
> OCPBUGS-39151: Add Missing Scope Change Instructions

- pkg/manifests/assets/router/deployment.yaml
- pkg/operator/controller/ingress/deployment_test.go
Courtesy PR demonstrating how to avoid pod deletion during serial e2e tests in runs like https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-upi-serial/1832439322075205632 which cause the observed failures in [component readiness](https://sippy.dptools.openshift.org/sippy-ng/component_readiness/test_details?Aggregation=none&Architecture=amd64&Architecture=amd64&FeatureSet=default&FeatureSet=default&Installer=upi&Installer=upi&Network=ovn&Network=ovn&NetworkAccess=default&Platform=vsphere&Platform=vsphere&Scheduler=default&SecurityMode=default&Suite=serial&Suite=serial&Topology=ha&Topology=ha&Upgrade=none&Upgrade=none&baseEndTime=2024-06-27%2023%3A59%3A59&baseRelease=4.16&baseStartTime=2024-05-28%2000%3A00%3A00&c …
> OCPBUGS-41527: Add tolerations to survive scheduler taint manager e2e tests on workers

- manifests/02-deployment-ibm-cloud-managed.yaml
- manifests/02-deployment.yaml
- pkg/manifests/assets/canary/daemonset.yaml
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
Workloads affected:
- `openshift-ingress/router-default` deployment
- `openshift-ingress-canary/ingress-canary` daemonset
- `openshift-ingress-operator/ingress-operator` deployment
> AUTH-482: set required-scc for openshift workloads

- pkg/dns/azure/client/auth.go
Set the managed identity client ID for the ARO HCP override to use managed identity.
> OCPBUGS-42004: Set the MI client ID for the ARO HCP override

- pkg/operator/controller/names.go
- test/e2e/allowed_source_ranges_test.go
- test/e2e/canary_test.go
- test/e2e/client_tls_test.go
- test/e2e/forwarded_header_policy_test.go
- test/e2e/http2_disable_test.go
- test/e2e/http_header_buffer_test.go
- test/e2e/operator_test.go
- test/e2e/route_metrics_test.go
- test/e2e/util_test.go
This PR fixes flakes in e2e tests due to the IngressController or Route objects being updated after the e2e test retrieves a local copy, resulting in an "object has been modified" error.
This is achieved by using the existing helper function `updateIngressControllerWithRetryOnConflict`.
Also a new helper function `updateRouteWithRetryOnConflict` was added to retry updates of Route object in the same way.
Example fail to update IngressController:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-ingress-operator/1114/pull-ci-openshift-cluster-ingress-operator-master-e2e-azure-operator/1818681004299128832
Example fail to update Route:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cluster-ingress-operator/1023/pull- …
> OCPBUGS-36340: Retry IngressController and Route updates in E2E tests

- pkg/dns/aws/dns.go
- pkg/dns/aws/dns_test.go
Move a to-do comment closer to the relevant source code.
Remove a useless, misleading `break` statement.  Rewrite the relevant code to be clearer.  Add a comment to describe how the service endpoints configuration is interpreted.
The AWS DNS provider implementation loops over the configured service endpoints to set service endpoint for the various clients: route53, elb, and tagging.  Inside this loop is a `switch` statement.  The first `case` statement has a `break` statement.  It appears that the intent may have been to break the loop.  However, because it is inside the `switch` statement, it only breaks out of the switch.  As there is nothing between the `switch` and the bottom of the loop, the `break` itself has no effect and can be removed.
However, because this `case` statement is …
> OCPBUGS-37932: Always log AWS service endpoints

- test/e2e/dns_ingressdegrade_test.go
Some platforms only have public zones, some others private, some none.
Let's just run zone update tests where applicable so we support
all platforms and also cover more scenarios.
> OCPBUGS-43033: e2e/ingress_dns: support both private & public

- cmd/ingress-operator/main.go
- test/e2e/all_test.go
- test/e2e/ocpbugs48050_test.go
- test/ocpbugs48050/server.go
Add a new command 'serve-ocpbugs40850-test-server' to the ingress-operator. Implement this HTTP server with two endpoints: /single-te and /duplicate-te, returning responses with single and duplicate Transfer-Encoding headers respectively.
Create a new e2e test that:
- Sets up a service, deployment, and routes for the test server
- Sends GET requests to both /single-te and /duplicate-te endpoints
- Verifies that /duplicate-te requests result in the expected error
- Checks metrics to ensure /duplicate-te hits are recorded in the 'haproxy_backend_duplicate_te_header_total' metric, except for passthrough routes
Support different TLS termination types in the test:
- Edge
- Reencrypt
- Passthrough (confirm no recording of duplicate Transfer-Encoding header metrics)
This test validates the …
> OCPBUGS-43095: Add e2e test for duplicate Transfer-Encoding headers

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- pkg/operator/controller/ingress/status_test.go
- test/e2e/all_test.go
- test/e2e/operator_test.go
- test/e2e/util_test.go
The PR introduces the following changes:
- The ingress controller now watches for the `Infrastructure` object changes. This ensures that any modifications to user-defined tags (`platform.AWS.ResourceTags`) trigger an update of the load balancer service.
- Consider the `awsLBAdditionalResourceTags` annotation as a managed annotation. Any changes to user-defined tags in the Infrastructure object will be reflected in this annotation, prompting an update to the load balancer service.
Implements: [CFE-1134](https://issues.redhat.com//browse/CFE-1134)
> CFE-1134: Watch infrastructure and update AWS tags

- go.mod
- pkg/dns/azure/client/auth.go
- pkg/util/filewatcher/filewatcher.go
Use Client Certificate Authentication for ARO HCP deployments. HyperShift will pass the needed environment variables for this authentication method: ARO_HCP_MI_CLIENT_ID, ARO_HCP_TENANT_ID, and ARO_HCP_CLIENT_CERTIFICATE_PATH.
> HOSTEDCP-2031: Use Client Certificate Authentication for ARO HCP deployments

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/operator_test.go
- Ingress controller: passed reconciler config to `desiredRouterDeployment`.
- TestDesiredRouterDeploymentDynamicConfigManager: added test case for invalid max servers.
Follow-up to https://github.com/openshift/cluster-ingress-operator/pull/1159:
- https://github.com/openshift/cluster-ingress-operator/pull/1159#discussion_r1852631252
- https://github.com/openshift/cluster-ingress-operator/pull/1159#discussion_r1852659675
- https://github.com/openshift/cluster-ingress-operator/pull/1159#discussion_r1853070823
- https://github.com/openshift/cluster-ingress-operator/pull/1159#discussion_r1852679738
- https://github.com/openshift/cluster-ingress-operator/pull/1159#discussion_r1852634142
> NE-1790: Follow up to enable Dynamic Configuration Manager feature gate

- pkg/operator/controller/gatewayapi/controller.go
A single CRD watch was added with a predicate to filter CRDs based on the gatewayapiv1.GroupName. This ensures that only relevant CRDs are watched, reducing unnecessary logging when the Gateway API feature is not enabled.
> OCPBUGS-41892: Single Watch on GWAPI CRD

- Makefile
- hack/gatewayapi-conformance.sh
This PR adds new Makefile target and enables the upstream gateway-api conformance test.
Once this get merged, the follow up https://github.com/openshift/release/pull/60217 will add optional pre-submits job to run conformance test.
> NE-1260: Add Makefile target to run Gateway API conformance tests

- test/e2e/idle_connection_test.go
- test/e2e/operator_test.go
- test/e2e/util_gatewayapi_test.go
- test/e2e/util_test.go
Fix IBMCloud DNS resolution issues in our E2E tests with two fixes:
Extend the timeout to 10 minutes. This fix defines the timeout as a documented constant, ensuring that all DNS resolution logic is updated to reference it.
[Testing](https://storage.googleapis.com/test-platform-results/pr-logs/pull/openshift_cluster-ingress-operator/1187/pull-ci-openshift-cluster-ingress-operator-master-e2e-ibmcloud-operator/1884453175545565184/build-log.txt) showed that new IBMCloud DNS records were resolving within 7 minutes for external (e.g., test runner cluster) queries. Setting the timeout to 10 minutes provides a reasonable buffer to accommodate DNS propagation across all platforms.
During testing, we found that IBMCloud's DNS resolution works well from outside the cluster (e.g., the test runner …
> OCPBUGS-48780: Fix IBMCloud DNS Propagation Issues in E2E

- pkg/dns/ibm/private/client/fake_client.go
- pkg/dns/ibm/private/dnssvcs_provider.go
- pkg/dns/ibm/private/dnssvcs_provider_test.go
- pkg/dns/ibm/public/cis_provider.go
- pkg/dns/ibm/public/cis_provider_test.go
- pkg/dns/ibm/public/client/fake_client.go
- test/e2e/operator_test.go
The IBM Public Cloud DNS provider (`cis_provider.go`) had a bug in `createOrUpdateDNSRecord` where it checked for the existence of a DNS record by filtering both DNS name and target. If the target was updated (e.g., due to a load balancer recreation), the logic would not match the existing DNS record. As a result, the function would attempt to create a new record, but fail because a record with that name already existed, as multiple DNS records with the same
name are not allowed in IBM Cloud DNS providers.
The fix is to remove the filtering by target and rely solely on filtering by name, as the name is the only attribute that needs to be unique.
This fix also includes a subtle fix in `createOrUpdateDNSRecord` of cis_provider.go to fall through to the create logic in the case of a …
> OCPBUGS-32776: Fix IBM Public Cloud DNS Provider Update Logic

- pkg/operator/controller/gatewayclass/controller.go
- pkg/operator/controller/names.go
- pkg/operator/operator.go
- test/e2e/gateway_api_test.go
- test/e2e/util_gatewayapi_test.go
Recreating the SMCP and subscription, in case the SMCP or subscriptions are deleted manually.
> OCPBUGS-31550: Gateway API - recreating SMCP which breaks Gateway API

- Makefile
- manifests/01-validating-admission-policy-binding.yaml
- manifests/01-validating-admission-policy.yaml
- test/e2e/all_test.go
- test/e2e/gateway_api_test.go
- test/e2e/util_gatewayapi_test.go
This PR introduces a validating admission policy that restricts modifications to CRDs from the "gateway.networking.k8s.io" group, allowing only the cluster ingress operator's service account to make changes.
This ensures that the core OpenShift retains exclusive ownership of the Gateway API implementation, preventing modifications from any add-ons (whether third-party or Red Hat-owned).
The policy and its corresponding binding will be managed by CVO.
> NE-1953: Add Validating Admission Policy for Gateway API CRDs

- Makefile
- pkg/operator/controller/gateway-service-dns/controller_test.go
- pkg/operator/controller/gatewayapi/controller_test.go
- pkg/operator/controller/route-metrics/controller_test.go
- pkg/operator/controller/test/util/fake.go
This PR:
- extracts test helpers that were used across multiple controllers into a dedicated package: `pkg/operator/controller/test/util`. This includes `FakeCache`, `FakeController`, and `FakeClientRecorder`.
- allows `test` target to run specific unit tests using `-run` flag.
> NE-1981: Move controller test helpers to dedicated package

- cmd/ingress-operator/start.go
- manifests/00-cluster-role.yaml
- manifests/02-deployment-ibm-cloud-managed.yaml
- manifests/02-deployment.yaml
- pkg/operator/config/config.go
- pkg/operator/controller/gatewayclass/controller.go
- pkg/operator/controller/gatewayclass/subscription.go
- pkg/operator/controller/gatewayclass/subscription_test.go
- pkg/operator/controller/names.go
- pkg/operator/operator.go
Istio and the Gateway API CRDs need to be in sync to work. The CRDs are baked into a particular openshift release, so this change updates the ingress operator to install a compatible version with the CRDs it already installs.
> NE-1907: Manage OSSM operator subscription manually to ensure a compatible version is installed

- pkg/manifests/assets/gateway-api/v1_2_1/gateway.networking.k8s.io_gatewayclasses.yaml
- pkg/manifests/assets/gateway-api/v1_2_1/gateway.networking.k8s.io_gateways.yaml
- pkg/manifests/assets/gateway-api/v1_2_1/gateway.networking.k8s.io_grpcroutes.yaml
- pkg/manifests/assets/gateway-api/v1_2_1/gateway.networking.k8s.io_httproutes.yaml
- pkg/manifests/assets/gateway-api/v1_2_1/gateway.networking.k8s.io_referencegrants.yaml
- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
- pkg/operator/controller/status/controller.go
- pkg/operator/controller/status/controller_test.go
- pkg/operator/controller/test/crds/crds.go
- pkg/operator/controller/test/crds/crds_test.go
- pkg/operator/controller/test/crds/gateway-api/experimental/v1/gateway.networking.k8s.io_gateways.yaml
- pkg/operator/controller/test/crds/gateway-api/experimental/v1/gateway.networking.k8s.io_tcproutes.yaml
- pkg/operator/controller/test/crds/gateway-api/experimental/v1/gateway.networking.x-k8s.io_listenersets.yaml
- pkg/operator/controller/test/crds/gateway-api/standard/v0/gateway.networking.k8s.io_gatewayclasses.yaml
- pkg/operator/controller/test/crds/gateway-api/standard/v0/gateway.networking.k8s.io_gateways.yaml
- pkg/operator/controller/test/crds/gateway-api/standard/v0/gateway.networking.k8s.io_httproutes.yaml
- pkg/operator/controller/test/crds/gateway-api/standard/v0/gateway.networking.k8s.io_referencegrants.yaml
- pkg/operator/operator.go
- test/e2e/all_test.go
- test/e2e/gatewayapi_upgradeable_test.go
This PR adds a new check in the Cluster Ingress Operator which sets its `Upgradeable` condition to `False` until the state of the Gateway API CRDs is validated.
The check logic verifies whether any Gateway API CRDs exist. If no GWAPI CRDs are installed in the cluster, then the operator's condition `Upgradable=True` (granted that nothing else prevents the upgrade).
If Gateway API CRDs are already present in the cluster the Cluster Ingress Operator `Upgradeable` condition is `False` until:
- only the standard CRDs exist: `GatewayClass`, `Gateway`, `HTTPRoute`, `GRPCRoute` or `ReferenceGrant`, and no other APIs from the `gateway.networking.k8s.io` are present.
- the existing standard CRDs are in `v1.2.1` which is the one currently targeted for OCP 4.19.
The check logic is added only to …
> NE-1952: Pre-upgrade check for Gateway API CRD Management Succession

- manifests/01-validating-admission-policy.yaml
- test/e2e/gateway_api_test.go
- test/e2e/util_gatewayapi_test.go
This PR adds `gateway.networking.x-k8s.io` to the match condition of the operator's Validating Admission Policy. This change ensures that modifications to experimental Gateway API CRDs can be made only by the ingress operator.
> NE-1953: Add experimental Gateway API group to Validating Admission Policy

- pkg/operator/controller/gatewayapi-upgradeable/controller.go
- pkg/operator/controller/names.go
- pkg/operator/operator.go
- test/e2e/gatewayapi_upgradeable_test.go
This PR introduces the following:
Initialize the GatewayAPI upgradeable controller
- Added the required imports and constants.
- Defined predicates for CRD and ConfigMap events to manage the admin gate.
- Configured watches in the controller for specific changes in the ConfigMap.
Implement the reconciler logic
- Added the Reconcile function to manage the admin gate addition and removal based on conditions
Enhance the operator initialization
- Conditionally initialize the gatewayapi_upgradeable controller based on the GatewayAPI feature gate.
End-to-End Tests
- Added the TestGatewayAPIUpgradeable end-to-end test.
- Included the new test case in the test suite.
> NE-1951: Pre-upgrade Admin Gate for Gateway API CRD Management Succession

- pkg/dns/gcp/provider.go
- pkg/operator/controller/dns/controller.go
- pkg/operator/operator.go
Enhancement link for the feature: https://github.com/openshift/enhancements/pull/1734
** Vendor update
** Set the endpoint information in the Config for GCP
** If an endpoint exists for the DNS service use the endpoint as an option when creating the new client.
> CORS-3907: Update ingress operator to with custom endpoints

- test/e2e/gateway_api_test.go
Add a new test to verify that Istio is configured not to allow manual deployment.
> NE-1994: Add E2E test for Istio manual deployment

- pkg/operator/controller/status/controller.go
- pkg/operator/operator.go
- test/e2e/canary_test.go
- test/e2e/gateway_api_test.go
- test/e2e/operator_test.go
- test/e2e/util_gatewayapi_test.go
* `pkg/operator/controller/names.go` (`GlobalOperatorsNamespace`): New const for the "openshift-operators" namespace.
(`ServiceMeshSubscriptionName`): Use `GlobalOperatorsNamespace`.
* `pkg/operator/controller/status/controller.go` (`New`): Add a watch for subscriptions so that the status controller updates `relatedObjects` when the OSSM subscription is added or removed.
(`Config`): Add `GatewayAPIEnabled` field.
(`Reconcile`): If `GatewayAPIEnabled` is true, add resources related to Gateway API to `relatedObjects`.  If `haveOSSMSubscription` is true, add resources that require the subscription.
(`operatorState`): Add `haveOSSMSubscription` field.
(`getOperatorState`): Set `haveOSSMSubscription`.
* `pkg/operator/operator.go` (`New`): Watch the "openshift-operators" namespace, and specify …
> NE-1277: status: Add Gateway API objects to relatedObjects

- hack/gatewayapi-conformance.sh
Add GRPCRoute to the SupportedFeatures list.
Increase max time to consistency to 180s for these tests.
Increase total run time of test to 20m max.
Co-authored-by: Hongan Li <lihongan>
> NE-2008: Add GRPC conformance tests

- manifests/01-validating-admission-policy-binding.yaml
- manifests/01-validating-admission-policy.yaml
The `openshift-ingress-operator-gatewayapi-crd-admission` Validating Admission Policy is bound to `GatewayAPI` featuregate, which has been promoted to GA (https://github.com/openshift/api/pull/2261).
This PR removes the `feature-set` annotation from manifests related to VAP, this effectively makes them part of the `Default` featureset.
> NE-2009: Move VAP to Default featureset

- pkg/operator/controller/gateway-service-dns/controller_test.go
- pkg/operator/controller/gatewayapi/controller.go
- pkg/operator/controller/gatewayapi/controller_test.go
- pkg/operator/controller/gatewayapi/crds.go
- pkg/operator/controller/gatewayapi/status.go
- pkg/operator/controller/status/controller.go
- pkg/operator/controller/status/controller_test.go
- pkg/operator/controller/test/util/fake.go
- test/e2e/gateway_api_test.go
- test/e2e/util_gatewayapi_test.go
Set the ingress cluster operator’s `Degraded` status to `true` if unmanaged Gateway API CRDs exist on the cluster.
An unmanaged Gateway API CRD is one with "gateway.networking.k8s.io" or "gateway.networking.x-k8s.io" in its `spec.group` field, and not managed by the gatewayapi controller.
This PR uses the cluster operator’s `status.extension` field to store the names of unmanaged CRDs. The gatewayapi controller writes to this field, while the status controller reads it and updates the ingress cluster operator’s `Degraded` status accordingly.
> NE-1969: Set Degraded=True if unmanaged Gateway API CRDs exist

- pkg/operator/controller/gatewayapi/controller.go
- pkg/operator/controller/gatewayapi/controller_test.go
- pkg/operator/controller/status/controller.go
- pkg/operator/operator.go
Only try to watch subscriptions and installplans if the "marketplace" and "OperatorLifecycleManager" capabilities are enabled.
If these capabilities are not enabled, the installplans and subscriptions resources do not exist.  Before this change, the operator would fail to initialize when these capabilities were not enabled as the status and gatewayclass controllers would try and fail to watch the non-existent resources.
> OCPBUGS-55317: Check capabilities before watching OLM resource

- pkg/operator/controller/status/controller.go
- pkg/operator/operator.go
- test/e2e/operator_test.go
Omit the namespace for the istios resource in `relatedObjects` as the istios resource is cluster-scoped.
Omit the namespace for the gateways resource in `relatedObjects` as Istio manages gateways in all namespaces.
Pass `ctx` from the controller's `Reconcile` method to `getOperatorState, and use it instead of `context.TODO()`.
Check whether the gatewayclasses, gateways, and istios CRDs actually exist before adding them to `relatedObjects`.
Watch customresourcedefinitions in the status controller so that it updates `relatedObjects` as these CRDs are created.
Check the "GatewayAPIController" featuregate to determine whether to add the gatewayclasses, gateways, istios, and subscriptions resources to relatedObjects, in addition to checking the "GatewayAPI" featuregate.
Before this change, the …
> OCPBUGS-54745: status: Conditionally add CRDs to relatedObjects

- pkg/operator/controller/dns/controller.go
- pkg/operator/operator.go
Removed PrivateHostedZoneAWS from cluster-ingress-operator as it is no longer needed
> OCPBUGS-55652: Removed PrivateHostedZoneAWS from component

- test/e2e/all_test.go
- test/e2e/idle_connection_test.go
- test/e2e/util_test.go
- test/http2/server.go
Follow-up of https://github.com/openshift/cluster-ingress-operator/pull/1234. This PR adds e2e tests for `IdleConnectionTerminationPolicy` ingresscontroller API knob.
This PR is a manual cherry pick of https://github.com/openshift/cluster-ingress-operator/pull/1225 with 2 differences:
- [New commit with an e2e helper function to get ingress address of the service publishing IngressController](https://github.com/openshift/cluster-ingress-operator/pull/1235/commits/f0caf3f1dc93f04f00ae7a93e987bb630df12d4c) is added because the e2e test is using this helper function.
- [New commit which passes testing.T argument to getRouteHost e2e helper function](https://github.com/openshift/cluster-ingress-operator/pull/1235/commits/d5b578269494b4efb528f8e28bd763dfadcded00).
> [release-4.16] OCPBUGS-56424: Add e2e tests for IdleConnectionTerminationPolicy

- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
Previously, upgrades from 4.15 to 4.16 were only blocked for default leaf certs using SHA1. However, in 4.16, any SHA1 cert that is CA-signed (not self-signed) is unsupported. As a result, we were incorrectly allowing upgrades for SHA1 intermediate certificates, while blocking upgrades for self-signed SHA1 leaf certificates.
This fix blocks upgrades to 4.16 for IngressControllers with default certificates containing CA-signed SHA1 certs. Root CA certs using SHA1 are still supported.
**Additional Fix For Blocking 4.15-->4.16 Upgrades for DSA SHA1 Default Certs:**
Previously, upgrades were not being blocked when default certificates used DSA SHA1. Although DSA certificates are rejected at the router level by our validation logic, they can still be used in a default certificate. In 4.15, DSA …
> [release-4.15] OCPBUGS-49392: Block Upgrades in release 4.15 for CA-Signed Certs Using SHA1

- cmd/ingress-operator/start.go
- hack/ossm-overrides.md
- manifests/02-deployment-ibm-cloud-managed.yaml
- manifests/02-deployment.yaml
- pkg/operator/config/config.go
- pkg/operator/controller/gatewayclass/controller.go
- pkg/operator/controller/gatewayclass/controller_test.go
- pkg/operator/controller/gatewayclass/istio.go
- pkg/operator/controller/gatewayclass/subscription.go
- pkg/operator/controller/gatewayclass/subscription_test.go
- pkg/operator/operator.go
Define annotations for the gatewayclass by which the channel and version for the OSSM subscription can be overridden.
When creating the subscription, the operator now checks the following annotations:
unsupported.do-not-use.openshift.io/ossm-channel
unsupported.do-not-use.openshift.io/ossm-version
One or both annotations may be specified to override the channel or version from the config.
> NE-2108: Add OSSM channel and version override annotations

- hack/ossm-overrides.md
[Istio versions use `v` prefix](https://github.com/openshift-service-mesh/sail-operator/blob/c2c0b245714353bfb720b7cfdfe9c5dd21f64fe4/bundle/manifests/sailoperator.io_istios.yaml#L9925); without it, the Istio CRD will complain about unsupported version:
```
failed to create istioi /openshift-gateway: Istio.sailoperator.io "openshift-gateway" is invalid:
[spec.version: Unsupported value: "1.26-latest": supported values: "v1.26-latest"]
```
> NE-2108: docs - correct Istio version format in ossm-overrides.md

- pkg/operator/controller/gatewayapi/controller.go
- pkg/operator/controller/gatewayapi/controller_test.go
- pkg/operator/controller/names.go
- pkg/operator/controller/status/controller.go
- pkg/operator/controller/status/controller_test.go
- pkg/operator/operator.go
Detect subscriptions that would prevent the Ingress Operator from installing OSSM 3, and set the operator's degraded condition to true when any of those subscriptions are present.
This is the implementation of [NE-2066](https://issues.redhat.com//browse/NE-2066)
> NE-2066: Set degraded=true when OSSM 3 can't be installed

- test/e2e/util_gatewayapi_test.go
Increase the timeout value for the `assertExpectedDNSRecords` test/e2e/util_gatewayapi_test function to 2 minutes to give the DNSRecords more time to be cleaned up in the e2e test cases that check for the record deletion. This is to avoid CI flakes.
Also increase the polling interval from 1s to 5s to avoid unnecessary polls and reduce the noise in the logs.
The changes are expected to increase the overall test run time by 3 minutes in total.
> OCPBUGS-59139: Increase assertExpectedDNSRecords timeouts

- test/e2e/operator_test.go
- test/e2e/util_test.go
Changing `infrastructures.config.openshift.io` causes Cloud controller manager to rollout/restart, to read the new configurations.
This happens at:
```
updateInfrastructureConfigSpecWithRetryOnConflict()
```
This restart can take at least 3 minutes due to controller-runtime leader election, + the required time to re-schedule the Pod on the node.
This may not be enough to ensure a LoadBalancer creation, causing the test to timeout when CCM has been restarted but is not yet available to reconcile the new LoadBalancer request.
> OCPBUGS-53432: deflake TestIngressControllerCustomEndpoints by proper waiting for CCM to be ready

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/load_balancer_service.go
- pkg/operator/controller/ingress/load_balancer_service_test.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
- pkg/operator/operator.go
- test/e2e/lb_subnets_test.go
The IngressControllerLBSubnetsAWS feature gate was at first introduced as TPNU in OpenShift 4.17 and was promoted to Default in the same release. The feature gate has been enabled by default for 3 releases, so it is scheduled to be removed imminently.
The feature itself (ability to choose AWS subnets for LoadBalancer Service) remains, only the feature gate check is removed.
Follow-up to the commit which introduced the feature gate: https://github.com/openshift/cluster-ingress-operator/pull/1046/commits/26dfe2c2f030cd6af33f94c8c958bbfcb733ba18
Feature was added as TPNU in: https://github.com/openshift/api/pull/1841
Feature was promoted to Default (GA) in: https://github.com/openshift/api/pull/1966
- pkg/operator/controller/ingress/controller.go: Remove IngressControllerLBSubnetsAWSEnabled …
> OCPBUGS-55673: Remove IngressControllerLBSubnetsAWS featuregate

- Makefile
- hack/test-pre-release-ossm-images.sh
- test/e2e/util_gatewayapi_test.go
Currently we have obtained a temp token from ossm team and can locally run the tests with the most up to date pre-release version (OSSM 3.2.0) 
e2e results:
```
--- PASS: TestGatewayAPI (736.15s)
--- PASS: TestGatewayAPI/testGatewayAPIResources (48.21s)
--- PASS: TestGatewayAPI/testGatewayAPIObjects (206.52s)
--- PASS: TestGatewayAPI/testGatewayAPIManualDeployment (10.30s)
--- PASS: TestGatewayAPI/testGatewayAPIIstioInstallation (12.75s)
--- PASS: TestGatewayAPI/testGatewayAPIDNS (54.96s)
--- PASS: TestGatewayAPI/testGatewayAPIDNS/multipleGatewaysSameListenerHostname (39.41s)
--- PASS: TestGatewayAPI/testGatewayAPIDNS/gatewayListenersWithOverlappingHostname (15.44s)
--- PASS: TestGatewayAPI/testGatewayAPIDNSListenerUpdate (187.57s)
--- PASS: …
```
> NE-1334: Script to install ossm pre-release operator and run GWAPI e2e tests
