openshift/cluster-ingress-operator

- HACKING.md
- README.md
/cc @openshift/sig-network-edge
> Add README and HACKING docs

- .gitignore
- Dockerfile
- Makefile
/cc @openshift/sig-network-edge
> Add product image build support files

- manifests/04_cluster-ingress-operator.yaml
Use the image spec we actually push to.
> Update operator image spec

- pkg/stub/handler.go
Handle delete events for ClusterIngress objects.
> Handle delete events

- test/integration/integration_test.go
@openshift/sig-network-edge PTAL
> Fix integration tests

- pkg/stub/handler.go
- sdk.Create(ds) will populate all the needed info in 'ds'.
- set owner ref instead of append, otherwise we may
end up with same owner ref multiple times.
> Owner ref for ingress service should only call sdk.Get() on ds if needed.

- HACKING.md
- README.md
/cc @openshift/sig-network-edge @smarterclayton @derekwaynecarr @bmcelvee
> Improve docs

- pkg/operator/controller/controller.go
- pkg/operator/controller/status.go
- pkg/operator/controller/status_test.go
- test/e2e/operator_test.go
https://coreos.slack.com/archives/CCH60A77E/p1549234657654400
> Renamed ingress ClusterOperator name from 'openshift-ingress-operator' to 'ingress'

- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_dns.go
- pkg/operator/controller/controller_lb.go
Currently we requeue the requests in these cases:
- cluster DNS config not found
- cluster Infra config not found
- get or create ServiceMonitor failed due to unknown GVK
Re-queued requests will be retried after 10 seconds by the controller.
> Requeue requests during controller reconciliation if needed

- pkg/operator/controller/controller.go
Always compute status unless it's absolutely impossible — otherwise transient failures that merely partially degrade service (e.g. metrics integration) will cause the operator to report unavailable status.
> controller: try harder to publish status when errors occur

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/openshift/api/config/v1/types_features.go
- vendor/github.com/openshift/api/config/v1/types_network.go
Update openshift/api to incorporate https://github.com/openshift/api/pull/238.
> deps: bump openshift/api

- test/e2e/operator_test.go
Previously, e2e only tested CRUD operations against the "default" ClusterIngress. This PR adds create/delete tests for multiple user-defined ClusterIngress resources.
> Update e2e to test multiple ClusterIngress resources

- pkg/dns/aws/dns.go
Previously, an ingresscontroller delete would hang when the
operation is performed prior to the DNS alias record being
created.
Fixes bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1683515
> Updates DNS deletion to support not found records

- Gopkg.lock
awserr is needed due to pr #164
> deps: bump to add awserr and remove k8s autoscale

- pkg/operator/controller/controller.go
Follow up to https://github.com/openshift/api/pull/251
> operator: set default publishing strategy to HostNetwork

- pkg/operator/controller/controller_router_deployment.go
We want the gains and to soak test for regressions.
/cc @smarterclayton @knobunc @openshift/sig-network-edge @mcurry-rh 
For your consideration.
> haproxy: set nbthread to 4 by default

- pkg/operator/operator.go
This commit adds error handling for the `Watch` method.
> Adds Watch error handling

- pkg/operator/controller/status.go
Previously, `clusteroperator/ingress` was being created without `status`. Even though the resource was being created with status fields properly constructed and included in the `client.create` call, the resource is initially created without `status`. `clusteroperator/ingress` must be created first, then have the status updated.
> Bug 1699488: Fixes Ingress ClusterOperator Initial Status

- pkg/operator/controller/controller.go
If an IngressController's effective domain is already in use, set the `Available` status condition to false with an explanatory message.
* `pkg/operator/controller/controller.go` (`enforceEffectiveIngressDomain`): Set the `Available` status condition if the domain is not unique.
> Report available=false if domain is already in use

- pkg/operator/controller/controller_router_deployment.go
Choose an appropriate default deployment strategy for an endpoint publishing
strategy.
The default is a rolling update with 25% max unavailable and 25% max surge. This
enables 100% availability rollouts at any replica/node count when the publishing
strategy supports colocated ingress controllers.
With HostNetwork, use 25% max unavailable and 0 surge. This is because the
ingress controllers can't be colocated. Usually, replicas will be equal to the
node pool size. Under these conditions, surge requires new nodes to support the
rollout. This means a positive surge can cause the rollout to wedge in the
absence of auto-scaling.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1701392
> Bug 1701392: Choose an appropriate default deployment strategy for an endpoint publishing strategy

- test/e2e/operator_test.go
Get the ingress controller from the API in between updates so that that each update uses the latest resource version in order to prevent the following test failure:
--- FAIL: TestIngressControllerUpdate (12.77s)
operator_test.go:367: failed to reset IngressController: Operation cannot be fulfilled on ingresscontrollers.operator.openshift.io "default": the object has been modified; please apply your changes to the latest version and try again
* `test/e2e/operator_test.go` (`TestIngressControllerUpdate`): Wait for ingress controller to be available at the start of the test.  Get the ingress controller in between updates to ensure we have the latest resource version for each update.  Use `RouterOperatorGeneratedDefaultCertificateSecretName` instead of hard-coding the default secret name. …
> Bug 1705100: TestIngressControllerUpdate: Re-get between updates

- pkg/operator/controller/controller_router_deployment.go
- pkg/operator/controller/controller_router_deployment_test.go
Before this change, ingresscontrollers published via LoadBalancerService could
be co-located according to a soft anti-affinity policy. This policy resulted in
a high probability of scheduler outcomes whereby 100% of ingresscontroller
processes were co-located on a single node after cluster installation, defeating
HA.
In the absence of the descheduler (for auto-rebalancing), the possibility
of unwanted co-location is too great a risk given admins have no obvious way
to detect the surprise co-location and no good procedure for forcing rebalancing.
After this change, deployment topologies are made more predictable by disabling
co-location for all publishing strategies.
An additional consequence of this change is that 100% availability rollouts when
the number of deployment replicas is equal …
> Bug 1703943: Make deployment topologies more predictable by prohibiting co-location

- pkg/operator/controller/controller_service_monitor.go
- pkg/operator/controller/names.go
@openshift/sig-network-edge PTAL
> Minor: Move service monitor name to pkg/operator/controller/names.go

- pkg/operator/controller/status.go
Add related ingresscontrollers to operator status to ensure ingresscontrollers
are captured by must-gather.
`oc adm must-gather` output:
```
$ tree namespaces/openshift-ingress-operator/
namespaces/openshift-ingress-operator/
└── operator.openshift.io
└── ingresscontrollers
└── default.yaml
2 directories, 1 file
```
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1717737
> Bug 1717737: status: add related ingresscontrollers to operator status

- manifests/02-deployment.yaml
- pkg/operator/controller/ingress/deployment.go
ref: https://jira.coreos.com/browse/POD-114
> use GA kubelet OS label

- pkg/operator/controller/status/controller.go
Add dnsrecords to related objects to ensure they are collected by must-gather.
> status: add dnsrecords to related objects

- pkg/operator/controller/dns/controller.go
Before this change, DNS records were only published to the configured public DNS
if the ingresscontroller load balancer is public. After this change, always
publish DNS records to any configured private or public DNS zone regardless of
the ingresscontroller load balancer scope. The new default seems more generally
useful, especially in the contexts in which internal load balancers are used.
Non-cluster clients on the same VPC don't always resolve DNS through the
internal zone, and so need to resolve the load balancer's internal hostname
through a public zone.
This change also seems more consistent with our published DNS configuration API
which doesn't mention the current behavior with regards to DNS and
internal/external. In fact, it's clear in the DNS configuration docs that the
presence …
> dns: always publish records to configured DNS zones

- HACKING.md
Updates hacking doc:
- uses make for uninstall
- fixes image name
> Updates Docs

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/operator_test.go
Implements [Wildcard Admission Policy](https://github.com/openshift/enhancements/pull/252) enhancement proposal.
/assign @ironcladlou @knobunc 
/cc @Miciah @frobware 
/hold until https://github.com/openshift/api/pull/607 merges.
> Adds Wildcard Admission Policy

- pkg/operator/controller/ingress/status.go
When reporting that the IngressController is degraded or may become degraded soon, list the causative status conditions.
* `pkg/operator/controller/ingress/status.go` (`computeDeploymentDegradedCondition`): List the degraded conditions in the error messages that are returned to (and logged by) the reconcile loop.
> Bug 1829584: computeDeploymentDegradedCondition: Better errors

- hack/run-local.sh
Updates the run-local script to use flags.
/assign @Miciah @knobunc 
/cc @frobware
> Bug 1835477: updates run-local script to use flags

- pkg/operator/controller/ingress/controller.go
`pkg/operator/controller/ingress/controller.go`: Updates `ensureIngressDeleted()` to delete the router deployment only when the `dnsrecord` object has been deleted. The router deployment is the owning object of the LB Service which is used by the AWS DNS provider to find the hosted zoned ID for record deletion (when the record is not cached).
/assign @Miciah @knobunc
> Bug 1850813: Delete Router Deployment Only Upon DNSRecord Deletion

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- test/e2e/http2_disable_test.go
> Bug 1854195: Invert http/2 kill switch logic

- pkg/operator/controller/dns/controller.go
Watch the cloud credentials secret and recreate the DNS provider if the credentials change.
* `pkg/operator/controller/dns/controller.go` (`New`): Watch the cloud credentials secret and trigger reconciliation if it changes.
(`reconciler`): Add `cloudCredentials` field.
(`Reconcile`): Refactor DNS provider create logic from here...
(`createDNSProviderIfNeeded`): ...to here.  Check if the cloud credentials secret data changed in addition to checking the infrastructure status to determine whether the DNS provider needs to be recreated.
> Bug 1854383: dns: Reread cloud credentials secret if it changes

- pkg/dns/aws/dns.go
Based on guidance from AWS [docs](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-r53.html), update AWS DNS to use the CNAME record type for the AWS GovCloud partition. All other regions continue to use the Alias record type.
/assign @knobunc @Miciah 
/cc @frobware @sgreene570 
xref: https://github.com/openshift/installer/pull/4043
> Bug 1869387: Adds CNAME support to AWS DNS

- pkg/operator/controller/ingress/deployment.go
Was reading through the pod affinity explanations and got a little confused, so I corrected some of the formatting/grammar mistakes.
> Fix up ingress controller deployment godocs

- pkg/operator/controller/certificate-publisher/publish_certs.go
- pkg/operator/controller/certificate/default_cert.go
certificate: Conditionally delete generated default cert 
pkg/operator/controller/certificate/default_cert.go: 
If an Ingress Controller is modified so that the Spec.DefaultCertificate field is now set, only delete the prior operator generated default certificate if the secret referenced by Spec.DefaultCertificate exists. This is to correct the bug identified in BZ 1887441 in which modifying an Ingress Controller to reference a secret that does not exist via Spec.DefaultCertificate breaks the authentication operator (which relies on the router-certs secret). This commit also cleans up the default_cert.go file to align with recent improvements in the ingress-operator codebase. Namely, the `currentRouterDefaultCertificate` and `desiredRouterDefaultCertificate` functions are enhanced so that …
> Bug 1887441: Conditionally delete generated default cert

- pkg/operator/controller/canary/controller.go
**pkg/opeator/controller/canary/controller.go:**
This commit forces the canary controller to hard-fail on any errors
encountered during the canary controller's reconcile function since none
of these errors are safe to continue on. This fix is to avoid nil
derefernce panics when the controller fails to ensure a resource.
---
This is a follow-up PR to https://github.com/openshift/cluster-ingress-operator/pull/533. I observed these canary controller panics when scrolling through recent CI failures via https://search.ci.openshift.org/?search=ingress-operator_previous.log.gz&maxAge=336h&context=1&type=junit&name=&maxMatches=5&maxBytes=20971520&groupBy=job .
> Bug 1917942: canary: Fail on all errors in `Reconcile(...)`

- test/e2e/operator_test.go
This commit adds a few small e2e test improvements in support of Bug
1948626.
test/e2e/operator_test.go:
Helper functions:
Increase the polling timeouts in `waitForRouterIngressConditions` and
`waitForClusterOperatorConditions` from 10 seconds to 1 minute.
1 minute is not much longer than 10 seconds, and presumably a longer
timeout for these polling functions could result in less test flakes.
It's worth taking the additional 50 seconds if it saves us from any
future `/retest` comments.
`TestRouteAdmissionPolicy`:
Use specific names for `route1` and `route2`, as to avoid the common
`route` name, which makes debugging this e2e test much easier.
Sleep for 2 (two) seconds after creating route1. This is to ensure that
route1 and route2 _do not_ wind up having the same creation timestamp.
If …
> Bug 1948626: test/e2e: Make `TestRouteAdmissionPolicy` deterministic.

- pkg/operator/controller/ingress/controller.go
pkg/operator/controller/ingress/controller.go:
Fix `setDefaultPublishingStrategy` so that updates to an Ingress
Controller's `spec.EndpointPublishingStrategy.LoadBalancer.ProviderParameters.GCP`
field are propagated to `status` correctly. Prior to this commit, GCP
provider parameter changes were only propagated to `status` if the
Ingress Controller was originally created with GCP provider parameters.
This commit resolves Bug 1949880, in which setting the GCP Global Access
provider parameter for an Ingress Controller created prior to an upgrade
resulted in no Load Balancer Service updates.
> Bug 1949880: ingress: Propagate GCP ProviderParameters to Status

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
openshift/router#291 gave the router
the ability to use stats credentials contained in separate username
and password files for security reasons.
This commit modifies the Ingress deployment so that the router-stats
secret is mounted into router pods, and the filenames for the username
and password files are passed to the Router binary via new
environment variables.
pkg/operator/controller/ingress/deployment.go:
Add a new volume and volume mount for the router stats secret.
Replace the STATS_USERNAME and STATS_PASSWORD environment variables with
the new STATS_USER_NAME_FILE and STATS_PASSWORD_FILE environment
variables.
pkg/operator/controller/ingress/deployment_test.go:
Update `TestDeploymentConfigChanged` to reflect the new stats-auth
volume.
Update `TestDesiredRouterDeployment` to …
> Bug 1955822: Ingress: Mount router stats secret as a volume

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
- pkg/operator/controller/names.go
- pkg/operator/controller/sync-http-error-code-configmap/controller.go
- pkg/operator/controller/sync-http-error-code-configmap/controller_test.go
- pkg/operator/controller/sync-http-error-code-configmap/httperrorcode_configmap.go
- pkg/operator/operator.go
- test/e2e/operator_test.go
https://issues.redhat.com/browse/NE-379
> Ability to Customize HAProxy 2.x Error Page

- pkg/operator/controller/dns/controller.go
With other platforms such as AWS, Azure, etc. and an external control plane (ie. Hypershift), we still want to create real DNS records for the wildcard route.
The usecase of Platform == IBMCloud and ControlPlaneTopology == External is the ROKS service. In ROKS, DNS is managed outside of the cluster. However, for Platforms like AWS, Azure, etc. and ControlPlaneTopology == External, the usecase is [Hypershift](https://github.com/openshift/hypershift). In Hypershift's use case we still rely on the cluster ingress operator to create DNS records as needed for IngressControllers in the same way that it is done when ControlPlaneTopology is not External.
> Bug 2011972: Use fake dns provider with external cp topology only in IBM Cloud case

- test/e2e/operator_test.go
Use a custom, private ingresscontroller for the scale test, and scale up from 1 replica to 2 and then back down to 1 replica, to avoid scheduling problems when creating an additional router pod replica during scale-up.
Before this change, the test used the default ingresscontroller and attempted to scale it up from 2 replicas to 3, which could fail if insufficient worker nodes were available.  This change reduces the likelihood of failures by using a private ingresscontroller (which doesn't require host ports) and scaling from 1 replica to 2 (which doesn't require as many worker nodes).
* `test/e2e/operator_test.go` (`TestIngressControllerScale`): Use a custom, private ingresscontroller, and start with 1 replica.
> TestIngressControllerScale: Use a private ingresscontroller

- pkg/operator/controller/ingress/status_test.go
Minor typo from 3b5ca42e07 (#693).
> pkg/operator/controller/ingress/status_test: Fix `...-tag` -> `...-tags` test-case description

- pkg/operator/controller/ingress/deployment_test.go
Unit test to check all EndpointPublishingStrategys sort the container env as a response to https://bugzilla.redhat.com/show_bug.cgi?id=1995953.
> Bug 1995953: Add unit test for verifying router deployment env is always sorted

- pkg/operator/controller/ingress/load_balancer_service.go
- test/e2e/operator_test.go
This is a manual cherry-pick of https://github.com/openshift/cluster-ingress-operator/pull/705.
---
/assign @rfredette
> [release-4.9] Bug 2057518: Normalize the AWS internal LB annotation value

- pkg/operator/controller/canary/controller.go
Adds a new status for IngressControllerCanaryCheckSuccessConditionType as unknown if the canary route is not admitted to the default ingress controller. It also doesn't attempt to probe canary route if probe routine is already started and canary route is not admitted.
> Bug 2021446: Set canary status as unknown if not admitted to default ingress controller

- test/e2e/operator_test.go
Due to numerous recent failures in matching expected to current conditions, add some logging to provide better CI results.  https://bugzilla.redhat.com/show_bug.cgi?id=2079468
> Bug 2079468: Enhance the waitForIngressControllerCondition for better CI results

- OWNERS
> add Ethany-RH to OWNERS

- pkg/operator/operator.go
Due to the way Hypershift is designed, it needs the ability to start the ingress operator in the hosted cluster namespace, and then create the default ingresscontroller object later on which hypershift's controllers manage. Right now we have a race between the ingress operator attempting to autocreate the default ingresscontroller and hypershift's controllers attempting to do it.
This PR modifies the ingress operator to not create the default ingress controller when the controlplane topology mode is set to `ExternalTopologyMode` which indicates that hypershift is in use.
> Bug 2108708: Disable auto creation of default ingress contoller for hypershift

- pkg/operator/controller/route-metrics/controller.go
- test/e2e/route_metrics_test.go
OCPBUGS-2848: Use matchExpressions for route and namespace selectors for route metrics (route_metrics_controller_routes_per_shard).
- `pkg/operator/controller/route-metrics/controller.go`: Modify logic to use entire routeSelector and namespaceSelector objects (including matchExpressions).
- `e2e/route_metrics_test.go`: Add matchExpressions to E2E to ensure testing
> OCPBUGS-2848: Support matchExpressions selectors with route metrics

- pkg/operator/controller/ingress/deployment.go
- pkg/operator/controller/ingress/deployment_test.go
Github issue: https://github.com/openshift/cluster-ingress-operator/issues/809
The bug is fixed and tested
> OCPBUGS-1725: Ingress controller should not have affinity policy in single-replica clusters

- pkg/operator/controller/ingress/load_balancer_service_test.go
Refactor Test_desiredLoadBalancerService  to simplify logic, remove extraneous test cases, and to make more readable.
> NE-1189: Refactor Test_desiredLoadBalancerService

- pkg/operator/controller/ingress/deployment.go
- test/e2e/all_test.go
- test/e2e/operator_test.go
Signed-off-by: kwall <kwall@apache.org>
> RFE-3007: Expose option-contstats as an unsupported option

- OWNERS
Add Thealisyed to the OWNERS file
> NO-JIRA: addowner-Thealisyed

- OWNERS
Add grzpiotrowski to the OWNERS file
> NO-JIRA: Add grzpiotrowski to OWNERS

- pkg/operator/controller/ingress/controller.go
- pkg/operator/controller/ingress/status.go
- pkg/operator/controller/ingress/status_test.go
Previously, the Upgradeable status was set to false if any certificates in the default certificate chain used SHA-1. However, HAProxy only rejects SHA-1 for the leaf (serving) certificate. This update ensures that the Upgradeable status is set to false only if the leaf certificate uses SHA-1, while ignoring other certificates in the chain.
> OCPBUGS-42480: Limit SHA-1 check to the leaf cert in default cert chain

- manifests/00-cluster-role.yaml
- pkg/manifests/assets/gateway-api/aggregated-cluster-roles/admin-cluster-role.yaml
- pkg/manifests/assets/gateway-api/aggregated-cluster-roles/view-cluster-role.yaml
- pkg/manifests/manifests.go
- pkg/manifests/manifests_test.go
- pkg/operator/controller/gatewayapi/controller.go
- pkg/operator/controller/gatewayapi/controller_test.go
- pkg/operator/controller/gatewayapi/rbac.go
- test/e2e/gateway_api_test.go
- test/e2e/util_gatewayapi_test.go
This adds aggregated ClusterRoles for Gateway API as per the "Security Policy" in the Gateway API EP.
> NE-1912: Add aggregated ClusterRoles for Gateway API

- pkg/operator/controller/gatewayclass/istio.go
Specify the "system-cluster-critical" priority class for the Istio control-plane.
> OCPBUGS-54568: desiredIstio: Specify priorityClassName

- test/e2e/gateway_api_test.go
- test/e2e/util_gatewayapi_test.go
This PR adds basic e2e tests for the Gateway API DNS feature.
The tests create gateways in different configurations and check for expected DNSRecords to be present or not existing, depending on the test case.
The test cases covered are:
- Multiple gateways with listeners of the same hostname.
- Multiple gateways with listeners with overlapping hostnames.
- Creating a gateway with multiple listeners and then updating and deleting the listeners to ensure the DNSRecords are reconciled accordingly.
- Gateway with a listener with no hostname.
> NE-1957: Add Gateway API DNS Feature e2e tests

- OWNERS
> NO-JIRA: Add rikatz to OWNERS

- OWNERS
Add new team member to approvers and reviewers
> NO-JIRA: Add bentito (btofel@redhat.com) to OWNERS
